### ISSUE TITLE
Upgrade jetty

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1041]
Upgrade of jetty from 9.3 to 9.4 resulted in broken image files as it now somehow automatically redirects to /index.html ... will revert https://github.com/graphhopper/graphhopper/commit/e8ff9a9398973cba6e03a65efcc1af5e4fa62bbd

**Comment by boldtrn** [comment]
There seems to be something wrong with the current jetty configuration anyway. When I start the server with the current master, I get exception for not found images, like the favicon or the picture generic vehicle.

```
WARN  org.eclipse.jetty.servlet.ServletHandler - /favicon.ico
java.lang.NullPointerException
	at com.graphhopper.http.GHBaseServlet.writeJsonError(GHBaseServlet.java:94)
	at com.graphhopper.http.InvalidRequestServlet.service(InvalidRequestServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.graphhopper.http.IPFilter.doFilter(IPFilter.java:60)
	at com.graphhopper.http.CORSFilter.doFilter(CORSFilter.java:38)
	at com.graphhopper.http.HeadFilter.doFilter(HeadFilter.java:37)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:448)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by karussell** [comment]
Did you recompile and force refresh in the browser? The 9.4 introduced this problem via redirecting to /index.html somehow and the old 9.3 does not have this problem

**Comment by michaz** [comment]
@boldtrn Thanks, that was an easy one. A NullPointerException in the code which is meant to handle bad requests, so nothing really bad, just someone else who produces the HTTP error.

*But* I am not getting any problems _at all_ with the Jetty upgrade. :-) Can you give steps to reproduce, @karussell ?

**Comment by michaz** [comment]
(preferably something independent of browser caches and such, so: request to path "/x/y/z" errors and shouldn't)?

**Comment by michaz** [comment]
By the way, on the other hand injecting ``GuiceFilter`` doesn't seem necessary and is a bit confusing, because it is ``GuiceFilter`` which _enables_ injecting Servlets. Inject it itself looks a bit weird.. Do you mind if I remove this, or do you need this for something down the chain? ,-)

**Comment by karussell** [comment]
> Can you give steps to reproduce, @karussell ?

The problem was only with the web UI. With the 9.4 version we get redirected to `/index.html` and the icons fails to resolve. With the 9.3 the page stays at `/`
