### ISSUE TITLE
NullPointerException when trying public transit

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1056]
Just tried the [steps here](https://github.com/graphhopper/graphhopper/tree/pt/reader-gtfs#quick-start) and got:

```
java.lang.NullPointerException
	at com.graphhopper.reader.gtfs.GraphExplorer.secondsOnTrafficDay(GraphExplorer.java:125)
	at com.graphhopper.reader.gtfs.GraphExplorer.access$500(GraphExplorer.java:32)
	at com.graphhopper.reader.gtfs.GraphExplorer$1$1.hasNext(GraphExplorer.java:70)
	at com.graphhopper.reader.gtfs.MultiCriteriaLabelSetting.calcPaths(MultiCriteriaLabelSetting.java:92)
```

for http://localhost:8989/?point=52.48278%2C13.362122&point=52.508699%2C13.485718&locale=en&vehicle=pt&weighting=fastest&elevation=false&use_miles=false&layer=Omniscale

(If this is a request problem like wrong time etc we need to throw a better error)

**Comment by karussell** [comment]
... was using an old graph cache. Maybe we should store a simple edge count or another 'hash value' to reduce likeliness of data vs. software 'mismatch'?

**Comment by michaz** [comment]
How would anything except the software revision number have helped here?

**Comment by karussell** [comment]
> How would anything except the software revision number have helped here?

Not sure :) ... we have e.g. a version in the flag encoder that needs to be updated when ('reader') incompatible changes are made

**Comment by boldtrn** [comment]
> Not sure :) ... we have e.g. a version in the flag encoder that needs to be updated when ('reader') incompatible changes are made

IMHO, this is the way to go. Usually reusing an old graph is no problem, if there is a breaking change, we should simply increase the version. Needing to re-import my local graphs, just because there was a change in the repo or something like this does not seem to be a good idea. Using the version number like 0.10, would be ok, but doesn't really help as the changes happen somewhere in between?
