### ISSUE TITLE
landmark preparation still not interrupted if failed

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1060]
Related to #107 and #980

It happily does the preprocessing further for the other profiles. Is this due to the error and not just an exception?

```
2017-05-11 06:42:48,403 [fastest_racingbike] ERROR com.graphhopper.routing.lm.LMAlgoFactoryDecorator - Problem while LM preparation fastest_racingbike
com.carrotsearch.hppc.BufferAllocationException: Not enough memory to allocate buffers for rehashing: 134,217,728 -> 268,435,456
        at com.carrotsearch.hppc.IntObjectHashMap.allocateBuffers(IntObjectHashMap.java:1109)
        at com.carrotsearch.hppc.IntObjectHashMap.allocateThenInsertThenRehash(IntObjectHashMap.java:1134)
        at com.carrotsearch.hppc.IntObjectHashMap.put(IntObjectHashMap.java:179)
        at com.graphhopper.routing.DijkstraBidirectionRef.fillEdges(DijkstraBidirectionRef.java:175)
        at com.graphhopper.routing.DijkstraBidirectionRef.fillEdgesFrom(DijkstraBidirectionRef.java:132)
        at com.graphhopper.routing.AbstractBidirAlgo.runAlgo(AbstractBidirAlgo.java:68)
        at com.graphhopper.routing.lm.LandmarkStorage$LandmarkExplorer.runAlgo(LandmarkStorage.java:748)
        at com.graphhopper.routing.lm.LandmarkStorage.createLandmarksForSubnetwork(LandmarkStorage.java:364)
        at com.graphhopper.routing.lm.LandmarkStorage.createLandmarks(LandmarkStorage.java:278)
        at com.graphhopper.routing.lm.PrepareLandmarks.doWork(PrepareLandmarks.java:130)
        at com.graphhopper.routing.lm.LMAlgoFactoryDecorator$1.run(LMAlgoFactoryDecorator.java:286)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at com.carrotsearch.hppc.IntObjectHashMap.allocateBuffers(IntObjectHashMap.java:1100)
        ... 17 more
2017-05-11 06:44:46,161 [fastest_foot] ERROR com.graphhopper.routing.lm.LMAlgoFactoryDecorator - Problem while LM preparation fastest_foot
com.carrotsearch.hppc.BufferAllocationException: Not enough memory to allocate buffers for rehashing: 134,217,728 -> 268,435,456
        at com.carrotsearch.hppc.IntObjectHashMap.allocateBuffers(IntObjectHashMap.java:1109)
        at com.carrotsearch.hppc.IntObjectHashMap.allocateThenInsertThenRehash(IntObjectHashMap.java:1134)
        at com.carrotsearch.hppc.IntObjectHashMap.put(IntObjectHashMap.java:179)
        at com.graphhopper.routing.DijkstraBidirectionRef.fillEdges(DijkstraBidirectionRef.java:175)
        at com.graphhopper.routing.DijkstraBidirectionRef.fillEdgesFrom(DijkstraBidirectionRef.java:132)
        at com.graphhopper.routing.AbstractBidirAlgo.runAlgo(AbstractBidirAlgo.java:68)
        at com.graphhopper.routing.lm.LandmarkStorage$LandmarkExplorer.runAlgo(LandmarkStorage.java:748)
        at com.graphhopper.routing.lm.LandmarkStorage.createLandmarksForSubnetwork(LandmarkStorage.java:364)
        at com.graphhopper.routing.lm.LandmarkStorage.createLandmarks(LandmarkStorage.java:278)
        at com.graphhopper.routing.lm.PrepareLandmarks.doWork(PrepareLandmarks.java:130)
        at com.graphhopper.routing.lm.LMAlgoFactoryDecorator$1.run(LMAlgoFactoryDecorator.java:286)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at com.carrotsearch.hppc.IntObjectHashMap.allocateBuffers(IntObjectHashMap.java:1101)
        ... 17 more
2017-05-11 06:47:51,418 [fastest_bike2] INFO  com.graphhopper.routing.lm.LandmarkStorage - Finding landmarks [fastest|bike2] in network [106422030]. Progress 0%, totalMB:163840, usedMB:13387
2017-05-11 06:47:54,283 [fastest_hike] INFO  com.graphhopper.routing.lm.LandmarkStorage - Finding la...
```

Furthermore the required RAM seems to be too high for the prepratation (25-35GB RAM per profile). Investigate this.

**Comment by karussell** [comment]
The problem is that if we have two profiles and we call completionService.take().get() then this call blocks until finished. And if this is a profile where no error was thrown the import won't stop soon. 

But there seems to be another problem as this failed preparation was ignored and the graph was successfully flushed.

**Comment by michaz** [comment]
>  Is this due to the error and not just an exception?

No, it's because the exception which is caught in line LMAlgoFactoryDecorator:289 is not rethrown.

**Comment by karussell** [comment]
> No, it's because the exception which is caught in line LMAlgoFactoryDecorator:289 is not rethrown.

Uhm, ugly small difference to CHAlgoFactoryDecorator which I didn't spotted - thanks!

**Comment by michaz** [comment]
> Uhm, ugly small difference to CHAlgoFactoryDecorator which I didn't spotted - thanks!

Sure. As a general point, maybe this is still too complicated. An exception which can't be handled just shouldn't be caught. Catching "only" to put the name of the thread into the log, and for private extra-bookkeeping in properties -- maybe that is all too much stuff and encourages errors.

**Comment by karussell** [comment]
Yes, will remove this catch stuff in the thread. Will keep the naming as it is helpful.

Still there is another ugly thing that we missed and should keep in mind: an error is not an exception! If we want to handle both we should use/catch Throwable instead of Exception. (You'll see that when you try eg. are Saxony with just 280MB and car&foot). And this is the reason why GH flushes happily although the error should be in the properties (it is not!).

Now, when an uncatched error happens inside the thread of the completionService the error is converted into an ExecutionException and so there would be no separate handling necessary here. So removing the catching inside the thread should solve all problems :)

**Comment by michaz** [comment]
> And this is the reason why GH flushes happily although the error should be in the properties (it is not!).

See? :-) Ideally, the mechanism which should prevent "flushing" should be the Exception _itself_ (that's what they are for!), not some code which picks them out of some properties afterwards. Every extra layer of self-invented stuff is a potential problem, I would go that far. :-)

**Comment by karussell** [comment]
Yes, sure. The bigger problem here is that I'm unsure why it was there at all ;( ... see #1061
