### ISSUE TITLE
If no RAM available on import it should not successfully finish

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#107]
```
Exception in thread "PBF Reader" java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:335)
    at com.graphhopper.reader.OSMInputFile.process(OSMInputFile.java:253)
    at com.graphhopper.reader.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:106)
    at com.graphhopper.reader.pbf.PbfDecoder.processBlobs(PbfDecoder.java:171)
    at com.graphhopper.reader.pbf.PbfDecoder.run(PbfDecoder.java:184)
    at com.graphhopper.reader.pbf.PbfReader.run(PbfReader.java:49)
    at java.lang.Thread.run(Thread.java:724)
2013-09-17 08:26:08,866 [main] INFO  graphhopper.reader.OSMReaderHelper - finished way processing. nodes: 6359398, osmIdMap.size:32437443, osmIdMap:381MB, osmIdMap.toString:Height:4, entries:247803 totalMB:968, usedMB:931
```

**Comment by boldtrn** [comment]
Is this issue still valid? I just tried it with the latest master and different amounts of RAM.

Either it hung up (I killed it, when there were not updates after the exception for at least a minute) or I received a `Process finished with exit code 1`, which should be OK? 

I tried about 10 different RAM settings, slowly increasing the RAM. Any ideas on how to reproduce this issue?

**Comment by karussell** [comment]
Have not experienced this in a long time. But it could be a similar problem like I stumbled over recently when one landmark thread crashed with: 

```
2017-02-26 16:36:06,143 [fastest_car] ERROR com.graphhopper.routing.lm.LMAlgoFactoryDecorator - Problem while LM preparation fastest_car
com.carrotsearch.hppc.BufferAllocationException: Not enough memory to allocate buffers for rehashing: 67,108,864 -> 134,217,728
        at com.carrotsearch.hppc.IntObjectHashMap.allocateBuffers(IntObjectHashMap.java:1109)
        at com.carrotsearch.hppc.IntObjectHashMap.allocateThenInsertThenRehash(IntObjectHashMap.java:1134)
        at com.carrotsearch.hppc.IntObjectHashMap.put(IntObjectHashMap.java:179)
        at com.graphhopper.routing.DijkstraBidirectionRef.fillEdges(DijkstraBidirectionRef.java:175)
        at com.graphhopper.routing.DijkstraBidirectionRef.fillEdgesFrom(DijkstraBidirectionRef.java:132)
        at com.graphhopper.routing.AbstractBidirAlgo.runAlgo(AbstractBidirAlgo.java:68)
        at com.graphhopper.routing.lm.LandmarkStorage$LandmarkExplorer.runAlgo(LandmarkStorage.java:743)
        at com.graphhopper.routing.lm.LandmarkStorage.createLandmarksForSubnetwork(LandmarkStorage.java:365)
        at com.graphhopper.routing.lm.LandmarkStorage.createLandmarks(LandmarkStorage.java:279)
        at com.graphhopper.routing.lm.PrepareLandmarks.doWork(PrepareLandmarks.java:130)
        at com.graphhopper.routing.lm.LMAlgoFactoryDecorator$1.run(LMAlgoFactoryDecorator.java:288)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at com.carrotsearch.hppc.IntObjectHashMap.allocateBuffers(IntObjectHashMap.java:1101)
        ... 13 more
```

But the preparation continues which should not be. So this is probably the missing exception catching in Runnable.run (in the LM or CH decorator) and might be missing in the import too.

**Comment by boldtrn** [comment]
Ok, thanks for the clarification, so we should try to replicate and fix this bug.

**Comment by boldtrn** [comment]
Should we equip all our Runnables with a try/catch block?

```
@Override
public void run() {
  try {
    // CODE
  } catch (Exception ex) {
    GloableException = ex
  }
}
```

At the end of the `importOrLoad` method we could check if there was an error and throw that exception on the main thread. This could be also implemented a bit nice by adding this to an ExceptionHandler where you can register the exception and throw them in the end.

**Comment by karussell** [comment]
> I found a couple of solutions using a Callable and Future for this

Yes, this is probably the way to go and should work for jdk7 too. But we should abort/interrupt the import for all other threads once one thread fails?

**Comment by boldtrn** [comment]
Should we close this now?
