### ISSUE TITLE
To little RAM in Graph Processing leads to weird Exception in LocationIndex

### ISSUE THREAD

**Issue by Gerungofulus** [graphhopper/graphhopper#1088]
I've been playing around with GH for a while now and everything worked fine so far, until I tried building the [latest and greatest all new and shiny graph of all of Europe](http://download.geofabrik.de/europe-latest.osm.pbf) with my little 16 GB machine (Mac OS) with 14Gb allocated for the JVM, when it was throwing the following error

```
2017-06-07 13:42:10,958 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - edges: 69505872, nodes 54314626, there were 2119927 subnetworks. removed them => 2119847 less nodes
Exception in thread "main" java.lang.IllegalStateException: location index was opened with incorrect graph: 54314817 vs. 54314626
	at com.graphhopper.storage.index.LocationIndexTree.loadExisting(LocationIndexTree.java:265)
	at com.graphhopper.GraphHopper.createLocationIndex(GraphHopper.java:1134)
	at com.graphhopper.GraphHopper.initLocationIndex(GraphHopper.java:1149)
	at com.graphhopper.GraphHopper.postProcessing(GraphHopper.java:842)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:650)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:619)
	at com.graphhopper.tools.Import.main(Import.java:31)
```
The error is included in GH versions 0.82 and 0.9. It did not appear when I ran the whole process on a 64GB Ubuntu 16.04. Server on which it was using more then 26GB.

**Comment by karussell** [comment]
This indicates a previously OutOfMemory error. What are the steps to reproduce this?

**Comment by Gerungofulus** [comment]
1. Download the most recent version of GH on a MBP 13" 2016 with 16 GB RAM
2. Download the latest Graph for all of Europe linked in the issue above.
3. Run `./graphhopper.sh import path/to/eruope.pbf`
4. There is no step 4

**Comment by karussell** [comment]
"europe" does not fit into the default settings, what JAVA_OPTS are you using?

**Comment by Gerungofulus** [comment]
-Xmx14g -Xms14g

**Comment by karussell** [comment]
And what config.properties? The default with CH, one vehicle profile (car) and without elevation?

**Comment by Gerungofulus** [comment]
Yes I didn't do any further changes because I thought at first that the mistake happened in my code so I used vanilla GH.

**Comment by karussell** [comment]
Ok, I'll try, have a 16g laptop (not a mac). Any other errors before in the log? Which JDK version?

**Comment by karussell** [comment]
I cannot reproduce this with the specified configuration and a current Europe file. Can you have a look at the logging output if there was an error before.

**Comment by Gerungofulus** [comment]
`## using java 1.8.0_131 (64bit) from /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
## using existing osm file /Users/pascalblunk/Coding/Calimoto/Graphen/Raw OSM/europe-latest.osm.pbf
## building graphhopper jar: tools/target/graphhopper-tools-0.10-SNAPSHOT-jar-with-dependencies.jar
## using maven at /usr/local/Cellar/maven/3.5.0/libexec
## now import. JAVA_OPTS=-Xmx14g -Xms14g
2017-06-07 10:22:31,309 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - version 0.10|2017-06-07T08:21:59Z (5,14,4,3,3,2)
2017-06-07 10:22:31,317 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - graph CH|car|RAM_STORE|2D|NoExt|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308, CHGraph|fastest|car, shortcuts:0, nodesCH:(0MB)
2017-06-07 10:22:31,338 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - start creating graph from /Users/pascalblunk/Coding/Calimoto/Graphen/Raw OSM/europe-latest.osm.pbf
2017-06-07 10:22:31,338 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - using CH|car|RAM_STORE|2D|NoExt|,,,,, memory:totalMB:12757, usedMB:199
2017-06-07 10:39:46,331 [main] INFO  com.graphhopper.reader.osm.OSMReader - 10 000 000 (preprocess), osmIdMap:82 815 455 (1013MB) totalMB:13032, usedMB:12586
2017-06-07 10:45:48,349 [main] INFO  com.graphhopper.reader.osm.OSMReader - 20 000 000 (preprocess), osmIdMap:179 656 547 (2139MB) totalMB:13062, usedMB:9966
2017-06-07 11:01:04,271 [main] INFO  com.graphhopper.reader.osm.OSMReader - 30 000 000 (preprocess), osmIdMap:273 499 595 (3235MB) totalMB:13069, usedMB:6349
2017-06-07 11:09:45,920 [main] INFO  com.graphhopper.reader.osm.OSMReader - 100 000 (preprocess), osmWayMap:0 totalMB:13105, usedMB:10379
2017-06-07 11:09:48,611 [main] INFO  com.graphhopper.reader.osm.OSMReader - 200 000 (preprocess), osmWayMap:0 totalMB:13146, usedMB:7442
2017-06-07 11:09:49,062 [main] INFO  com.graphhopper.reader.osm.OSMReader - 300 000 (preprocess), osmWayMap:0 totalMB:13146, usedMB:8767
2017-06-07 11:09:49,539 [main] INFO  com.graphhopper.reader.osm.OSMReader - 400 000 (preprocess), osmWayMap:0 totalMB:13146, usedMB:9885
2017-06-07 11:09:50,303 [main] INFO  com.graphhopper.reader.osm.OSMReader - 500 000 (preprocess), osmWayMap:0 totalMB:13146, usedMB:11123
2017-06-07 11:09:50,889 [main] INFO  com.graphhopper.reader.osm.OSMReader - 600 000 (preprocess), osmWayMap:0 totalMB:12997, usedMB:8088
2017-06-07 11:09:51,259 [main] INFO  com.graphhopper.reader.osm.OSMReader - 700 000 (preprocess), osmWayMap:0 totalMB:12997, usedMB:9345
2017-06-07 11:09:51,506 [main] INFO  com.graphhopper.reader.osm.OSMReader - 800 000 (preprocess), osmWayMap:0 totalMB:12997, usedMB:10475
2017-06-07 11:09:51,836 [main] INFO  com.graphhopper.reader.osm.OSMReader - 900 000 (preprocess), osmWayMap:0 totalMB:13137, usedMB:7639
2017-06-07 11:09:52,077 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 000 000 (preprocess), osmWayMap:0 totalMB:13137, usedMB:8770
2017-06-07 11:09:52,327 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 100 000 (preprocess), osmWayMap:0 totalMB:13137, usedMB:9899
2017-06-07 11:09:52,573 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 200 000 (preprocess), osmWayMap:0 totalMB:13137, usedMB:11027
2017-06-07 11:09:53,014 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 300 000 (preprocess), osmWayMap:0 totalMB:12976, usedMB:8206
2017-06-07 11:09:53,262 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 400 000 (preprocess), osmWayMap:0 totalMB:12976, usedMB:9260
2017-06-07 11:09:53,553 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 500 000 (preprocess), osmWayMap:0 totalMB:12976, usedMB:10514
2017-06-07 11:09:53,831 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 600 000 (preprocess), osmWayMap:0 totalMB:13142, usedMB:7532
2017-06-07 11:09:54,070 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 700 000 (preprocess), osmWayMap:0 totalMB:13142, usedMB:8667
2017-06-07 11:09:54,334 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 800 000 (preprocess), osmWayMap:0 totalMB:13142, usedMB:9842
2017-06-07 11:09:54,567 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 900 000 (preprocess), osmWayMap:0 totalMB:13142, usedMB:10896
2017-06-07 11:09:54,840 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 000 000 (preprocess), osmWayMap:0 totalMB:13138, usedMB:7898
2017-06-07 11:09:55,094 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 100 000 (preprocess), osmWayMap:0 totalMB:13138, usedMB:9115
2017-06-07 11:09:55,283 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 200 000 (preprocess), osmWayMap:0 totalMB:13138, usedMB:10169
2017-06-07 11:09:55,464 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 300 000 (preprocess), osmWayMap:0 totalMB:13138, usedMB:11190
2017-06-07 11:09:55,652 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 400 000 (preprocess), osmWayMap:0 totalMB:13150, usedMB:8188
2017-06-07 11:09:55,855 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 500 000 (preprocess), osmWayMap:0 totalMB:13150, usedMB:9414
2017-06-07 11:09:56,033 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 600 000 (preprocess), osmWayMap:0 totalMB:13150, usedMB:10435
2017-06-07 11:09:56,309 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 700 000 (preprocess), osmWayMap:0 totalMB:13145, usedMB:7537
2017-06-07 11:09:56,486 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 800 000 (preprocess), osmWayMap:0 totalMB:13145, usedMB:8515
2017-06-07 11:09:56,685 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 900 000 (preprocess), osmWayMap:0 totalMB:13145, usedMB:9695
2017-06-07 11:09:56,886 [main] INFO  com.graphhopper.reader.osm.OSMReader - 3 000 000 (preprocess), osmWayMap:0 totalMB:13145, usedMB:10672
2017-06-07 11:09:57,180 [main] INFO  com.graphhopper.reader.osm.OSMReader - 3 100 000 (preprocess), osmWayMap:0 totalMB:13158, usedMB:7783
2017-06-07 11:09:57,422 [main] INFO  com.graphhopper.reader.osm.OSMReader - 3 200 000 (preprocess), osmWayMap:0 totalMB:13158, usedMB:8852
2017-06-07 11:09:57,659 [main] INFO  com.graphhopper.reader.osm.OSMReader - 3 300 000 (preprocess), osmWayMap:0 totalMB:13158, usedMB:9922
2017-06-07 11:09:58,013 [main] INFO  com.graphhopper.reader.osm.OSMReader - 3 400 000 (preprocess), osmWayMap:0 totalMB:13158, usedMB:10949
2017-06-07 11:09:58,201 [main] INFO  com.graphhopper.reader.osm.OSMReader - creating graph. Found nodes (pillar+tower):325 427 021, totalMB:13154, usedMB:7827
2017-06-07 11:12:48,123 [main] INFO  com.graphhopper.reader.osm.OSMReader - 200 000 000, locs:60 681 557 (0) totalMB:13238, usedMB:9700
2017-06-07 11:16:20,480 [main] INFO  com.graphhopper.reader.osm.OSMReader - 400 000 000, locs:88 297 366 (0) totalMB:13272, usedMB:12258
2017-06-07 11:20:31,789 [main] INFO  com.graphhopper.reader.osm.OSMReader - 600 000 000, locs:125 156 105 (0) totalMB:13248, usedMB:8744
2017-06-07 11:23:36,788 [main] INFO  com.graphhopper.reader.osm.OSMReader - 800 000 000, locs:168 166 030 (0) totalMB:13266, usedMB:12792
2017-06-07 11:27:00,237 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 000 000 000, locs:208 332 380 (0) totalMB:13221, usedMB:8854
2017-06-07 11:28:26,072 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 200 000 000, locs:231 384 252 (0) totalMB:13087, usedMB:8263
2017-06-07 11:30:01,446 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 400 000 000, locs:258 767 837 (0) totalMB:13060, usedMB:7041
2017-06-07 11:31:34,710 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 600 000 000, locs:285 242 521 (0) totalMB:13099, usedMB:8156
2017-06-07 11:33:41,029 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 800 000 000, locs:310 953 253 (0) totalMB:13076, usedMB:8909
2017-06-07 11:34:39,871 [main] INFO  com.graphhopper.reader.osm.OSMReader - 1 902 775 916, now parsing ways
2017-06-07 11:47:09,068 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Бывалки — Ширково, 66Н-0830 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 11:47:22,993 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Взглядье — Ивано — Гудино — Добрушино, 66Н-0806 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 11:47:28,367 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Сельцо, 66Н-1407 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 11:47:28,369 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Урубок, 66Н-1443 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 11:47:28,369 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Стригино, 66Н-1428 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 11:47:28,369 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Сельцо, 66Н-1407 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 11:47:28,386 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Березкино — Большое Тишово, 66Н-0413 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 11:52:09,319 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Хиславичи — граница Республики Беларусь» — Прилепово, 66Н-1409 truncated to «Брянск — Смоленск до границы Республики Беларусь (через Рудню, 
2017-06-07 11:52:09,321 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Хиславичи — граница Республики Беларусь» — Владимировка, 66Н-2208 truncated to «Брянск — Смоленск до границы Республики Беларусь (через Рудню, 
2017-06-07 11:59:04,117 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Павлово, 66Н-0405 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:04:23,925 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги Смоленск — Вязьма)» — Тюшино — Нетризово — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Пересветово, 66Н-1049 truncated to «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги См
2017-06-07 12:04:52,893 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Беларусь» — от Москвы до границы с Республикой Беларусь (на Минск, Брест)» — Смогири — Болдино — «Витязи — Духовщина — Белый — Нелидово», 66Н-1019 truncated to «Беларусь» — от Москвы до границы с Республикой Беларусь (на Мин
2017-06-07 12:06:18,410 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Бояды, 66Н-1429 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:06:18,449 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Сельцо, 66Н-1407 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:06:55,670 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Хиславичи — граница Республики Беларусь» — Большие Хутора, 66Н-2210 truncated to «Брянск — Смоленск до границы Республики Беларусь (через Рудню, 
2017-06-07 12:07:08,597 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Битюково, 66Н-0818 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:07:08,598 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Щеплево, 66Н-0809 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:07:08,598 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Щеплево, 66Н-0809 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:07:08,599 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Чемуты — Полонец, 66Н-0823 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:07:08,599 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Битюково» — Шарапово — Иванево, 66Н-0815 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:07:54,012 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги Смоленск — Вязьма)» — Тюшино — Нетризово — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Шутовка, 66Н-1010 truncated to «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги См
2017-06-07 12:07:54,013 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Беларусь» — от Москвы до границы с Республикой Беларусь (на Минск, Брест)» — Смогири — Болдино — «Витязи — Духовщина — Белый — Нелидово», 66Н-1019 truncated to «Беларусь» — от Москвы до границы с Республикой Беларусь (на Мин
2017-06-07 12:07:54,013 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги Смоленск — Вязьма)» — Тюшино — Нетризово — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Попково — Павлихино, 66Н-1027 truncated to «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги См
2017-06-07 12:07:54,014 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Беларусь» — от Москвы до границы с Республикой Беларусь (на Минск, Брест)» — Смогири — Болдино — «Витязи — Духовщина — Белый — Нелидово», 66Н-1019 truncated to «Беларусь» — от Москвы до границы с Республикой Беларусь (на Мин
2017-06-07 12:07:54,014 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги Смоленск — Вязьма)» — Тюшино — Нетризово — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Бельчевицы, 66Н-1037 truncated to «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги См
2017-06-07 12:07:54,015 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги Смоленск — Вязьма)» — Тюшино — Нетризово — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Ломейково, 66Н-1030 truncated to «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги См
2017-06-07 12:07:54,015 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги Смоленск — Вязьма)» — Тюшино — Нетризово — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Святая Яровня, 66Н-1038 truncated to «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги См
2017-06-07 12:07:54,015 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги Смоленск — Вязьма)» — Тюшино — Нетризово — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Попково — Павлихино, 66Н-1027 truncated to «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги См
2017-06-07 12:08:21,776 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Красный — граница Республики Беларусь (участок Старой Смоленской дороги Красный — Ляды)» — Катково — Нейково — Марково — Туговище, 66Н-1114 truncated to «Красный — граница Республики Беларусь (участок Старой Смоленско
2017-06-07 12:08:21,776 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Красный — граница Республики Беларусь (участок Старой Смоленской дороги Красный — Ляды)» — Катково — Нейково — Марково — Туговище, 66Н-1114 truncated to «Красный — граница Республики Беларусь (участок Старой Смоленско
2017-06-07 12:14:50,999 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 000 000 000, locs:325 427 021 (0) totalMB:13264, usedMB:10014
2017-06-07 12:17:47,009 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Ладыжино — Красильники — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)», 66Н-1526 truncated to «Брянск — Смоленск до границы Республики Беларусь (через Рудню, 
2017-06-07 12:17:47,012 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Ладыжино — Красильники — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Бабичи, 66Н-1527 truncated to «Брянск — Смоленск до границы Республики Беларусь (через Рудню, 
2017-06-07 12:39:25,608 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Беларусь» — от Москвы до границы с Республикой Беларусь (на Минск, Брест)» — Жуково — Самолюбово» — Мазальцево — Фефелово» — Рязаново, 66Н-1877 truncated to «Беларусь» — от Москвы до границы с Республикой Беларусь (на Мин
2017-06-07 12:42:50,431 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Хиславичи — граница Республики Беларусь» — Новая Рудня, 66Н-2207 truncated to «Брянск — Смоленск до границы Республики Беларусь (через Рудню, 
2017-06-07 12:45:02,869 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Беларусь» — от Москвы до границы с Республикой Беларусь (на Минск, Брест)» — Жуково — Самолюбово» — Мазальцево — Фефелово» — Лаврово, 66Н-1852 truncated to «Беларусь» — от Москвы до границы с Республикой Беларусь (на Мин
2017-06-07 12:45:02,898 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Беларусь» — от Москвы до границы с Республикой Беларусь (на Минск, Брест)» — Жуково — Самолюбово» — Мазальцево — Фефелово» — Зыколино, 66Н-1851 truncated to «Беларусь» — от Москвы до границы с Республикой Беларусь (на Мин
2017-06-07 12:49:56,587 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Взглядье — Ивано — Гудино — Добрушино, 66Н-0806 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:49:56,587 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Павлово» — Сивцево, 66Н-0417 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:50:20,797 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Хиславичи — граница Республики Беларусь» — Новая Рудня» — Шатиловка, 66Н-2214 truncated to «Брянск — Смоленск до границы Республики Беларусь (через Рудню, 
2017-06-07 12:50:22,040 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Тростино — Петрополье — Хиславичи» — Думаничи — Торчиловка — Шанталово, 66Н-1418 truncated to «Брянск — Смоленск до границы Республики Беларусь (через Рудню, 
2017-06-07 12:50:22,040 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Сельцо, 66Н-1407 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:50:36,125 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Красный — граница Республики Беларусь (участок Старой Смоленской дороги Красный — Ляды)» — Катково — Нейково — Марково — Туговище, 66Н-1114 truncated to «Красный — граница Республики Беларусь (участок Старой Смоленско
2017-06-07 12:50:37,362 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги Смоленск — Вязьма)» — Тюшино — Нетризово — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Бельчевицы, 66Н-1037 truncated to «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги См
2017-06-07 12:50:37,362 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги Смоленск — Вязьма)» — Тюшино — Нетризово — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Пересветово, 66Н-1049 truncated to «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги См
2017-06-07 12:50:44,240 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Москва — Малоярославец — Рославль до границы с Республикой Беларусь (на Бобруйск, Слуцк)» — Спас-Деменск — Ельня — Починок» — Березкино — Большое Тишово, 66Н-0413 truncated to «Москва — Малоярославец — Рославль до границы с Республикой Бела
2017-06-07 12:57:17,270 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги Смоленск — Вязьма)» — Тюшино — Нетризово — «Брянск — Смоленск до границы Республики Беларусь (через Рудню, на Витебск)» — Пересветово, 66Н-1049 truncated to «Смоленск — Вязьма — Зубцов (участок Старой Смоленской дороги См
2017-06-07 13:07:07,205 [main] INFO  com.graphhopper.search.NameIndex - Way name is too long: «Беларусь» — от Москвы до границы с Республикой Беларусь (на Минск, Брест)» — Смогири — Болдино — «Витязи — Духовщина — Белый — Нелидово», 66Н-1019 truncated to «Беларусь» — от Москвы до границы с Республикой Беларусь (на Мин
2017-06-07 13:20:05,042 [main] INFO  com.graphhopper.reader.osm.OSMReader - 2 135 555 620, now parsing relations
2017-06-07 13:21:16,692 [main] INFO  com.graphhopper.reader.osm.OSMReader - finished way processing. nodes: 56434473, osmIdMap.size:326015169, osmIdMap:3838MB, nodeFlagsMap.size:588148, relFlagsMap.size:0, zeroCounter:581081 totalMB:13264, usedMB:12730
2017-06-07 13:21:16,703 [main] INFO  com.graphhopper.reader.osm.OSMReader - time pass1:2388s, pass2:7878s, total:10266s
2017-06-07 13:21:16,724 [main] INFO  com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks - start finding subnetworks (min:200, min one way:200) totalMB:13264, usedMB:12730
2017-06-07 13:27:10,268 [main] INFO  com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks - car findComponents time:353.51584, size:641653
2017-06-07 13:28:21,105 [main] INFO  com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks - 2119927 subnetworks found for car, totalMB:12975, usedMB:8807
2017-06-07 13:28:27,798 [main] INFO  com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks - optimize to remove subnetworks (2119927), unvisited-dead-end-nodes (1557739), maxEdges/node (17)
2017-06-07 13:42:10,958 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - edges: 69505872, nodes 54314626, there were 2119927 subnetworks. removed them => 2119847 less nodes
Exception in thread "main" java.lang.IllegalStateException: location index was opened with incorrect graph: 54314817 vs. 54314626
	at com.graphhopper.storage.index.LocationIndexTree.loadExisting(LocationIndexTree.java:265)
	at com.graphhopper.GraphHopper.createLocationIndex(GraphHopper.java:1134)
	at com.graphhopper.GraphHopper.initLocationIndex(GraphHopper.java:1149)
	at com.graphhopper.GraphHopper.postProcessing(GraphHopper.java:842)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:650)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:619)
	at com.graphhopper.tools.Import.main(Import.java:31)`

**Comment by karussell** [comment]
When you import can you remove the folder `europe-xy-gh`?

I'm not entirely sure why this can happen at all. The problem could be that an OutOfMem error could happen while CH preparation and the location index was created and flushed before, and then a new europe file is used with an existing but wrong location index.

**Comment by Gerungofulus** [comment]
I'll try tomorrow. 

Mit besten Physiker-Grüßen

**Comment by Gerungofulus** [comment]
Okay apparently the error occurred because a previous run had failed (because of to little memory) and when I restarted with more memory, it was building on the already existing but damaged data. I'm sorry for wasting your time.

**Comment by karussell** [comment]
No problem. Probably we should make the removal atomic.
