### ISSUE TITLE
Jetty bug when calling httpReq.getLocale()

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1118]
There is some reproducable problem in jetty for a certain locale setting which I do not know :(

```
2017-07-28 03:15:28,143 [qtp464064894-1142] WARN  org.eclipse.jetty.server.HttpChannel - /route
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.StringBuffer.charAt(StringBuffer.java:204)
        at org.eclipse.jetty.http.QuotedQualityCSV.parsedParam(QuotedQualityCSV.java:104)
        at org.eclipse.jetty.http.QuotedCSV.addValue(QuotedCSV.java:156)
        at org.eclipse.jetty.http.QuotedQualityCSV.addValue(QuotedQualityCSV.java:88)
        at org.eclipse.jetty.http.HttpFields.getQualityCSV(HttpFields.java:441)
        at org.eclipse.jetty.server.Request.getLocale(Request.java:857)
        at javax.servlet.ServletRequestWrapper.getLocale(ServletRequestWrapper.java:311)
        at javax.servlet.ServletRequestWrapper.getLocale(ServletRequestWrapper.java:311)
        at com.graphhopper.http.GraphHopperServlet.doGet(GraphHopperServlet.java:149)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
```

This might be [this code line](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedQualityCSV.java#L113) in jetty for an empty buffer:

```java
   protected void parsedParam(StringBuffer buffer, int valueLength, int paramName, int paramValue)
    {
        if (paramName<0)
        {
            if (buffer.charAt(buffer.length()-1)==';')
                buffer.setLength(buffer.length()-1);
}
```

**Comment by karussell** [comment]
This is already fixed here https://github.com/eclipse/jetty.project/issues/1351

**Comment by karussell** [comment]
It occurs very rarely (yesterday again)

**Comment by joakime** [comment]
What version of Jetty is this occurring on in your project?

**Comment by karussell** [comment]
At that time we were running 9.4.2.v20170220

But let's close as we have migrated to dropwizard and use also a different version of jetty.
