### ISSUE TITLE
local Graphhopper Server java.lang.IllegalStateException: Cannot load properties to fetch EncodingManager

### ISSUE THREAD

**Issue by AnnaSophieJaeger** [graphhopper/graphhopper#1156]
Hello!

I tried to set up my own Graphhopper Server using Ubuntu 16.04.. I already managed to do so, a couple of months ago and documented my steps. I used the same commands as the last time, but unfortunately I get a exception when I type: ./graphhopper.sh web europe_austria.pbf.

The exception is: 
Exception in thread "main" java.lang.IllegalStateException: Cannot load properties to fetch EncodingManager configuration at: ./europe_austria-gh/
        at com.graphhopper.routing.util.EncodingManager.create(EncodingManager.java:155)
        at com.graphhopper.GraphHopper.load(GraphHopper.java:726)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:618)
        at com.graphhopper.http.GraphHopperModule$2.start(GraphHopperModule.java:156)
        at com.graphhopper.http.GHServer.start(GHServer.java:123)
        at com.graphhopper.http.GHServer.start(GHServer.java:63)
        at com.graphhopper.http.GHServer.main(GHServer.java:58)

Maybe the last change in git caused this issue?

**Comment by karussell** [comment]
For questions please use our forum: https://discuss.graphhopper.com/c/graphhopper
