### ISSUE TITLE
Speed is 0 for low speed edges using motorcycle

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1234]
If you use the motorcycle profile and the curvature weighting and read an OSM way with a low maxspeed, for example maxspeed=2, the speed of the edge will be 0. An example way can be found [here](http://www.openstreetmap.org/way/367264051).

```
java.lang.IllegalStateException: Calculating time should not require to read speed from edge in wrong direction. Reverse:false, fwd:false, bwd:false
	at com.graphhopper.routing.weighting.AbstractWeighting.calcMillis(AbstractWeighting.java:44)
	at com.graphhopper.routing.weighting.FastestWeighting.calcMillis(FastestWeighting.java:83)
	at com.graphhopper.routing.Path.processEdge(Path.java:242)

```

**Comment by karussell** [comment]
When I think about this a bit more: this is kind of expected as we set access to false for speed==0 and so if speed is rounded downwards the result can be access==false. The only other solution would be a different rounding strategy if close to 0. But having speed==0 and access==true does not make sense.

**Comment by karussell** [comment]
But the question is why there is a path going through if access==false for both directions.

**Comment by boldtrn** [comment]
> But the question is why there is a path going through if access==false for both directions.

I think I found the issue here. The CurvatureWeighting has no clause `if(speed==0) return Double.POSITIVE_INFINITIVE`.

**Comment by karussell** [comment]
This is a more general problem that we always had problems with. 

For motorcycle we could solve it consistent: we could make the access-check dependent on speed==0 and do not use separate access bits as we have one speed value for every direction. 

But for other vehicles like car or foot we only want to use `speedBits+2` instead `speedBits*2` and so we need two separate access bits.

In the latest branch #1447 we could try to solve this via creating a special "combined" speed+access EncodedValue that handles this on the lowest level and switches to `speedBits*2` without any access bits if the speed value should be stored for both directions.
