### ISSUE TITLE
import custom pbf file , error

### ISSUE THREAD

**Issue by adustdu2015** [graphhopper/graphhopper#1310]
how to draw or make the pbf file corrent ,I can‘t open the pbf file made by myself ,but i don't know the error the pbf file.

**Comment by adustdu2015** [comment]
2018-03-16 15:41:29,539 [main] WARN  com.graphhopper.storage.BaseGraph - More th
an a half of the network should be removed!? Nodes:9, remove:9
Exception in thread "main" java.lang.IllegalStateException: graph is empty after
 in-place removal but was 9
        at com.graphhopper.storage.BaseGraph.inPlaceNodeRemove(BaseGraph.java:70
7)
        at com.graphhopper.storage.GraphHopperStorage.optimize(GraphHopperStorag
e.java:219)
        at com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks.doWork(P
repareRoutingSubnetworks.java:93)
        at com.graphhopper.GraphHopper.cleanUp(GraphHopper.java:1220)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:670)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:640)
        at com.graphhopper.http.GraphHopperModule$1.start(GraphHopperModule.java
:122)
        at com.graphhopper.http.GHServer.start(GHServer.java:122)
        at com.graphhopper.http.GHServer.start(GHServer.java:63)
        at com.graphhopper.http.GHServer.main(GHServer.java:58)

**Comment by karussell** [comment]
Please use our forum for questions
