### ISSUE TITLE
Add openjdk10 as build option

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1318]
There are problems with openjdk10 and so we should add it as an option. Travis currently does not support it but there are tools making it easy: https://github.com/travis-ci/travis-ci/issues/9368

Here is one warning (test if OracleJDK10 solves this)

```
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.graphhopper.api.GraphHopperMatrixGoogleIT.testMatrix(GraphHopperMatrixGoogleIT.java:28)
```

And then there is another problem (does not occur for java 9 as reader-shp is only activated for all other JDKs):

```
testTravelTimesBetweenPredefinedLocations(com.graphhopper.reader.shp.ShapeFileReaderTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.IllegalArgumentException: org.geotools.data.DataStoreFactorySpi is not an ImageIO SPI class
	at com.graphhopper.reader.shp.ShapeFileReaderTest.initHopper(ShapeFileReaderTest.java:117)
	at com.graphhopper.reader.shp.ShapeFileReaderTest.setupBeforeClass(ShapeFileReaderTest.java:130)
```

Geotools 19 should fix this as they implemented JDK 9 support then.

**Comment by karussell** [comment]
Using geotools 19.0 in reader-shp indeed makes it possible to compile it with openjdk10 but there is still a warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.geotools.resources.NIOUtilities (file:/home/ic/.m2/repository/org/geotools/gt-metadata/19.0/gt-metadata-19.0.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.geotools.resources.NIOUtilities
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
