### ISSUE TITLE
Geocoding test failues in client-hc module

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1325]
```
testForwardGeocodingNominatim(com.graphhopper.api.GraphHopperGeocodingIT)  Time elapsed: 0.742 sec  <<< ERROR!
java.lang.RuntimeException: 
Problem performing geocoding for https://graphhopper.com/api/1/geocode?reverse=false&q=Berlin&limit=5&locale=en&provider=nominatim&key=614b8305-b4db-48c9-bf4a-40de90919939: Can not deserialize instance of java.lang.Double[] out of START_OBJECT token
 at [Source: [B@29ef6856; line: 1, column: 124] (through reference chain: com.graphhopper.api.model.GHGeocodingResponse["hits"]->java.util.ArrayList[0]->com.graphhopper.api.model.GHGeocodingEntry["extent"])
	at com.graphhopper.api.GraphHopperGeocodingIT.testForwardGeocodingNominatim(GraphHopperGeocodingIT.java:49)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: 
Can not deserialize instance of java.lang.Double[] out of START_OBJECT token
 at [Source: [B@29ef6856; line: 1, column: 124] (through reference chain: com.graphhopper.api.model.GHGeocodingResponse["hits"]->java.util.ArrayList[0]->com.graphhopper.api.model.GHGeocodingEntry["extent"])
	at com.graphhopper.api.GraphHopperGeocodingIT.testForwardGeocodingNominatim(GraphHopperGeocodingIT.java:49)
```

**Comment by karussell** [comment]
Problem on server side: https://github.com/graphhopper/geocoder-converter/issues/38
