### ISSUE TITLE
Can't get graphhopper to start - java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by phildias** [graphhopper/graphhopper#1395]
Hi there,

I'm using the babun terminal on a Windows 10 PC with graphhopper 0.10.0 and JRE/JDK 1.8.0_171. 

When I try to set up the graphhopper server using a PBF file downloaded off geofabrik, I get the following error at some point of the bootup process:

    Exception in thread "pool-7-thread-1" Exception in thread "PBF Reader" java.lang.OutOfMemoryError: GC overhead limit exceeded

I've tried using a newer version of JRE/JDK and downloading other PBF files, but I keep getting the same error regardless of how small the PBF file is. I find this very odd, because the PBF file I'm trying to read is only 300MB and the PC I'm using has 192 GBs of RAM. 

Does anyone know what might be causing this?

I've copied all of the notifications I get in the terminal below.

I apologize if this is a super simple question!

Thanks in advance for the help!

```
{ graphhopper } master » ./graphhopper.sh web texas-latest.osm.pbf
## using java  from /cygdrive/c/Program Files/Java/jdk1.8.0_171
./graphhopper.sh: line 138: mvn: command not found
## using existing osm file texas-latest.osm.pbf
## building graphhopper jar: web/target/graphhopper-web-0.11-SNAPSHOT.jar
## using maven at ./maven
## now web. JAVA_OPTS=-Xms128m -Xmx256m
INFO  [2018-06-15 04:05:17,148] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2018-06-15 04:05:17,148] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2018-06-15 04:05:17,289] io.dropwizard.bundles.assets.ConfiguredAssetsBundle: Registering ConfiguredAssetBundle with name: assets for path /maps/*
INFO  [2018-06-15 04:05:17,289] io.dropwizard.server.ServerFactory: Starting GraphHopperApplication
                        _     _
   __ _ _ __ __ _ _ __ | |__ | |__   ___  _ __  _ __   ___ _ __
  / _` | '__/ _` | '_ \| '_ \| '_ \ / _ \| '_ \| '_ \ / _ \ '__|
 | (_| | | | (_| | |_) | | | | | | | (_) | |_) | |_) |  __/ |
  \__, |_|  \__,_| .__/|_| |_|_| |_|\___/| .__/| .__/ \___|_|
  |___/          |_|                     |_|   |_|

INFO  [2018-06-15 04:05:17,351] org.eclipse.jetty.setuid.SetUIDListener: Opened application@ac20bb4{HTTP/1.1,[http/1.1]}{localhost:8989}
INFO  [2018-06-15 04:05:17,351] org.eclipse.jetty.setuid.SetUIDListener: Opened admin@5a2bd7c8{HTTP/1.1,[http/1.1]}{localhost:8990}
INFO  [2018-06-15 04:05:17,351] org.eclipse.jetty.server.Server: jetty-9.4.z-SNAPSHOT; built: 2018-05-03T15:56:21.710Z; git: daa59876e6f384329b122929e70a80934569428c; jvm 1.8.0_171-b11
INFO  [2018-06-15 04:05:17,367] com.graphhopper.reader.osm.GraphHopperOSM: version 0.11|2018-06-15T04:04:35Z (5,14,4,3,3,2)
INFO  [2018-06-15 04:05:17,367] com.graphhopper.reader.osm.GraphHopperOSM: graph CH|car|RAM_STORE|2D|NoExt|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308, CHGraph|fastest|car, shortcuts:0, nodesCH:(0MB)
INFO  [2018-06-15 04:05:17,383] com.graphhopper.reader.osm.GraphHopperOSM: start creating graph from texas-latest.osm.pbf
INFO  [2018-06-15 04:05:17,383] com.graphhopper.reader.osm.GraphHopperOSM: using CH|car|RAM_STORE|2D|NoExt|,,,,, memory:totalMB:123, usedMB:25
Exception in thread "pool-7-thread-1" Exception in thread "PBF Reader" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.Long.valueOf(Long.java:840)
        at com.google.protobuf.LongArrayList.get(LongArrayList.java:126)
        at com.google.protobuf.LongArrayList.get(LongArrayList.java:45)
        at java.util.AbstractList$Itr.next(AbstractList.java:358)
        at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.processWays(PbfBlobDecoder.java:259)
        at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.processOsmPrimitives(PbfBlobDecoder.java:331)
        at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.runAndTrapExceptions(PbfBlobDecoder.java:343)
        at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.run(PbfBlobDecoder.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Unable to read PBF file.
        at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:50)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
        at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:253)
        at com.graphhopper.reader.osm.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:96)
        at com.graphhopper.reader.osm.pbf.PbfDecoder.processBlobs(PbfDecoder.java:151)
        at com.graphhopper.reader.osm.pbf.PbfDecoder.run(PbfDecoder.java:162)
        at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:47)
        ... 1 more
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
        at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:350)
        at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:251)
        ... 5 more
INFO  [2018-06-15 04:05:47,196] org.eclipse.jetty.server.AbstractConnector: Started application@ac20bb4{HTTP/1.1,[http/1.1]}{localhost:8989}
INFO  [2018-06-15 04:05:47,196] org.eclipse.jetty.server.AbstractConnector: Started admin@5a2bd7c8{HTTP/1.1,[http/1.1]}{localhost:8990}
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:3308)
        at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.ensureSize(GHLongIntBTree.java:364)
        at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.insertKeyValue(GHLongIntBTree.java:294)
        at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.put(GHLongIntBTree.java:223)
        at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.put(GHLongIntBTree.java:232)
        at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.put(GHLongIntBTree.java:232)
        at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.put(GHLongIntBTree.java:232)
        at com.graphhopper.coll.GHLongIntBTree.put(GHLongIntBTree.java:99)
        at com.graphhopper.reader.osm.OSMReader.prepareHighwayNode(OSMReader.java:577)
        at com.graphhopper.reader.osm.OSMReader.preProcess(OSMReader.java:170)
        at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:141)
        at com.graphhopper.GraphHopper.importData(GraphHopper.java:693)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:662)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:640)
        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:71)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:419)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:386)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:46)
```

**Comment by ammagamma** [comment]
>  now web. JAVA_OPTS=-Xms128m -Xmx256m

By default the JVM only uses a limited amount of memory of your system and you need to increase this. For example use `export JAVA_OPTS="-Xmx5g -Xms5g"` before you run `graphhopper.sh`.
For further usage related questions please use the forum, there are some related questions here:
https://discuss.graphhopper.com/search?q=xmx%20java_opts
