### ISSUE TITLE
error "The turn cost storage must be initialized only once."

### ISSUE THREAD

**Issue by develar** [graphhopper/graphhopper#1398]
Version: 0.11.0-pre1

In my config: `graph.flag_encoders: car|turn_costs=true,bike2,racingbike,mtb,hike`

```
+ ./graphhopper.sh -a import -i /Volumes/Pegasus/maps/australia-latest.osm.pbf -c /Users/develar/Documents/gh-routing-data/config.yml
## using java 1.8.0_172 (64bit) from 
## using existing osm file /Volumes/Pegasus/maps/australia-latest.osm.pbf
## existing jar found web/target/graphhopper-web-0.11-SNAPSHOT.jar
## now import. JAVA_OPTS=-Xmx15g -Xms10g -XX:+UseG1GC
INFO  [2018-06-16 06:13:58,777] com.graphhopper.reader.osm.GraphHopperOSM: version 0.11|2018-06-07T15:12:38Z (5,14,4,3,3,2)
INFO  [2018-06-16 06:13:58,782] com.graphhopper.reader.osm.GraphHopperOSM: graph CH|car,bike2,racingbike,mtb,hike|RAM_STORE|3D|turn_cost|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308, CHGraph|fastest|car, shortcuts:0, nodesCH:(0MB), CHGraph|fastest|bike2, shortcuts:0, nodesCH:(0MB), CHGraph|fastest|racingbike, shortcuts:0, nodesCH:(0MB), CHGraph|fastest|mtb, shortcuts:0, nodesCH:(0MB), CHGraph|fastest|hike, shortcuts:0, nodesCH:(0MB)
INFO  [2018-06-16 06:13:58,825] com.graphhopper.reader.osm.GraphHopperOSM: start creating graph from /Volumes/Pegasus/maps/australia-latest.osm.pbf
INFO  [2018-06-16 06:13:58,826] com.graphhopper.reader.osm.GraphHopperOSM: using CH|car,bike2,racingbike,mtb,hike|RAM_STORE|3D|turn_cost|,,,,, memory:totalMB:10240, usedMB:19
INFO  [2018-06-16 06:14:13,529] com.graphhopper.reader.osm.OSMReader: creating graph. Found nodes (pillar+tower):14 388 392, totalMB:10240, usedMB:294
INFO  [2018-06-16 06:14:13,541] com.graphhopper.reader.dem.CGIARProvider: cgiar Elevation Provider, from: http://srtm.csi.cgiar.org/SRT-ZIP/SRTM_V41/SRTM_Data_GeoTiff, to: /Users/develar/graphhopper-master/cgiar, as: MMAP_STORE using calcmean: false
INFO  [2018-06-16 06:17:37,511] com.graphhopper.reader.osm.OSMReader: 42 917 671, now parsing ways
INFO  [2018-06-16 06:18:03,549] com.graphhopper.reader.osm.OSMReader: 46 281 931, now parsing relations
INFO  [2018-06-16 06:18:03,667] com.graphhopper.reader.osm.OSMReader: finished way processing. nodes: 2314621, osmIdMap.size:14409849, osmIdMap:180MB, nodeFlagsMap.size:26378, relFlagsMap.size:36001, zeroCounter:21023 totalMB:10240, usedMB:3541
INFO  [2018-06-16 06:18:06,226] com.graphhopper.reader.osm.OSMReader: time pass1:14s, pass2:232s, total:247s
INFO  [2018-06-16 06:18:06,228] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: start finding subnetworks (min:200, min one way:200) totalMB:10240, usedMB:494
INFO  [2018-06-16 06:18:07,238] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: car findComponents time:1.0101064, size:20883
INFO  [2018-06-16 06:18:07,923] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: 381449 subnetworks found for car, totalMB:10240, usedMB:1095
INFO  [2018-06-16 06:18:08,982] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: bike2 findComponents time:1.0588369, size:31280
INFO  [2018-06-16 06:18:09,682] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: 120789 subnetworks found for bike2, totalMB:10240, usedMB:1573
INFO  [2018-06-16 06:18:10,720] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: racingbike findComponents time:1.0376482, size:31403
INFO  [2018-06-16 06:18:11,289] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: 123286 subnetworks found for racingbike, totalMB:10240, usedMB:2050
INFO  [2018-06-16 06:18:12,281] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: mtb findComponents time:0.99158376, size:31207
INFO  [2018-06-16 06:18:12,864] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: 119960 subnetworks found for mtb, totalMB:10240, usedMB:2526
INFO  [2018-06-16 06:18:13,801] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: hike findComponents time:0.9365595, size:20454
INFO  [2018-06-16 06:18:14,393] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: 80641 subnetworks found for hike, totalMB:10240, usedMB:2980
INFO  [2018-06-16 06:18:14,612] com.graphhopper.routing.subnetwork.PrepareRoutingSubnetworks: optimize to remove subnetworks (381449), unvisited-dead-end-nodes (364429), maxEdges/node (9)
INFO  [2018-06-16 06:18:14,955] com.graphhopper.reader.osm.GraphHopperOSM: edges: 3 049 022, nodes 2 253 040, there were 381 449 subnetworks. removed them => 61 581 less nodes
java.lang.AssertionError: The turn cost storage must be initialized only once.
	at com.graphhopper.storage.TurnCostExtension.init(TurnCostExtension.java:60)
	at com.graphhopper.storage.BaseGraph.<init>(BaseGraph.java:143)
	at com.graphhopper.storage.GraphHopperStorage.<init>(GraphHopperStorage.java:83)
	at com.graphhopper.util.GHUtility.newStorage(GHUtility.java:306)
	at com.graphhopper.GraphHopper.postProcessing(GraphHopper.java:854)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:671)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:640)
	at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:71)
	at com.graphhopper.http.cli.ImportCommand.run(ImportCommand.java:40)
	at com.graphhopper.http.cli.ImportCommand.run(ImportCommand.java:28)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:46)
```

How do I can enable turn costs for car?

**Comment by develar** [comment]
From https://github.com/graphhopper/graphhopper/blob/master/docs/core/turn-restrictions.md I see "Currently, it is not possible to use turn restrictions with the 'speed mode' (contraction hierarchies)", so, probably error message should be improved and explanation comment in the example config modified to make clear that you should use landmarks instead of CH.

**Comment by karussell** [comment]
It should be possible to use the config. For speed mode the turn costs will still be ignored (until #270 is fixed)

This is indeed a bug if additionally the configuration `graph.do_sort: true` is used.

**Comment by develar** [comment]
Thanks, indeed, problem in the "graph.do_sort: true". The same error if use landmarks and only car.

**Comment by trumpeta** [comment]
So turn costs currently are ignored everywhere or just in car/fast profile?

**Comment by karussell** [comment]
They are ignored if CH is used. If you disable CH they'll be used.

**Comment by karussell** [comment]
Ok

**Comment by Nakaner** [comment]
What does "Ok" mean? Yes or no? Sorry, I am a bit confused.

**Comment by karussell** [comment]
It means ok, I'm interested :)

**Comment by develar** [comment]
In 1.0-pre18 I have error `Sorting the graph is currently not supported in the presence of turn costs`. So, this issue type can be changed from bug to feature.

**Comment by easbar** [comment]
I think we can close. There is already #1773.
