### ISSUE TITLE
Isochrone bug if invalid coordinate

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1410]
If you use e.g. point=-1.81671943805717%2C51.557147756587 you get the following exception:
```
java.lang.IllegalStateException: Do not call QueryGraph.lookup with invalid QueryResult -1, -1.81671943805717,51.557147756587, -1
        at com.graphhopper.routing.QueryGraph.lookup(QueryGraph.java:230)
        at com.graphhopper.resources.IsochroneResource.doGet(IsochroneResource.java:81)
```

It should be an IllegalArgumentException

**Comment by karussell** [comment]
This is in #1407 ... but ok. This is stupid me in a double sense ;( as findbugs told me so
