### ISSUE TITLE
 java.lang.NullPointerException: Attempt to read from field 'org.oscim.core.BoundingBox org.oscim.tiling.source.mapfile.MapInfo.boundingBox' on a null object reference

### ISSUE THREAD

**Issue by anonym24** [graphhopper/graphhopper#1462]
```
09-21 00:02:12.925 11734-11734/com.graphhopper.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.graphhopper.android, PID: 11734
    java.lang.NullPointerException: Attempt to read from field 'org.oscim.core.BoundingBox org.oscim.tiling.source.mapfile.MapInfo.boundingBox' on a null object reference
        at com.graphhopper.android.MainActivity.loadMap(MainActivity.java:374)
        at com.graphhopper.android.MainActivity.downloadingFiles(MainActivity.java:308)
        at com.graphhopper.android.MainActivity.initFiles(MainActivity.java:197)
        at com.graphhopper.android.MainActivity.access$000(MainActivity.java:66)
        at com.graphhopper.android.MainActivity$2.onSelect(MainActivity.java:219)
        at com.graphhopper.android.MainActivity$4.onClick(MainActivity.java:297)
        at android.view.View.performClick(View.java:5215)
        at android.view.View$PerformClick.run(View.java:21196)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5613)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

```

**Comment by anonym24** [comment]
error happens here https://github.com/graphhopper/graphhopper/blob/master/android/app/src/main/java/com/graphhopper/android/MainActivity.java#L371

**Comment by devemux86** [comment]
Android sample demonstrates offline maps via [VTM](https://github.com/mapsforge/vtm) vector map library and offline routing via GraphHopper. Last time I checked the sample works as intended.

If you have made changes need to debug your implementation and see if map file is loaded correctly.

**Comment by anonym24** [comment]
I didn't do any changes, come on..
I cloned original project, did run it without any changes

p.s. remote german maps works

Local Ukraine didn't work 

what I did

1) downloaded original Android Project, didn't modify it
2) downloaded **ukraine.map** v4 http://download.mapsforge.org/maps/v4/europe/ukraine.map
There is no available v5 for Ukraine... mb it doesn't work because of it (are v3/v4 still supported?)
3) downloaded **ukraine-latest.osm.pbf** http://download.geofabrik.de/europe/ukraine-latest.osm.pbf
4) executed `./graphhopper.sh -a import -i ukraine-latest.osm.pbf` and I got *ukraine-latest.osm-gh* folder
5) copied **ukraine.map** to *ukraine-latest.osm-gh* folder and got next picture
![screenshot_17](https://user-images.githubusercontent.com/8851301/45868692-12e87f80-bd8f-11e8-972c-23498c36f5dd.png)
6) copied to my phone **storage/download/graphhopper/maps** directory
7) when I select this map in Graphhopper app it crashes with error a described above

**Comment by devemux86** [comment]
Can see how the folders of the working downloaded maps exist in filesystem and create similar path for any new area.
