### ISSUE TITLE
Memory problems using custom weights

### ISSUE THREAD

**Issue by FxKu** [graphhopper/graphhopper#1475]
Hey there,

in our research project we are using Graphhopper routing in combination with custom travel times. For each request every 15 minutes we call a service that returns the travel times for all edge IDs of one city (getActualTraveltimeDresden). The API looks like [this](https://www.excell-mobility.de/developer/docs.php?service=traveltime_service)

Then, we calculate the weights, see [TravelTimeWeighting](https://github.com/excell-mobility/routing_service/blob/master/src/main/java/restrouting/component/TravelTimeWeighting.java)

This works for some time/requests until we run out of memory. This is the stack:
```
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3284) ~[na:1.8.0_112]
        at com.carrotsearch.hppc.IntArrayList.ensureBufferSpace(IntArrayList.java:351) ~[hppc-0.7.2.jar!/:na]
        at com.carrotsearch.hppc.IntArrayList.add(IntArrayList.java:102) ~[hppc-0.7.2.jar!/:na]
        at com.graphhopper.routing.Path.addEdge(Path.java:113) ~[graphhopper-core-0.9.0.jar!/:na]
        at com.graphhopper.routing.Path.processEdge(Path.java:245) ~[graphhopper-core-0.9.0.jar!/:na]
        at com.graphhopper.routing.PathBidirRef.extract(PathBidirRef.java:90) ~[graphhopper-core-0.9.0.jar!/:na]
        at com.graphhopper.routing.AStarBidirection.extractPath(AStarBidirection.java:173) ~[graphhopper-core-0.9.0.jar!/:na]
        at com.graphhopper.routing.AbstractBidirAlgo.calcPath(AbstractBidirAlgo.java:62) ~[graphhopper-core-0.9.0.jar!/:na]
        at com.graphhopper.routing.AbstractRoutingAlgorithm.calcPaths(AbstractRoutingAlgorithm.java:116) ~[graphhopper-core-0.9.0.jar!/:na]
        at com.graphhopper.routing.template.ViaRoutingTemplate.calcPaths(ViaRoutingTemplate.java:115) ~[graphhopper-core-0.9.0.jar!/:na]
        at com.graphhopper.GraphHopper.calcPaths(GraphHopper.java:1048) ~[graphhopper-core-0.9.0.jar!/:na]
        at com.graphhopper.GraphHopper.route(GraphHopper.java:933) ~[graphhopper-core-0.9.0.jar!/:na]
        at restrouting.component.RoutingService.startRouting(RoutingService.java:85) ~[classes!/:0.1.0]
        at restrouting.controller.RoutingController.routing(RoutingController.java:49) ~[classes!/:0.1.0]
```

I'm not 100% sure, if this is a bug or if we simply use our own weighting in a very wrong way. I can send you the graphhopper graph (ca. 500 MB), OSM file and my token for using the travel time service if you want, because the edge ids of the travel time service only match against this graph. If you clone and run the `excell_routing` project you have to change some settings in the [application.properties](https://github.com/excell-mobility/routing_service/blob/master/src/main/resources/application.properties).

Please, let me know if
a. I shall provide more assistence for you to test?
b. in case this is a bug, it has already been fixed?
c. I'm using the weighting class the wrong way?

Keep up the great work!
Felix

**Comment by boldtrn** [comment]
I am not sure if this would better fit our [forum](https://discuss.graphhopper.com/)?

I only had a brief look at your custom weighting. The method `calcWeight` is called **a lot** when calculating a route. It can be called several thousand times to even million times for long routes. Everytime you create a 3 new maps (or map references, haven't checked the code). 

If you run out of memory over time, there might be a memory leak? Or is the map constantly growing without being emptied or something like this?

It might also be worthwhile to check the max visited nodes setting and try to limit the number of visited nodes.

**Comment by karussell** [comment]
> I am not sure if this would better fit our forum?

Yes, please. Questions or situations where you are unsure should go there first. Also we can only fix stuff that is reproducable with GH core. And if you are using non-CH you should at least enable landmark routing for queries > 500km.

> This works for some time/requests until we run out of memory.

This sounds like a memory leak. As we run our system with hundreds of millions of queries without memory issues, it is more likely to be usage issue.
