### ISSUE TITLE
Avoid returning null in GTFSFeed

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1513]
Instead of just logging we should throw an exception or would this break some code?

https://github.com/graphhopper/graphhopper/blob/master/reader-gtfs/src/main/java/com/conveyal/gtfs/GTFSFeed.java#L368

Related [discussion](https://discuss.graphhopper.com/t/issues-setting-up-gtfs-routing/3978), the full stacktrace is:

```
ERROR [2019-01-10 08:54:19,413] com.conveyal.gtfs.GTFSFeed: Could not construct db from file.
! java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
! ... 18 common frames omitted
! Causing: java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
! at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:269)
! at org.mapdb.StoreDirect.<init>(StoreDirect.java:207)
! at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:971)
! at org.mapdb.DBMaker.makeEngine(DBMaker.java:758)
! at org.mapdb.DBMaker.make(DBMaker.java:701)
! at com.conveyal.gtfs.GTFSFeed.constructDB(GTFSFeed.java:365)
! at com.conveyal.gtfs.GTFSFeed.<init>(GTFSFeed.java:352)
! at com.graphhopper.reader.gtfs.GtfsStorage.loadGtfsFromFile(GtfsStorage.java:198)
! at com.graphhopper.reader.gtfs.GraphHopperGtfs.createOrLoad(GraphHopperGtfs.java:347)
! at com.graphhopper.http.GraphHopperBundle.runPtGraphHopper(GraphHopperBundle.java:213)
! at com.graphhopper.http.GraphHopperBundle.run(GraphHopperBundle.java:202)
! at com.graphhopper.http.GraphHopperBundle.run(GraphHopperBundle.java:64)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:93)
! at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:33)
java.lang.RuntimeException: java.lang.NullPointerException
	at com.graphhopper.reader.gtfs.GtfsStorage.loadGtfsFromFile(GtfsStorage.java:203)
	at com.graphhopper.reader.gtfs.GraphHopperGtfs.createOrLoad(GraphHopperGtfs.java:347)
	at com.graphhopper.http.GraphHopperBundle.runPtGraphHopper(GraphHopperBundle.java:213)
	at com.graphhopper.http.GraphHopperBundle.run(GraphHopperBundle.java:202)
	at com.graphhopper.http.GraphHopperBundle.run(GraphHopperBundle.java:64)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:33)
Caused by: java.lang.NullPointerException
	at com.conveyal.gtfs.GTFSFeed.<init>(GTFSFeed.java:376)
	at com.conveyal.gtfs.GTFSFeed.<init>(GTFSFeed.java:352)
	at com.graphhopper.reader.gtfs.GtfsStorage.loadGtfsFromFile(GtfsStorage.java:198)
	... 10 more
```

**Comment by michaz** [comment]
Totally right, this is bad, will get this.
