### ISSUE TITLE
Building graph from OSM in case of loop edge fails.

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1533]
I am getting this error when trying to import this map: https://download.geofabrik.de/europe/germany-140101.osm.pbf. The error occurs due to the recent changes in #1531.
```
Exception in thread "PBF Reader" java.lang.RuntimeException: Unable to read PBF file.
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:50)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:253)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:96)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.processBlobs(PbfDecoder.java:151)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.run(PbfDecoder.java:162)
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:47)
	... 1 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:350)
	at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:251)
	... 5 more
ERROR [2019-02-04 07:38:59,164] com.graphhopper.reader.osm.OSMReader: Couldn't properly add edge with osm ids:[2603643788, 2603643788, 2569371457, 2517174531]
! java.lang.ArrayIndexOutOfBoundsException: -43
! at com.graphhopper.storage.RAMDataAccess.getInt(RAMDataAccess.java:207)
! at com.graphhopper.reader.PillarInfo.getLatitude(PillarInfo.java:83)
! at com.graphhopper.reader.osm.OSMReader.handlePillarNode(OSMReader.java:768)
! at com.graphhopper.reader.osm.OSMReader.addOSMWay(OSMReader.java:659)
```

**Comment by karussell** [comment]
Thanks, this is ugly. It looks like the nodes are already removed in the latest OSM data

One remaining node is [the last one](https://www.openstreetmap.org/node/2517174531),

 so this is likely some rare data constellation. I'll investigate - do you already have a reproducer :) ?

**Comment by easbar** [comment]
No I have not looked into it yet.

**Comment by karussell** [comment]
Will do

**Comment by karussell** [comment]
Is it possible for you to extract this "danneberg" area via e.g. osmosis or osmconvert? As I cannot reproduce this for the latest data set and it is no longer available in the archive: https://download.geofabrik.de/europe/germany/

(Another option is to copy this file to the server, so that I can extract it on my own)

**Comment by easbar** [comment]
Is the link to the file not working ?  https://download.geofabrik.de/europe/germany-140101.osm.pbf. Otherwise I will extract.

**Comment by karussell** [comment]
Ups, will try.

**Comment by karussell** [comment]
Can reproduce it for a loop like (same for the reverse nodes)

```
<way id="12" uid="85762">
        <nd ref="2"/>
        <nd ref="2"/>
        <nd ref="3"/>
        <nd ref="4"/>
        <nd ref="2"/>
        <tag k="name" v="B B C D B"/>
        <tag k="highway" v="secondary"/>
    </way>
```

What do you think - should we just throw a better message that the mapping is broken or accept such data?

**Comment by easbar** [comment]
Ugh, thats a weird double loop ;) Thanks for investigating!
Hmm I think rejecting maps with such artifacts would be rather annoying for users ? 
Then again I can see how handling such artifacts is difficult to do in our importer.
