### ISSUE TITLE
directions-api-client-hc 0.11+ requires Android min sdk version >= 26

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#1550]
directions-api-client-hc 0.11+ now has as dependency the graphhopper-web-api whose some code seems requiring Android min sdk version >= 26.

Note that directions-api-client-hc 0.10.3 works fine on Android, even in older versions.

```java
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/graphhopper/jackson/MultiExceptionSerializer.class
	at com.android.builder.dexing.DxDexArchiveBuilder.getExceptionToRethrow(DxDexArchiveBuilder.java:143)
	at com.android.builder.dexing.DxDexArchiveBuilder.convert(DxDexArchiveBuilder.java:89)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:904)
	... 6 more
Caused by: com.android.dx.cf.code.SimException: ERROR in com.graphhopper.jackson.MultiExceptionSerializer.serialize:(Lcom/graphhopper/MultiException;Lcom/fasterxml/jackson/core/JsonGenerator;Lcom/fasterxml/jackson/databind/SerializerProvider;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 16)
```

Since client-hc is used also in [graphhopper-navigation-example](https://github.com/graphhopper/graphhopper-navigation-example), such Android crashes could be catched if it [uses](https://github.com/graphhopper/graphhopper-navigation-example/blob/master/app/build.gradle) latest GraphHopper release and a Android recommended `minSdkVersion` (instead of 23).

**Comment by boldtrn** [comment]
I think the navigation example uses the generated client that can be found here: https://github.com/graphhopper/directions-api-clients

So this should be unrelated to this issue.

**Comment by devemux86** [comment]
Off topic: my advice would be to lower its `minSdkVersion` to current Android recommendation (15 or 16) and test it also on older Android emulator to cover all corner cases. Unless some dependency requires such high min Android version, but that leaves outside a large percentage of Android users and most developers definitely don't want that forced from their libraries. :slightly_smiling_face:

**Comment by boldtrn** [comment]
> Unless some dependency requires such high min Android version, but that leaves outside a large percentage of Android users and most developers definitely don't want that forced from their libraries.

Thanks I opened a different issue for the navigation-example. I think it should be possible to have a lower min sdk version.

**Comment by karussell** [comment]
@devemux86 do you have an idea what the problem could be? Obviously downgrading jackson could help, but I wouldn't like it. Or is it just the MultiExceptionSerializer class (if yes, why only this)?

**Comment by devemux86** [comment]
Unfortunately didn't have time to explore more the situation (reverted back to `0.10.3`). :slightly_smiling_face: 

But Android [documentation](https://developer.android.com/studio/write/java8-support) states:
_"Desugar currently doesn't support MethodHandle.invoke or MethodHandle.invokeExact. If your source code or one of your module dependencies use one of these methods you need to specify minSdkVersion 26 or higher."_

And the exception mentions that there is some _"invokedynamic requires --min-sdk-version >= 26"_.

**Comment by karussell** [comment]
Not sure how to continue here tbh. Did you try this: https://stackoverflow.com/questions/47137483/android-studio-3-0-dexarchivebuilderexception

**Comment by karussell** [comment]
Can you also can try a smaller jackson version like 2.9.0 or 2.8.0 in web-api/pom.xml?

If that would fix the problem, we could create a special client-hc bundle for Android.

If the serialization of the JTS objects makes problems while this you can also try to downgrade [this dep too](https://github.com/bedatadriven/jackson-datatype-jts#maven) but this would likely mean you will need to change GH again back to the older JTS 1.14.

**Comment by devemux86** [comment]
client-hc requires many dependencies, like OkHttp, Jackson, jackson-datatype-jts, JTS, graphhopper-web-api, other GraphHopper modules etc.

There can never be a guarantee that third-party dependencies won't be Android incompatible.

"Simplest" solution seems to just use in app regular HttpsURLConnection and org.json parsing, like doing already with other online services. :slightly_smiling_face:

**Comment by karussell** [comment]
> regular HttpsURLConnection and org.json parsing,

That would be a big sacrifice - feels a bit like assembler ;)

And of course maintenance can't be neglected. We need a solution that is easy to develop and maintain and compatible with not only the newest Android. I (wrongly) assumed that jackson including databind is working on Android properly.

**Comment by devemux86** [comment]
> That would be a big sacrifice - feels a bit like assembler ;)

More like some devs are willing to take the difficult path to keep things under control. :slightly_smiling_face: 

It's still remarkable that GraphHopper is one of few libs offering high level web clients.

Fact is that Java 8 support on Android remains complicated. Some calls need large min sdk version.
And [D8 dexer](https://android-developers.googleblog.com/2018/04/android-studio-switching-to-d8-dexer.html) is still avoided by several devs because can cause problems during app installation.

**Comment by karussell** [comment]
Writing a new client from scratch can't be the goal with our limited resources. Can you try with one smaller jackson dependency if this would work? If not, I fear we have to again postpone this issue to 0.13

> And D8 dexer is still avoided by several devs because can cause problems during app installation

Would D8 mean jdk8 compatibility?

**Comment by devemux86** [comment]
I tested with old jackson 2.8.4 (working with 0.10.3). Problem seems coming from web-api and jackson-datatype-jts. Could be solved if upgrade Android compile options to 1.8 and willing to [enable D8](https://android-developers.googleblog.com/2017/08/next-generation-dex-compiler-now-in.html).

**Comment by karussell** [comment]
Can you try with the latest master and jackson 2.8.4? (plus excluding jackson for jackson-datatype-jts)

I [released a new jackson-datatype-jts](https://github.com/graphhopper/jackson-datatype-jts/commits/gh) where I made sure to compile it with 1.7 as target using JDK8:

 * jackson-datatype-jts/0.12-2.5-0 with the original jackson databind dependency 2.4.2
 * jackson-datatype-jts/0.12-2.5-1 with the jackson databind 2.9.6 ([now used in GH core](https://github.com/graphhopper/graphhopper/commit/61203250219907c9066d6c29482267ea12451afa))

**Comment by devemux86** [comment]
Trying with GraphHopper 0.12-SNAPSHOT, Jackson 2.8.4 and jackson-datatype-jts 0.12-2.5-0 or 0.12-2.5-1 gets the same [above error](https://github.com/graphhopper/graphhopper/issues/1550#issue-413336035).
If look at exception, it's not only about compile, but also for using some [invoke method](https://developer.android.com/studio/write/java8-support#supported_features)?

Even with new dependencies, only can be solved if developers use app compile options for 1.8 and have enabled D8 dexer. If don't do both, the problem remains.

**Comment by karussell** [comment]
Thanks for trying again! This is ugly. I'm pretty sure we do not use something special and I read everywhere that jackson (even with databind) is possible on Android. (and jackson-datatype-jts is just a lib using where we have full control over)

**Comment by karussell** [comment]
I still thinks that the specific problem with 
```
invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 16
```

is not based on the fact that we use some special function but that a transitive dependency was compiled for Java 8. Is there a tool that could identify which of the jar or classes are the problems?

And because you are getting the same error even if are using the old jackson 2.8.4 maybe there is a dependency that still fetches the latest jackson causing this problem? Can you try the following command
```
mvn dependency:tree |  grep -v :test | grep jackson
```
and see if there are compile-time jackson deps with a different version?

**Comment by devemux86** [comment]
I hadn't transitive dependencies, so there is total control which dependencies are updated in the app.
The only updates were GraphHopper from 0.10.3 to 0.12-SNAPSHOT and new jackson-datatype-jts.

**Comment by carlos-mg89** [comment]
This isn't the case any more, or not at least in 0.13. I have included successfully the api client, in a project with minSdk 19:

`implementation 'com.graphhopper:directions-api-client-hc:0.13.0'`

**Comment by devemux86** [comment]
> This isn't the case any more, or not at least in 0.13. I have included successfully the api client, in a project with minSdk 19

@carlos-mg89 with what compile options, 1.7 or 1.8?
(mentioned [above](https://github.com/graphhopper/graphhopper/issues/1550#issuecomment-470652443) that works with 1.8)

**Comment by carlos-mg89** [comment]
Ouch, I didn't see it was working on Java 1.8.

Then no, and I cannot make it to work on 1.7, not because of Graphhopper api client, but because of other packages I have on the project as well.
