### ISSUE TITLE
Upgrade dropwizard to 2.0.0 when it is out to fix Exception in logs

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1558]
See [discussion](https://discuss.graphhopper.com/t/cant-load-pre-imported-graph-on-different-machine/4109/24)

Stacktrace:
```
org.glassfish.jersey.server.ServerRuntime$Responder: An I/O error has occurred while writing a response message entity to the container output stream.
! java.io.IOException: Broken pipe
! at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
! at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
! at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
! at sun.nio.ch.IOUtil.write(IOUtil.java:65)
! at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
! at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264)
! ... 11 common frames omitted
! Causing: org.eclipse.jetty.io.EofException: null
! at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:286)
! at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
! at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:384)
! at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:133)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:295)
! ... 6 common frames omitted
! Causing: org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
...........................
```

Reason: client disconnects too early

[Fix available in dw 2.0.0](https://github.com/dropwizard/dropwizard/pull/2541)

**Comment by karussell** [comment]
Already dropwizard 2.0.8 is out now, so we could consider switching to it: 
https://github.com/graphhopper/graphhopper/tree/dw20

@michaz any problems with this version?

**Comment by michaz** [comment]
@karussell None that I was aware of. I just dropped it in and it worked.

**Comment by karussell** [comment]
Ok, great! Will merge it then :)
