### ISSUE TITLE
config.yml not found

### ISSUE THREAD

**Issue by mghildiy** [graphhopper/graphhopper#1617]
Hi,

I imported the project in IntelliJ, and configured it as per this link:

https://github.com/graphhopper/graphhopper/blob/0.12/docs/core/quickstart-from-source.md#start-development

When I run the configuration, I get error as:

> java.io.FileNotFoundException: File config.yml not found
	at io.dropwizard.configuration.FileConfigurationSourceProvider.open(FileConfigurationSourceProvider.java:18)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:80)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:36)

Link instructs to pass config.yml as argument.

**Comment by mghildiy** [comment]
I found config-example.yml in the project, so used it as program argument. It works fine.
