### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'com.graphhopper.GHResponse com.graphhopper.GraphHopper.route(com.graphhopper.GHRequest)

### ISSUE THREAD

**Issue by zainriaz** [graphhopper/graphhopper#1621]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.graphhopper.GHResponse com.graphhopper.GraphHopper.route(com.graphhopper.GHRequest)' on a null object reference
        at com.junjunguo.pocketmaps.map.MapHandler$2.doInBackground(MapHandler.java:425)
        at com.junjunguo.pocketmaps.map.MapHandler$2.doInBackground(MapHandler.java:414)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762) 

this issue occur in new version 'com.graphhopper:graphhopper-core:0.13-SNAPSHOT'.
in 'com.graphhopper:graphhopper-core:0.10-SNAPSHOT' draw route working fine.

**Comment by akyzi007** [comment]
Facing the same issue. Any solution yet?

**Comment by karussell** [comment]
This is likely not the correct place to ask as you seem to use pocketmaps. Please post an issue there, but include more details like what you did step by step, what android version, what pocketmaps version etc!
