### ISSUE TITLE
CH vs. Dijkstra difference?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1622]
https://travis-ci.org/graphhopper/graphhopper/jobs/536951726

But this looks like the exact same weight, where time and distance are different:

```
[INFO] Running com.graphhopper.routing.ch.CHTurnCostTest
Graph that produced error:
WARNING: printGraphForUnitTest does not pay attention to custom edge speeds at the moment
na.setNode(0, 0.000000, 0.000000);
na.setNode(1, 0.000000, 0.000000);
na.setNode(2, 0.000000, 0.000000);
na.setNode(3, 0.000000, 0.000000);
na.setNode(4, 0.000000, 0.000000);
na.setNode(5, 0.000000, 0.000000);
na.setNode(6, 0.000000, 0.000000);
na.setNode(7, 0.000000, 0.000000);
na.setNode(8, 0.000000, 0.000000);
na.setNode(9, 0.000000, 0.000000);
na.setNode(10, 0.000000, 0.000000);
na.setNode(11, 0.000000, 0.000000);
na.setNode(12, 0.000000, 0.000000);
na.setNode(13, 0.000000, 0.000000);
na.setNode(14, 0.000000, 0.000000);
na.setNode(15, 0.000000, 0.000000);
graph.edge(0, 1, 1.687000, true);
graph.edge(1, 2, 2.074000, true);
graph.edge(2, 3, 2.700000, true);
graph.edge(4, 5, 1.772000, true);
graph.edge(5, 6, 3.643000, true);
graph.edge(6, 7, 0.807000, true);
graph.edge(8, 9, 2.388000, true);
graph.edge(9, 10, 2.978000, true);
graph.edge(10, 11, 1.936000, true);
graph.edge(12, 13, 0.358000, true);
graph.edge(13, 14, 2.048000, true);
graph.edge(14, 15, 0.464000, true);
graph.edge(0, 4, 1.018000, true);
graph.edge(1, 5, 1.869000, true);
graph.edge(2, 6, 1.427000, true);
graph.edge(3, 7, 1.065000, true);
graph.edge(4, 8, 1.677000, true);
graph.edge(5, 9, 3.046000, true);
graph.edge(6, 10, 2.178000, true);
graph.edge(7, 11, 3.131000, true);
graph.edge(8, 12, 3.979000, true);
graph.edge(9, 13, 2.706000, true);
graph.edge(10, 14, 3.486000, true);
graph.edge(11, 15, 2.642000, true);
graph.edge(0, 5, 2.441000, true);
graph.edge(1, 6, 3.083000, true);
graph.edge(1, 4, 0.851000, true);
graph.edge(2, 7, 1.941000, true);
graph.edge(2, 5, 0.834000, true);
graph.edge(3, 6, 3.834000, true);
graph.edge(4, 9, 0.915000, true);
graph.edge(5, 10, 2.505000, true);
graph.edge(5, 8, 0.003000, true);
graph.edge(6, 11, 2.881000, true);
graph.edge(6, 9, 1.737000, true);
graph.edge(7, 10, 1.339000, true);
graph.edge(8, 13, 0.180000, true);
graph.edge(9, 14, 3.446000, true);
graph.edge(9, 12, 0.591000, true);
graph.edge(10, 15, 1.910000, true);
graph.edge(10, 13, 1.483000, true);
graph.edge(11, 14, 2.022000, true);
[ERROR] Tests run: 30, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.484 s <<< FAILURE! - in com.graphhopper.routing.ch.CHTurnCostTest
[ERROR] testFindPath_highlyConnectedGraph_compareWithDijkstra(com.graphhopper.routing.ch.CHTurnCostTest)  Time elapsed: 2.996 s  <<< FAILURE!
java.lang.AssertionError: 
Dijkstra and CH did not find equal shortest paths for route from 8 to 12
 dijkstra: weight: 3.979, distance: 2.979, time: 1178, nodes: [8, 9, 12]
       ch: weight: 3.979, distance: 3.979, time: 238, nodes: [8, 12]
	at com.graphhopper.routing.ch.CHTurnCostTest.compareCHQueryWithDijkstra(CHTurnCostTest.java:1059)
	at com.graphhopper.routing.ch.CHTurnCostTest.compareCHWithDijkstra(CHTurnCostTest.java:1042)
	at com.graphhopper.routing.ch.CHTurnCostTest.testFindPath_highlyConnectedGraph_compareWithDijkstra(CHTurnCostTest.java:572)
```

**Comment by easbar** [comment]
Yes this situation can occur whenever some randomness of the graph is involved. I usually disable the 'strict check' (checking distance/time/nodes in addition to weight) for these cases, but forgot to do so for this test.

**Comment by karussell** [comment]
Thanks!
