### ISSUE TITLE
Several matched keys found for keyPrefix

### ISSUE THREAD

**Issue by routexl** [graphhopper/graphhopper#1735]
Ran into an error when creating new graph:

```
## using java  from C:/Program Files/Java/jdk1.8.0_152
./graphhopper.sh: line 138: mvn: command not found
## using existing osm file netherlands-latest.osm.pbf
## building graphhopper jar: web/target/graphhopper-web-0.14-SNAPSHOT.jar
## using maven at ./maven
## now web. JAVA_OPTS=-Xmx14G -Xms2G
2019-09-20 14:47:44.878 [main] INFO  i.d.server.DefaultServerFactory - Registering jersey handler with root path prefix: /
2019-09-20 14:47:44.880 [main] INFO  i.d.server.DefaultServerFactory - Registering admin handler with root path prefix: /
2019-09-20 14:47:45.284 [main] INFO  i.d.b.assets.ConfiguredAssetsBundle - Registering ConfiguredAssetBundle with name: assets for path /maps/*
2019-09-20 14:47:45.291 [main] INFO  io.dropwizard.server.ServerFactory - Starting GraphHopperApplication
                        _     _
   __ _ _ __ __ _ _ __ | |__ | |__   ___  _ __  _ __   ___ _ __
  / _` | '__/ _` | '_ \| '_ \| '_ \ / _ \| '_ \| '_ \ / _ \ '__|
 | (_| | | | (_| | |_) | | | | | | | (_) | |_) | |_) |  __/ |
  \__, |_|  \__,_| .__/|_| |_|_| |_|\___/| .__/| .__/ \___|_|
  |___/          |_|                     |_|   |_|

2019-09-20 14:47:45.329 [main] INFO  o.e.jetty.setuid.SetUIDListener - Opened application@ea52184{HTTP/1.1,[http/1.1]}{localhost:8989}
2019-09-20 14:47:45.329 [main] INFO  o.e.jetty.setuid.SetUIDListener - Opened admin@3e7b65d7{HTTP/1.1,[http/1.1]}{localhost:8990}
2019-09-20 14:47:45.330 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 1.8.0_152-b16
2019-09-20 14:47:45.345 [main] INFO  c.g.reader.osm.GraphHopperOSM - version 0.14|2019-09-20T12:47:24Z (5,15,4,3,3,5)
2019-09-20 14:47:45.348 [main] INFO  c.g.reader.osm.GraphHopperOSM - graph CH|car|RAM_STORE|2D|NoExt|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308, CHGraph|fastest|car|edge_based=false|u_turn_costs=-1, shortcuts:0, nodesCH:(0MB)
2019-09-20 14:47:45.360 [main] INFO  c.g.reader.osm.GraphHopperOSM - start creating graph from netherlands-latest.osm.pbf
2019-09-20 14:47:45.360 [main] INFO  c.g.reader.osm.GraphHopperOSM - using CH|car|RAM_STORE|2D|NoExt|,,,,, memory:totalMB:1963, usedMB:91
Exception in thread "PBF Reader" java.lang.RuntimeException: Unable to read PBF file.
        at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:50)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Thread was interrupted.
        at com.graphhopper.reader.osm.pbf.PbfDecoder.waitForUpdate(PbfDecoder.java:64)
        at com.graphhopper.reader.osm.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:83)
        at com.graphhopper.reader.osm.pbf.PbfDecoder.processBlobs(PbfDecoder.java:151)
2019-09-20 14:48:14.922 [main] ERROR io.dropwizard.cli.ServerCommand - Unable to start server, shutting down
java.lang.RuntimeException: Problem while parsing file
        at com.graphhopper.reader.osm.OSMReader.preProcess(OSMReader.java:199)
        at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:142)
        at com.graphhopper.GraphHopper.importData(GraphHopper.java:667)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:638)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:616)
        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:74)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.server.Server.start(Server.java:418)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:34)
Caused by: java.lang.IllegalArgumentException: Several matched keys found for keyPrefix restriction:
        at com.graphhopper.reader.ReaderElement.getKeyStartsWith(ReaderElement.java:108)
        at com.graphhopper.reader.osm.OSMReader.createTurnRelation(OSMReader.java:871)
        at com.graphhopper.reader.osm.OSMReader.prepareRestrictionRelation(OSMReader.java:204)
        at com.graphhopper.reader.osm.OSMReader.preProcess(OSMReader.java:185)
        ... 19 common frames omitted
```
Got it to work with this in ReaderElement.java:

```
public String getKeyStartsWith(String keyPrefix) {
        int nbMatchedKeys = 0;
        String matchedKey = null;
        for (String key : properties.keySet()) {
            if (key.startsWith(keyPrefix)) {
                nbMatchedKeys++;
                matchedKey = key;
            }
        }
        return matchedKey;
    }
```
But that's probably not the correct way to do it.

**Comment by easbar** [comment]
Thanks for reporting, this was introduced in #1683.

> But that's probably not the correct way to do it.

No, this would arbitrarily use the last matching key.

It is probably easiest to use the `0.13.0` release until this is fixed.

**Comment by easbar** [comment]
Since this is not trivial to fix, I reverted the conflicting commit in master and opened #1736.
