### ISSUE TITLE
Unable to setup Graphhopper with GTFS

### ISSUE THREAD

**Issue by SmartTransit** [graphhopper/graphhopper#1779]
Hi Graphhopper Team,

I followed all below steps :
git clone https://github.com/graphhopper/graphhopper
cd graphhopper
wget -O gtfs-vbb.zip http://transitfeeds.com/p/verkehrsverbund-berlin-brandenburg/213/latest/download
wget http://download.geofabrik.de/europe/germany/brandenburg-latest.osm.pbf
./graphhopper.sh build
java -Xmx8g -Xms8g \
  -Dgraphhopper.datareader.file=brandenburg-latest.osm.pbf \
  -Dgraphhopper.gtfs.file=gtfs-vbb.zip \
  -Dgraphhopper.graph.flag_encoders=pt \
  -Dgraphhopper.prepare.ch.weightings=no \
  -Dgraphhopper.graph.location=./graph-cache \
  -jar web/target/graphhopper-web-*.jar server config.yml

But when I am running above command I am getting below exception : 
**java.lang.UnsupportedOperationException: Read-only
	at org.mapdb.EngineWrapper$ReadOnlyEngine.put(EngineWrapper.java:191)
	at org.mapdb.HTreeMap.putInner(HTreeMap.java:589)
	at org.mapdb.HTreeMap.put(HTreeMap.java:488)
	at org.mapdb.HTreeMap$KeySet.add(HTreeMap.java:826)
	at com.graphhopper.reader.gtfs.GtfsStorage.loadGtfsFromFile(GtfsStorage.java:186)
	at com.graphhopper.reader.gtfs.GraphHopperGtfs.createOrLoad(GraphHopperGtfs.java:388)
	at com.graphhopper.http.GraphHopperBundle.runPtGraphHopper(GraphHopperBundle.java:199)
	at com.graphhopper.http.GraphHopperBundle.run(GraphHopperBundle.java:189)
	at com.graphhopper.http.GraphHopperBundle.run(GraphHopperBundle.java:62)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:36)**

Please help me with this. Thanks in Advance.

Regards,
Smart Transit Team
Volkswagen IT Services Pvt Ltd, India

**Comment by karussell** [comment]
Question should always go to our public forum first: https://discuss.graphhopper.com/c/graphhopper/public-transit

Include your config.yml and full log output

BTW: using the config-example.yml and current master I cannot reproduce this problem. You can also try switching to the latest stable branch 0.13

**Comment by SmartTransit** [comment]
Hi,
Thanks for your time @karussell.
Please find attachment of full log output and Config.yml file configuration. 
Thanks for the information about forum.

[Full Output Logs after running command.docx](https://github.com/graphhopper/graphhopper/files/3817902/Full.Output.Logs.after.running.command.docx)
[graphhopper_config-yml-file.docx](https://github.com/graphhopper/graphhopper/files/3817903/graphhopper_config-yml-file.docx)
