### ISSUE TITLE
Error while generating routing data with elevation in a few maps

### ISSUE THREAD

**Issue by carlos-mg89** [graphhopper/graphhopper#1822]
**Describe the bug**
I create this issue here, since I'm using pretty much the same config than in Graphhopper 0.11, but now it's in 0.13 where I'm trying to generate the routing data.

Using the same osm.pbf file, there are no problems in 0.11 but the following error log in 0.13.

It doesn't happen with all my osm.pbf, just with a few of them.

**To Reproduce**

Attached you'll find the config.yml for both 0.11 and 0.13. Basically, the difference is in the graph.encoded_values: road_class,road_class_link,road_environment,surface,road_access that it wasn't present in 0.11. However, I've tried commenting it and the result is the same.

There's RAM left when the crash happens. And there's enough free space in disk too

Config files:
[config-0.11.yml.txt](https://github.com/graphhopper/graphhopper/files/3950732/config-0.11.yml.txt)
[config-0.13.yml.txt](https://github.com/graphhopper/graphhopper/files/3950722/config-0.13.yml.txt)

1. Version 0.13 of Graphhopper
2. Link to the osm.pbf: https://we.tl/t-jBcUvymOU7 (it's Normandie, in France)
3. Run export JAVA_OPTS="-Xmx24g -Xms24g"; ./graphhopper.sh import ~/3793170.osm.pbf
4. See following error:

**Expected behaviour**
The expected behaviour was to see the routing data generated, as it happend in 0.11

**System Information**

- Java: 12.0.2 (64bit)
- OS: Ubuntu 19.10
- RAM: 32GB DDR4
- Graphhopper: 0.13

**Screenshots & Logs**

```
## using java 12.0.2 (64bit) from /usr/lib/jvm/java-12-oracle
## using existing osm file /home/carlos/workspace/osm-pbf-generator/countries/FR/3793170.osm.pbf
## existing jar found web/target/graphhopper-web-0.13-SNAPSHOT.jar
## now import. JAVA_OPTS=-Xmx22g -Xms22g
INFO  [2019-12-11 13:39:52,039] com.graphhopper.reader.osm.GraphHopperOSM: version 0.13|2019-12-09T11:51:05Z (5,15,4,3,3,5)
INFO  [2019-12-11 13:39:52,042] com.graphhopper.reader.osm.GraphHopperOSM: graph hike|MMAP_STORE|3D|NoExt|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308
INFO  [2019-12-11 13:39:52,051] com.graphhopper.reader.osm.GraphHopperOSM: start creating graph from /home/carlos/workspace/osm-pbf-generator/countries/FR/3793170.osm.pbf
INFO  [2019-12-11 13:39:52,051] com.graphhopper.reader.osm.GraphHopperOSM: using hike|MMAP_STORE|3D|NoExt|,,,,, memory:totalMB:22528, usedMB:87
INFO  [2019-12-11 13:39:58,470] com.graphhopper.reader.osm.OSMReader: creating graph. Found nodes (pillar+tower):2 570 684, totalMB:22528, usedMB:2854
INFO  [2019-12-11 13:39:58,485] com.graphhopper.reader.dem.CGIARProvider: cgiar Elevation Provider, from: http://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/, to: /home/carlos/workspace/graphhopper-0.13/srtmprovider, as: MMAP_STORE using calcmean: true
INFO  [2019-12-11 13:40:05,879] com.graphhopper.reader.osm.OSMReader: 21 402 086, now parsing ways
Exception in thread "PBF Reader" java.lang.RuntimeException: Unable to read PBF file.
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:50)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:253)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:96)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.processBlobs(PbfDecoder.java:151)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.run(PbfDecoder.java:162)
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:47)
	... 1 more
Caused by: java.lang.InterruptedException
ERROR [2019-12-11 13:40:10,299] com.graphhopper.reader.osm.OSMReader: Couldn't properly add edge with osm ids:[4395398499, 4395398500, 4395398501, 4395398508, 4395398502, 4395398512, 4395398517, 4395398515, 4395398516, 4395398513, 4395398518, 4395398514, 4395398519, 4395398511, 4395398499]
! java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 25
! at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
! at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
! at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
! at java.base/java.util.Objects.checkIndex(Objects.java:372)
! at java.base/java.util.ArrayList.get(ArrayList.java:458)
! at com.graphhopper.storage.MMapDataAccess.getInt(MMapDataAccess.java:347)
! at com.graphhopper.reader.PillarInfo.getLatitude(PillarInfo.java:83)
! at com.graphhopper.reader.osm.OSMReader.handlePillarNode(OSMReader.java:784)
! at com.graphhopper.reader.osm.OSMReader.addOSMWay(OSMReader.java:675)
! at com.graphhopper.reader.osm.OSMReader.processWay(OSMReader.java:404)
! at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:270)
! at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:146)
! at com.graphhopper.GraphHopper.importData(GraphHopper.java:667)
! at com.graphhopper.GraphHopper.process(GraphHopper.java:638)
! at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:616)
! at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:74)
! at com.graphhopper.http.cli.ImportCommand.run(ImportCommand.java:58)
! at com.graphhopper.http.cli.ImportCommand.run(ImportCommand.java:39)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:93)
! at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:34)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
	at java.base/java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:341)
	at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:251)
	... 5 more
java.lang.RuntimeException: Couldn't process file /home/carlos/workspace/osm-pbf-generator/countries/FR/3793170.osm.pbf, error: Index -1 out of bounds for length 25
	at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:294)
	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:146)
	at com.graphhopper.GraphHopper.importData(GraphHopper.java:667)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:638)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:616)
	at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:74)
	at com.graphhopper.http.cli.ImportCommand.run(ImportCommand.java:58)
	at com.graphhopper.http.cli.ImportCommand.run(ImportCommand.java:39)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:34)
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 25
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.graphhopper.storage.MMapDataAccess.getInt(MMapDataAccess.java:347)
	at com.graphhopper.reader.PillarInfo.getLatitude(PillarInfo.java:83)
	at com.graphhopper.reader.osm.OSMReader.handlePillarNode(OSMReader.java:784)
	at com.graphhopper.reader.osm.OSMReader.addOSMWay(OSMReader.java:675)
	at com.graphhopper.reader.osm.OSMReader.processWay(OSMReader.java:404)
	at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:270)
	... 11 more
```

**Comment by carlos-mg89** [comment]
Similar error happens in the current 1.0-pre11:

```
## using java 12.0.2 (64bit) from /usr/lib/jvm/java-12-oracle
## using existing osm file /home/carlos/workspace/osm-pbf-generator/countries/FR/3792876.osm.pbf
## existing jar found web/target/graphhopper-web-1.0-SNAPSHOT.jar
## now import. JAVA_OPTS=-Xmx22g -Xms22g
2019-12-11 15:36:04.266 [main] INFO  c.g.reader.osm.GraphHopperOSM - version 1.0|2019-12-11T14:27:12Z (5,15,4,3,5,5)
2019-12-11 15:36:04.269 [main] INFO  c.g.reader.osm.GraphHopperOSM - graph hike|RAM_STORE|3D|no_turn_cost|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308
2019-12-11 15:36:04.283 [main] INFO  c.g.reader.osm.GraphHopperOSM - start creating graph from /home/carlos/workspace/osm-pbf-generator/countries/FR/3792876.osm.pbf
2019-12-11 15:36:04.283 [main] INFO  c.g.reader.osm.GraphHopperOSM - using hike|RAM_STORE|3D|no_turn_cost|,,,,, memory:totalMB:22528, usedMB:95
2019-12-11 15:36:15.199 [main] INFO  com.graphhopper.reader.osm.OSMReader - creating graph. Found nodes (pillar+tower):5 475 791, totalMB:22528, usedMB:7467
2019-12-11 15:36:15.210 [main] INFO  c.g.reader.dem.CGIARProvider - cgiar Elevation Provider, from: http://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/, to: /home/carlos/workspace/graphhopper-1.0/srtmprovider, as: RAM_STORE using calcmean: true
2019-12-11 15:36:29.320 [main] INFO  com.graphhopper.reader.osm.OSMReader - 33 253 308, now parsing ways
2019-12-11 15:36:34.836 [main] ERROR com.graphhopper.reader.osm.OSMReader - Couldn't properly add edge with osm ids:[2504906090, 2504906082, 2504906061, 6246217291, 2504906044, 2504906073, 4679765577, 2504906092, 2504906086, 2504906067, 2126980157, 313553954, 2126980154, 313553953, 313553952, 2126980153, 2126980151, 2126980148, 2126980147, 2126980149, 2126980145, 2504906084, 2272857808, 2272857807, 4417908006, 5794426301, 2504906090]
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 53
	at com.graphhopper.storage.RAMDataAccess.getInt(RAMDataAccess.java:202)
	at com.graphhopper.reader.PillarInfo.getLatitude(PillarInfo.java:83)
	at com.graphhopper.reader.osm.OSMReader.handlePillarNode(OSMReader.java:749)
	at com.graphhopper.reader.osm.OSMReader.addOSMWay(OSMReader.java:640)
	at com.graphhopper.reader.osm.OSMReader.processWay(OSMReader.java:409)
	at com.graphhopper.reader.osm.OSMReader.writeOsmToGraph(OSMReader.java:275)
	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:150)
	at com.graphhopper.GraphHopper.importData(GraphHopper.java:688)
	at com.graphhopper.GraphHopper.readData(GraphHopper.java:667)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:654)
	at com.graphhopper.GraphHopper.importAndClose(GraphHopper.java:632)
	at com.graphhopper.http.cli.ImportCommand.run(ImportCommand.java:58)
	at com.graphhopper.http.cli.ImportCommand.run(ImportCommand.java:39)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:36)
Exception in thread "PBF Reader" java.lang.RuntimeException: Unable to read PBF file.
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:50)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:253)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:96)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.processBlobs(PbfDecoder.java:151)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.run(PbfDecoder.java:162)
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:47)
	... 1 more
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
	at java.base/java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:341)
	at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:251)
	... 5 more
java.lang.RuntimeException: Couldn't process file /home/carlos/workspace/osm-pbf-generator/countries/FR/3792876.osm.pbf, error: Index -1 out of bounds for length 53
	at com.graphhopper.reader.osm.OSMReader.writeOsmToGraph(OSMReader.java:299)
	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:150)
	at com.graphhopper.GraphHopper.importData(GraphHopper.java:688)
	at com.graphhopper.GraphHopper.readData(GraphHopper.java:667)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:654)
	at com.graphhopper.GraphHopper.importAndClose(GraphHopper.java:632)
	at com.graphhopper.http.cli.ImportCommand.run(ImportCommand.java:58)
	at com.graphhopper.http.cli.ImportCommand.run(ImportCommand.java:39)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:36)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 53
	at com.graphhopper.storage.RAMDataAccess.getInt(RAMDataAccess.java:202)
	at com.graphhopper.reader.PillarInfo.getLatitude(PillarInfo.java:83)
	at com.graphhopper.reader.osm.OSMReader.handlePillarNode(OSMReader.java:749)
	at com.graphhopper.reader.osm.OSMReader.addOSMWay(OSMReader.java:640)
	at com.graphhopper.reader.osm.OSMReader.processWay(OSMReader.java:409)
	at com.graphhopper.reader.osm.OSMReader.writeOsmToGraph(OSMReader.java:275)
	... 11 more
```

**Comment by carlos-mg89** [comment]
Same error is happening in 0.12 as well :(

**Comment by carlos-mg89** [comment]
I think my error is kind of related to this one https://discuss.graphhopper.com/t/exception-during-preprocessing-conversion-pillarnode-to-towernode-already-happended/4551

**Comment by carlos-mg89** [comment]
I've found the issue. Before, I was using Osmosis 0.45, and I've finally updated it to 0.47 and now the error has gone away.

Perhaps, in Osmosis 0.47, those nodes are removed, and in 0.45 they weren't. And somehow Graphhopper expected them to be there (perhaps correctly).

Will close the issue ;)

**Comment by carlos-mg89** [comment]
I'm reopening the issue, I messed it up with the folders, and I was generating the routing data with Graphhopper 0.11 instead of 0.13 (or 0.12). The error persists.

**Comment by karussell** [comment]
I can reproduce the issue with the provided pbf that make GH crash on this (loop) way: https://www.openstreetmap.org/way/441843519

Related to #1525 and #1533.

Debug info:

```
// i == 13
lastOsmNodeId = osmNodeIds.get(i - 1); // == 4395398511
lastGHNodeId == 1; //  => tmpNode = tmpNode - 3  => pillarInfo.getLatitude(-2);
```

This means the node is only contained in the way and no lat & lon information is provided in the node list section. So this is more a data issue although we should probably handle it without crashing (see OSMReader#L627 where we do this for non-loops)

**Comment by carlos-mg89** [comment]
Any quick fix that I could perform? Perhaps osmosis can get rid of them by passing a parameter when I obtain them (via polygon bounding)?

**Comment by carlos-mg89** [comment]
If we set the exitOnlyPillarNodeException property to false, would it just skip this nodes and continue the whole process instead of exiting? Or would it raise other issues somewhere else of that function (OSMReader#L627)?

I'm keen to help here.

**Comment by blas-rabella** [comment]
Any change on this issue?

**Comment by karussell** [comment]
There is currently no fix in the software, but when you fix the data (e.g. provide lat,lon for all nodes) then it will work.

**Comment by carlos-mg89** [comment]
@karussell do you have any idea about what could we do here?

Could we fix the OSM data? Could we manually edit the OSM to be processed?

Thanks in advance

**Comment by carlos-mg89** [comment]
I've figured out a way of solving this situation.

First of all, I must say that the OSM.PBF files that I'm using, I generate them myself by clipping the country with the POLY of the region. Like this:

`osmosis --rbf workers=12 country-from-geofabrik.osm.pbf --bp file=region.poly --wb region.osm.pbf`

So after rereading this thread, I thought that perhaps the issue was in the way Osmosis clips the region OSM.PBF.

So I added the `clipIncompleteEntities=true` option that works with the `--bp` Osmosis parameter, and then I tried to generate the Graphhopper data again. And this time it worked!

This is the command I use now to get the regions OSM.PBF files:

`osmosis --rbf workers=12 country-from-geofabrik.osm.pbf --bp file=region.poly clipIncompleteEntities=true --wb region.osm.pbf

I hope this helps anyone that faces the same situation. The `clipIncompleteEntities=true` is available as well when clipping by bounding box, not only by POLY file.

I emplace you @karussell to test this and if you can verify it, from my side this issue could be closed.

**Comment by karussell** [comment]
Thanks @carlos-mg89 for finding and reporting a solution to this. As you created the issue I think this is fine to close it if it works for you :)
