### ISSUE TITLE
Increase segmentSize for larger setups and MMAP

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1866]
On some production systems where the resulting graph folder is >100 GB we get:

For shared-outdoor it fails with either

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fd9299ab000, 262144, 0) failed; error='Not enough space' (errno=12)
```

or

```
2019-12-07 12:50:17.531 [main] ERROR io.dropwizard.cli.ServerCommand - Unable to start server, shutting down
java.lang.RuntimeException: Couldn't map buffer 1227 of 6421 for shortcuts_fastest_hike_node at position 1286602852 for 6732906396 bytes with offset 100, new fileLength:6732906596
        at com.graphhopper.storage.MMapDataAccess.mapIt(MMapDataAccess.java:237)
        at com.graphhopper.storage.MMapDataAccess.loadExisting(MMapDataAccess.java:296)
        at com.graphhopper.storage.CHGraphImpl.loadExisting(CHGraphImpl.java:358)
        at com.graphhopper.storage.GraphHopperStorage.loadExisting(GraphHopperStorage.java:260)
        at com.graphhopper.GraphHopper.load(GraphHopper.java:774)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:615)
        at 
...
Caused by: java.io.IOException: Map failed
        at java.base/sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:1016)
        at com.graphhopper.storage.MMapDataAccess.newByteBuffer(MMapDataAccess.java:252)
        at com.graphhopper.storage.MMapDataAccess.mapIt(MMapDataAccess.java:230)
        ... 20 common frames omitted
Caused by: java.lang.OutOfMemoryError: Map failed
```

So even decreasing the -Xmx argument, increasing graph.dataaccess.segment_size or increasing /proc/sys/vm/max_map_count did not help.

The reason is simple: alhtough we can certainly change the segment size, the segment size value is stored while import into the header of every DataAccess file and [then read](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/AbstractDataAccess.java#L111) on loadExisting. This will overwrite any previously set value.

I.e. too many memory mapped files are created and when increasing the default segment size we could avoid this. We could also try to move the often separately handled segmentSize into the GHDirectory and make it a final variable in the DataAccess objects.

A workaround should be also simple via using `graph.dataaccess.segment_size: 16777216` in the config.yml. But need to try this later.

**Comment by boldtrn** [comment]
I just saw a similar exception when importing the planet file with skadi set as elevation provider. In my case this was fixable by increasing the `max_map_count`. The issue was, as far as I can tell, created by skadi, since there are a lot more files and data to consider compared to other providers like CGIAR.
