### ISSUE TITLE
Build error: location index was opened with incorrect graph

### ISSUE THREAD

**Issue by gonick** [graphhopper/graphhopper#1896]
2020-02-10 07:58:09.197 [main] INFO  c.g.r.s.PrepareRoutingSubnetworks - start finding subnetworks (min:200, min one way:200) totalMB:61440, usedMB:46678
2020-02-10 08:45:24.372 [main] INFO  c.g.r.s.PrepareRoutingSubnetworks - car-access|version=-318709518|bits=1|index=0|shift=24|store_both_directions=true findComponents time:2835.1724, size:1913826
2020-02-10 08:46:44.690 [main] INFO  c.g.r.s.PrepareRoutingSubnetworks - 7123790 subnetworks found for car, totalMB:61440, usedMB:30635
2020-02-10 08:47:03.589 [main] INFO  c.g.r.s.PrepareRoutingSubnetworks - optimize to remove subnetworks (7123790), unvisited-dead-end-nodes (5836035), maxEdges/node (26)
2020-02-10 12:38:14.976 [main] INFO  c.g.reader.osm.GraphHopperOSM - edges: 249 769 775, nodes 187 882 536, there were 7 123 790 subnetworks. removed them => 7 122 505 less nodes
2020-02-10 12:38:22.098 [main] ERROR io.dropwizard.cli.ServerCommand - Unable to start server, shutting down
java.lang.IllegalStateException: location index was opened with incorrect graph: 187882454 vs. 187882536
        at com.graphhopper.storage.index.LocationIndexTree.loadExisting(LocationIndexTree.java:268)
        at com.graphhopper.GraphHopper.createLocationIndex(GraphHopper.java:1158)
        at com.graphhopper.GraphHopper.initLocationIndex(GraphHopper.java:1173)
        at com.graphhopper.GraphHopper.postProcessing(GraphHopper.java:853)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:647)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:616)
        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:74)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.server.Server.start(Server.java:418)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:34)
java.lang.IllegalStateException: location index was opened with incorrect graph: 187882454 vs. 187882536
        at com.graphhopper.storage.index.LocationIndexTree.loadExisting(LocationIndexTree.java:268)
        at com.graphhopper.GraphHopper.createLocationIndex(GraphHopper.java:1158)
        at com.graphhopper.GraphHopper.initLocationIndex(GraphHopper.java:1173)
        at com.graphhopper.GraphHopper.postProcessing(GraphHopper.java:853)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:647)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:616)
        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:74)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.server.Server.start(Server.java:418)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:34)

**Comment by karussell** [comment]
Please create a new topic in the forum and what steps lead to this error.
