### ISSUE TITLE
cant start the demo, error msg appears, windows 10 x64 pro

### ISSUE THREAD

**Issue by feiercrack** [graphhopper/graphhopper#1927]
C:\Users\ironb\Downloads\Graphhopper>java -Ddw.graphhopper.datareader.file=berlin-latest.osm.pbf -jar graphhopper-web-0.13.0.jar server config-example.yml
io.dropwizard.configuration.ConfigurationParsingException: config-example.yml has an error:
  * Unrecognized field at: server.application_connectors
    Did you mean?:
      - applicationConnectors
      - applicationContextPath
      - adminConnectors
      - adminMinThreads
      - allowedMethods
        [22 more]

        at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:140)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:34)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "application_connectors" (class io.dropwizard.server.DefaultServerFactory), not marked as ignorable (27 known properties: "registerDefaultExceptionMappers", "gid", "idleThreadTimeout", "applicationContextPath", "detailedJsonProcessingExceptionMapper", "user", "uid", "nofileHardLimit", "adminMaxThreads", "gzip", "maxQueuedRequests", "umask", "shutdownGracePeriod", "maxThreads", "adminMinThreads", "rootPath", "allowedMethods", "enableThreadNameFilter", "nofileSoftLimit", "adminConnectors", "applicationConnectors", "minThreads", "serverPush", "group", "startsAsRoot", "requestLog", "adminContextPath"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.graphhopper.http.GraphHopperServerConfiguration["server"]->io.dropwizard.server.DefaultServerFactory["application_connectors"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:178)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:105)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
        ... 6 more

C:\Users\ironb\Downloads\Graphhopper>

**Comment by karussell** [comment]
See #1925
