### ISSUE TITLE
Cannot re-run tests in IntelliJ since adding Junit5

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1970]
Anyone else having this issue? I often run all tests and then would like to re-run those which failed. But since we added JUnit I am getting errors like this: 

```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:189)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:124)
	at com.intellij.junit5.JUnit5IdeaTestRunner.getTestToStart(JUnit5IdeaTestRunner.java:88)
	at com.intellij.rt.junit.JUnitForkedSplitter.createRootDescription(JUnitForkedSplitter.java:30)
	at com.intellij.rt.execution.testFrameworks.ForkedSplitter.startSplitting(ForkedSplitter.java:37)
	at com.intellij.rt.execution.testFrameworks.ForkedByModuleSplitter.startSplitting(ForkedByModuleSplitter.java:60)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:227)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: org.junit.platform.commons.JUnitException: MethodSelector [className = 'com.graphhopper.api.GraphHopperMatrixIT', methodName = 'testPointsNotFound_doNotFailFast[BATCH = false, maxUnzippedLength = 0]', methodParameterTypes = ''] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:45)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:181)
	... 8 more
Caused by: org.junit.platform.commons.PreconditionViolationException: Could not find method with name [testPointsNotFound_doNotFailFast[BATCH = false, maxUnzippedLength = 0]] in class [com.graphhopper.api.GraphHopperMatrixIT].
	at org.junit.platform.engine.discovery.MethodSelector.lambda$lazyLoadJavaMethod$2(MethodSelector.java:176)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.junit.platform.engine.discovery.MethodSelector.lazyLoadJavaMethod(MethodSelector.java:174)
	at org.junit.platform.engine.discovery.MethodSelector.getJavaMethod(MethodSelector.java:149)
	at org.junit.jupiter.engine.discovery.MethodSelectorResolver.resolve(MethodSelectorResolver.java:69)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:146)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
	... 13 more
```

**Comment by michaz** [comment]
Works fine for me, even with mixed tests! Version:

```
IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Build #IU-193.6911.18, built on March 17, 2020
Licensed to GraphHopper GmbH / Michael Zilske
Subscription is active until October 18, 2020
Runtime version: 11.0.6+8-b520.43 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: org.intellij.scala
```

**Comment by karussell** [comment]
> Works fine for me, even with mixed tests!

For me it is fine too.
```
IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by easbar** [comment]
Ok, thanks good to know. I will try to find out why it does not work for me and post here in case I find out.

**Comment by easbar** [comment]
I updated IDEA to 2020.1 and now it seems fine (not sure what this was) :+1:
