### ISSUE TITLE
NoSuchMethodError while PBF processing

### ISSUE THREAD

**Issue by sgerr** [graphhopper/graphhopper#2047]
While trying to read PBF file from disk using Graphhopper.importOrLoad() getting such an error:

```
Exception in thread "pool-7-thread-1" java.lang.NoSuchMethodError: org.openstreetmap.osmosis.osmbinary.Osmformat$DenseNodes.emptyLongList()Lcom/google/protobuf/Internal$LongList;
	at org.openstreetmap.osmosis.osmbinary.Osmformat$DenseNodes.<init>(Osmformat.java:12453)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$DenseNodes.<clinit>(Osmformat.java:13925)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup.<init>(Osmformat.java:4575)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup.<init>(Osmformat.java:4514)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup$1.parsePartialFrom(Osmformat.java:6521)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup$1.parsePartialFrom(Osmformat.java:6515)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.<init>(Osmformat.java:3077)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.<init>(Osmformat.java:3012)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock$1.parsePartialFrom(Osmformat.java:4372)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock$1.parsePartialFrom(Osmformat.java:4366)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.parseFrom(Osmformat.java:3469)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.processOsmPrimitives(PbfBlobDecoder.java:325)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.runAndTrapExceptions(PbfBlobDecoder.java:343)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.run(PbfBlobDecoder.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-7-thread-2" java.lang.NoClassDefFoundError: Could not initialize class org.openstreetmap.osmosis.osmbinary.Osmformat$DenseNodes
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup.<init>(Osmformat.java:4575)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup.<init>(Osmformat.java:4514)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup$1.parsePartialFrom(Osmformat.java:6521)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup$1.parsePartialFrom(Osmformat.java:6515)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.<init>(Osmformat.java:3077)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.<init>(Osmformat.java:3012)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock$1.parsePartialFrom(Osmformat.java:4372)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock$1.parsePartialFrom(Osmformat.java:4366)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.parseFrom(Osmformat.java:3469)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.processOsmPrimitives(PbfBlobDecoder.java:325)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.runAndTrapExceptions(PbfBlobDecoder.java:343)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.run(PbfBlobDecoder.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-7-thread-3" java.lang.NoSuchMethodError: org.openstreetmap.osmosis.osmbinary.Osmformat$Way.emptyIntList()Lcom/google/protobuf/Internal$IntList;
	at org.openstreetmap.osmosis.osmbinary.Osmformat$Way.<init>(Osmformat.java:14111)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$Way.<clinit>(Osmformat.java:15722)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup.<init>(Osmformat.java:4588)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup.<init>(Osmformat.java:4514)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup$1.parsePartialFrom(Osmformat.java:6521)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup$1.parsePartialFrom(Osmformat.java:6515)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:923)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.<init>(Osmformat.java:3077)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.<init>(Osmformat.java:3012)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock$1.parsePartialFrom(Osmformat.java:4372)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock$1.parsePartialFrom(Osmformat.java:4366)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.parseFrom(Osmformat.java:3469)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.processOsmPrimitives(PbfBlobDecoder.java:325)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.runAndTrapExceptions(PbfBlobDecoder.java:343)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.run(PbfBlobDecoder.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Error has appear in latest branches of 1.0. At least 1.0-pre34 has not this error.

The same OSM-file is being processed just fine.

**Comment by karussell** [comment]
With which GraphHopper version do you get this? If you are using GraphHopper as a Java library it is likely a dependency issue. See also #2019.

**Comment by sgerr** [comment]
Hello! I'm using these maven dependencies:

```
    <dependency>
      <groupId>com.graphhopper</groupId>
      <artifactId>graphhopper-api</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>com.graphhopper</groupId>
      <artifactId>graphhopper-core</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>com.graphhopper</groupId>
      <artifactId>graphhopper-reader-osm</artifactId>
      <version>1.0</version>
    </dependency>
```

**Comment by karussell** [comment]
Ok, so this very likely a dependency issue and you need to exclude the "osmosis-osm-binary" dependency from one of your other dependencies that pulls in an older version.

See the linked discussion in other issue.

**Comment by sgerr** [comment]
Hmmm... Doing the trick 

```
        <dependency>
            <groupId>com.graphhopper</groupId>
            <artifactId>graphhopper-reader-osm</artifactId>
            <version>1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.openstreetmap.osmosis</groupId>
                    <artifactId>osmosis-osm-binary</artifactId>
                    <!--version>0.47.3</version-->
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.openstreetmap.osmosis</groupId>
            <artifactId>osmosis-osm-binary</artifactId>
            <version>0.47</version>
        </dependency>        
```

did not help. The error is different, but still here:

```
Exception in thread "pool-7-thread-1" java.lang.NoSuchMethodError: org.openstreetmap.osmosis.osmbinary.Osmformat$HeaderBlock.getRequiredFeaturesList()Lcom/google/protobuf/ProtocolStringList;
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.processOsmHeader(PbfBlobDecoder.java:83)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.runAndTrapExceptions(PbfBlobDecoder.java:340)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.run(PbfBlobDecoder.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Further downgrading is impossible because of total incompatibility. (((

**Comment by karussell** [comment]
Version 1.0 now requires the latest version of osmosis-osm-binary. So you need to exclude the old osmosis-osm-binary dependency from your other dependencies somewhere.

**Comment by sgerr** [comment]
I have no explicit dependensies on osmosis-osm-binary. Only those I posted before:
```
 <dependency>
      <groupId>com.graphhopper</groupId>
      <artifactId>graphhopper-api</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>com.graphhopper</groupId>
      <artifactId>graphhopper-core</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>com.graphhopper</groupId>
      <artifactId>graphhopper-reader-osm</artifactId>
      <version>1.0</version>
    </dependency>
```
This is resulting in exceptions as I posted earlier.

**Comment by karussell** [comment]
> I have no explicit dependensies on osmosis-osm-binary.

There must be implicit dependencies on osmosis-osm-binary, otherwise you would only pull the latest osmosis-osm-binary.

**Comment by karussell** [comment]
This should help to find it:

> mvn dependency:tree

**Comment by sgerr** [comment]
I cleared .m2 and rebuild project. mvn is showing:

```
INFO] +- com.graphhopper:graphhopper-api:jar:1.0:compile
[INFO] |  \- org.locationtech.jts:jts-core:jar:1.15.1:compile
[INFO] +- com.graphhopper:graphhopper-core:jar:1.0:compile
[INFO] |  +- com.carrotsearch:hppc:jar:0.8.1:compile
[INFO] |  +- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.3:compile
[INFO] |  |  \- commons-io:commons-io:jar:2.6:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] +- com.graphhopper:graphhopper-reader-osm:jar:1.0:compile
[INFO] |  \- org.openstreetmap.osmosis:osmosis-osm-binary:jar:0.47.3:compile
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.6.1:compile
```

**Comment by karussell** [comment]
You need to search for osmosis-osm-binary in another dependency. As I said earlier graphhopper version 1.0 requires osmosis-osm-binary:jar:0.47.3 so the snippet you show is correct.

**Comment by sgerr** [comment]
Yep! Thank you.

**Comment by theqp** [comment]
@karussell 
I had the same issue and upgrading protobuf from 3.6.1 to 3.12.3 solved the issue for me.
Maybe this is related to JDK14.

**Comment by sgerr** [comment]
@theqp, yes. one should search for osmosis-osm-binary or even protobuf in other dependencies and upgrade it if needed.

**Comment by theqp** [comment]
> @theqp, yes. one should search for osmosis-osm-binary or even protobuf in other dependencies and upgrade it if needed.

I forgot to mention that both protobuf and osmosis-osm-binary versions were coming from GraphHopper, not other dependency.
