### ISSUE TITLE
NoSuchElementException in AlternativeRouteEdgeCH#concat

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2125]
This came up during performance measurements on the `measurement_gps` branch: The map was ~~bayern~~germany-190101.osm.pbf and this was using the car encoder.

```
java.lang.RuntimeException: Error while calculating route! nodes: [], request:48.809588728161366,13.802305862129481; 48.79258273210414,13.822429243226258 (alternative_route) (Hints:{ch.disable=false, stall_on_demand=false, lm.disable=true, lm.active_landmarks=-1, instructions=true, way_point_max_distance=0})
	at com.graphhopper.tools.Measurement$14.doCalc(Measurement.java:693)
	at com.graphhopper.util.MiniPerfTest.start(MiniPerfTest.java:51)
	at com.graphhopper.tools.Measurement.printTimeOfRouteQuery(Measurement.java:737)
	at com.graphhopper.tools.Measurement.start(Measurement.java:279)
	at com.graphhopper.tools.Measurement.main(Measurement.java:95)
Caused by: java.util.NoSuchElementException
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1000)
	at com.graphhopper.routing.AlternativeRouteEdgeCH.concat(AlternativeRouteEdgeCH.java:248)
	at com.graphhopper.routing.AlternativeRouteEdgeCH.calcAlternatives(AlternativeRouteEdgeCH.java:133)
	at com.graphhopper.routing.AlternativeRouteEdgeCH.calcPaths(AlternativeRouteEdgeCH.java:260)
	at com.graphhopper.routing.CHPathCalculator.calcPaths(CHPathCalculator.java:65)
	at com.graphhopper.routing.CHPathCalculator.calcPaths(CHPathCalculator.java:47)
	at com.graphhopper.routing.ViaRouting.calcPaths(ViaRouting.java:134)
	at com.graphhopper.routing.Router.routeAlt(Router.java:191)
	at com.graphhopper.routing.Router.route(Router.java:133)
	at com.graphhopper.GraphHopper.route(GraphHopper.java:992)
	at com.graphhopper.tools.Measurement$14.doCalc(Measurement.java:690)
	... 4 more
```

@michaz, maybe this is related to f3d8bd5979d4a7e042e8b4ca274d0bc61ea9baca?

**Comment by michaz** [comment]
> maybe this is related to f3d8bd5?

Yes.

I applied the obvious fix, but I don't have a constructed test (yet) where this can happen. Anyway.
