### ISSUE TITLE
Cygwin and Cmd error with jackson and DropWizard

### ISSUE THREAD

**Issue by ljmartinez1994** [graphhopper/graphhopper#2131]
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/reflect/MalformedParametersException
        at com.fasterxml.jackson.module.paramnames.ParameterNamesModule.setupModule(ParameterNamesModule.java:25)
        at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:817)
        at io.dropwizard.jackson.Jackson.configure(Jackson.java:68)
        at io.dropwizard.jackson.Jackson.newObjectMapper(Jackson.java:30)
        at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:64)
        at io.dropwizard.Application.run(Application.java:86)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:36)
Caused by: java.lang.ClassNotFoundException: java.lang.reflect.MalformedParametersException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 7 more

**Comment by karussell** [comment]
Please provide a step by step guide on how to reproduce this problem. Including versions of cygwin, windows, java and graphhopper.

**Comment by ljmartinez1994** [comment]
Last version of Cynwin, Win10, 
1- java 8 installed
2- Maven 3.6.3 installed
3- Java and Maven configured correctly
4- execute ./graphhopper.sh -a import -i cuba-latest.osm.pbf, and that error appear

Note> the graphhhopper /web/target/graphhopper-web-2.0-SNAPSHOT.jar are generated to correctly

**Comment by ljmartinez1994** [comment]
The error is triggered by this class:
https://github.com/FasterXML/jackson-module-parameter-names/blob/master/src/main/java/com/fasterxml/jackson/module/paramnames/ParameterNamesModule.java
But i set the modules ans nothing, and dont know what i have to do

**Comment by ljmartinez1994** [comment]
$ ./graphhopper.sh -a import -i cuba-latest.osm.pbf -o cuba-gh -fd
## using java  from C:\Program Files\Java\jdk1.8.0
## using existing osm file cuba-latest.osm.pbf
## existing jar found web/target/graphhopper-web-2.0-SNAPSHOT.jar
## now import. JAVA_OPTS=-Xmx4g
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/reflect/MalformedParametersException
        at com.fasterxml.jackson.module.paramnames.ParameterNamesModule.setupModule(ParameterNamesModule.java:25)
        at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:818)
        at io.dropwizard.jackson.Jackson.configure(Jackson.java:68)
        at io.dropwizard.jackson.Jackson.newObjectMapper(Jackson.java:30)
        at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:64)
        at io.dropwizard.Application.run(Application.java:86)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:36)
Caused by: java.lang.ClassNotFoundException: java.lang.reflect.MalformedParametersException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 7 more

**Comment by karussell** [comment]
I cannot reproduce this issue on a recent windows machine.

Make sure that you installed a JDK (at least JDK8 is required, a JRE is not sufficient) and that this is reachable from cygwin.

Also try first with a PBF that is locally reachable or use:

```
./graphhopper.sh -a import -i europe_germany_berlin.pbf
```
