### ISSUE TITLE
CGIARProvider moved to HTTPS

### ISSUE THREAD

**Issue by REASY** [graphhopper/graphhopper#2255]
GraphHopper [web service jar v1.0](https://github.com/graphhopper/graphhopper/releases/tag/1.0) fails when tries to build a graph with elevation data. Logs:
```
2021-03-16 03:10:33.563 [main] INFO  c.g.reader.osm.GraphHopperOSM - version 1.0|2020-05-22T12:08:02Z (5,15,4,3,5,6)
2021-03-16 03:23:23.574 [main] INFO  c.g.reader.dem.CGIARProvider - cgiar Elevation Provider, from: http://srtm.csi.cgiar.org/wp-co
ntent/uploads/files/srtm_5x5/TIFF/, to: /home/ubuntu/git/gh/multiprovider, as: RAM_STORE using interpolate: false
2021-03-16 03:23:23.945 [main] ERROR io.dropwizard.cli.ServerCommand - Unable to start server, shutting down
java.lang.RuntimeException: Couldn't process file map/us-latest.osm.pbf, error: Can't decode srtm_20_07.tif
        at com.graphhopper.reader.osm.OSMReader.writeOsmToGraph(OSMReader.java:297)
        at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:148)
        at com.graphhopper.GraphHopper.importData(GraphHopper.java:709)
        at com.graphhopper.GraphHopper.readData(GraphHopper.java:688)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:675)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:640)
        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:125)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:407)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:36)
Caused by: java.lang.RuntimeException: Can't decode srtm_20_07.tif
        at com.graphhopper.reader.dem.CGIARProvider.generateRasterFromFile(CGIARProvider.java:112)
        at com.graphhopper.reader.dem.AbstractTiffElevationProvider.getEle(AbstractTiffElevationProvider.java:136)
        at com.graphhopper.reader.dem.MultiSourceElevationProvider.getEle(MultiSourceElevationProvider.java:52)
        at com.graphhopper.reader.osm.OSMReader.getElevation(OSMReader.java:528)
        at com.graphhopper.reader.osm.OSMReader.addNode(OSMReader.java:504)
        at com.graphhopper.reader.osm.OSMReader.processNode(OSMReader.java:482)
        at com.graphhopper.reader.osm.OSMReader.writeOsmToGraph(OSMReader.java:264)
        ... 20 common frames omitted
Caused by: java.io.EOFException: null
        at org.apache.xmlgraphics.image.codec.util.SeekableStream.readUnsignedShort(SeekableStream.java:483)
        at org.apache.xmlgraphics.image.codec.tiff.TIFFDirectory.getNumDirectories(TIFFDirectory.java:590)
        at org.apache.xmlgraphics.image.codec.tiff.TIFFImageDecoder.getNumPages(TIFFImageDecoder.java:81)
        at org.apache.xmlgraphics.image.codec.tiff.TIFFImageDecoder.decodeAsRenderedImage(TIFFImageDecoder.java:85)
        at org.apache.xmlgraphics.image.codec.util.ImageDecoderImpl.decodeAsRaster(ImageDecoderImpl.java:136)
        at org.apache.xmlgraphics.image.codec.util.ImageDecoderImpl.decodeAsRaster(ImageDecoderImpl.java:122)
        at com.graphhopper.reader.dem.CGIARProvider.generateRasterFromFile(CGIARProvider.java:110)
        ... 26 common frames omitted
```
The content of that file `srtm_20_07.zip`:
```
ubuntu@ip-172-31-9-198:~/git/gh$ cat multiprovider/srtm_20_07.zip
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_20_07.zip">here</a>.</p>
</body></html>
ubuntu@ip-172-31-9-198:~/git/gh$
```
If I try to curl it, it says it is moved:
```
ubuntu@ip-172-31-9-198:~/git/gh$ curl http://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_20_07.zip -v
*   Trying 45.5.184.24...
* Connected to srtm.csi.cgiar.org (45.5.184.24) port 80 (#0)
> GET /wp-content/uploads/files/srtm_5x5/TIFF/srtm_20_07.zip HTTP/1.1
> Host: srtm.csi.cgiar.org
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Tue, 16 Mar 2021 12:57:07 GMT
< Server: Apache
< Location: https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_20_07.zip
< Content-Length: 288
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_20_07.zip">here</a>.</p>
</body></html>
* Connection #0 to host srtm.csi.cgiar.org left intact
ubuntu@ip-172-31-9-198:~/git/gh$
```

Seems like it is pretty easy fix to in https://github.com/graphhopper/graphhopper/blob/9ea3023bc8bc9c1dc3de3c8bd8d9b3b7ee4cbeb7/core/src/main/java/com/graphhopper/reader/dem/CGIARProvider.java#L57. I can create PR if it is ok.

Thanks.

**Comment by karussell** [comment]
Ah, cool - fixed it in master. You can change the URL also via the config file.

**Comment by karussell** [comment]
Thanks for reporting this and already suggesting the fix!
