### ISSUE TITLE
import command does not stop on exception

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2269]
The following exception is thrown and the import process continues.

```
Exception in thread "PBF Reader" java.lang.RuntimeException: Unable to read PBF file.
        at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:50)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Unable to get next blob from PBF stream.
        at com.graphhopper.reader.osm.pbf.PbfStreamSplitter.getNextBlob(PbfStreamSplitter.java:82)
        at com.graphhopper.reader.osm.pbf.PbfStreamSplitter.hasNext(PbfStreamSplitter.java:89)
        at com.graphhopper.reader.osm.pbf.PbfDecoder.processBlobs(PbfDecoder.java:106)
        at com.graphhopper.reader.osm.pbf.PbfDecoder.run(PbfDecoder.java:162)
        at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:47)
        ... 1 more
Caused by: java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
        at com.graphhopper.reader.osm.pbf.PbfStreamSplitter.readRawBlob(PbfStreamSplitter.java:51)
        at com.graphhopper.reader.osm.pbf.PbfStreamSplitter.getNextBlob(PbfStreamSplitter.java:77)
        ... 5 more
```

This seem to cause to skip only a single way and does not corrupt the binary layout or something but still very ugly.
This does not seem to be a new issue as I found it also in logs of 6th December 2020 but at that time at least a later check stopped the import.

**Comment by otbutz** [comment]
> This seem to cause to skip only a single way

Are you sure?

https://github.com/graphhopper/graphhopper/blob/71681a140b59561b0c93671ab1cf6e72eb3b1af2/core/src/main/java/com/graphhopper/reader/osm/pbf/PbfReader.java#L49-L54

The `finally` block is called regardless which in turn calls `OSMInputFile.complete()`. I'd expect that anything *after* the corrupt blob isn't imported at all.
