### ISSUE TITLE
Calculating time should not require to read speed from edge in wrong direction in map matching

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2296]
See here: https://discuss.graphhopper.com/t/bike-profile-error/6463

**Comment by easbar** [comment]
This GPX reproduces the error

```xml
<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" version="1.1" creator="gpx.py -- https://github.com/tkrajina/gpxpy">
  <trk>
    <trkseg>
      <trkpt lat="47.36424539979" lon="8.51110371766787">
      </trkpt>
      <trkpt lat="47.364303366170304" lon="8.51074177919314">
      </trkpt>
    </trkseg>
  </trk>
</gpx>
```
with this config using a recent OSM extract that includes the above points

```yaml
graphhopper:
  datareader.file: "map.osm"
  graph.location: graph-cache
  graph.flag_encoders: car,bike
  profiles:
    - name: car
      vechicle: car
      weighting: fastest
    - name: bike
      vehicle: bike
      weighting: short_fastest
```

```shell
java -jar graphhopper-web-3.0-SNAPSHOT.jar match --file config.yml --profile bike data.gpx
```

Results in:

```shell
java.lang.IllegalStateException: Calculating time should not require to read speed from edge in wrong direction. (9 - 2) (47.364225310748445,8.51109710415043), (47.36425796220283,8.510880921279213), dist: 16.6819658552161 Reverse:false, fwd:false, bwd:false, fwd-speed: 0.0, bwd-speed: 0.0
        at com.graphhopper.routing.weighting.AbstractWeighting.calcEdgeMillis(AbstractWeighting.java:71)
        at com.graphhopper.routing.weighting.FastestWeighting.calcEdgeMillis(FastestWeighting.java:114)
        at com.graphhopper.routing.InstructionsFromEdges.updatePointsAndInstruction(InstructionsFromEdges.java:445)
        at com.graphhopper.routing.InstructionsFromEdges.next(InstructionsFromEdges.java:291)
        at com.graphhopper.routing.Path.forEveryEdge(Path.java:209)
        at com.graphhopper.routing.InstructionsFromEdges.calcInstructions(InstructionsFromEdges.java:114)
        at com.graphhopper.util.PathMerger.doWork(PathMerger.java:113)
        at com.graphhopper.http.cli.MatchCommand.run(MatchCommand.java:136)
        at com.graphhopper.http.cli.MatchCommand.run(MatchCommand.java:46)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:35)
```

**Comment by easbar** [comment]
The problem was that MatchCommand did not use the right weighting, but always the one for the *first* profile. Therefore `MatchCommand` did not work with multiple profiles *unless* we used the first profile. In the present case we used the second profile.
