### ISSUE TITLE
Updated fr osm pbf file causes outofmemory exception

### ISSUE THREAD

**Issue by HarelM** [graphhopper/graphhopper#2359]
**Describe the bug**
When trying to import a osm.pbf file that was updated using osm-c-tools and minutely updates from the fr storage, graphhopper fails.

**To Reproduce**
1. Download http://download.openstreetmap.fr/extracts/asia/israel_and_palestine-latest.osm.pbf
2. Run `import` using the config file here: https://github.com/IsraelHikingMap/Site/blob/master/gh-config.yml
3. Everything passes without a problem
4. Running on the file `osmupdate` to update it to latest version of the current time and then trying to import this file to GH causes the following exception:
```
## using java 11.0.11 (64bit) from /usr/local/openjdk-11
copying non-default config file: /data/gh-config.yml
## using existing osm file /data/israel-and-palestine-latest.osm.pbf
## existing jar found web/target/graphhopper-web-3.0-SNAPSHOT.jar
## now import. JAVA_OPTS=-Xmx1g -Xms1g -Ddw.server.application_connectors[0].bind_host=0.0.0.0 -Ddw.server.application_connectors[0].port=8989
2021-07-07 12:07:48.344 [main] INFO  c.g.http.GraphHopperManaged - Loaded landmark splitting collection from 
2021-07-07 12:07:48.561 [main] INFO  com.graphhopper.GraphHopper - version 3.0|2021-05-23T06:40:15Z (5,17,4,4,5,7)
2021-07-07 12:07:48.567 [main] INFO  com.graphhopper.GraphHopper - graph CH|car4wd,hike,mtb|RAM_STORE|3D|no_turn_cost|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308, CHGraph|car4wd|NODE_BASED, shortcuts:0 (0MB), nodesCH:0 (0MB), CHGraph|hike|NODE_BASED, shortcuts:0 (0MB), nodesCH:0 (0MB), CHGraph|mtb|NODE_BASED, shortcuts:0 (0MB), nodesCH:0 (0MB)
2021-07-07 12:07:48.570 [main] INFO  com.graphhopper.GraphHopper - start creating graph from /data/israel-and-palestine-latest.osm.pbf
2021-07-07 12:07:48.593 [main] INFO  com.graphhopper.GraphHopper - using CH|car4wd,hike,mtb|RAM_STORE|3D|no_turn_cost|,,,,, memory:totalMB:1024, usedMB:40
2021-07-07 12:07:48.594 [main] INFO  com.graphhopper.reader.osm.OSMReader - Starting to process OSM file: '/data/israel-and-palestine-latest.osm.pbf'
2021-07-07 12:08:05.620 [main] INFO  com.graphhopper.reader.osm.OSMReader - creating graph. Found nodes (pillar+tower):3 869 149, totalMB:1024, usedMB:481
2021-07-07 12:08:07.605 [main] INFO  c.g.reader.dem.SRTMProvider - srtm Elevation Provider, from: https://srtm.kurviger.de/SRTM3/, to: /usr/src/app/elevation, as: RAM_STORE using interpolate: false

Exception in thread "pool-6-thread-1" java.lang.OutOfMemoryError: Java heap space
	at com.google.protobuf.LongArrayList.addLong(LongArrayList.java:179)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$DenseNodes.<init>(Osmformat.java:12540)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$DenseNodes.<init>(Osmformat.java:12443)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$DenseNodes$1.parsePartialFrom(Osmformat.java:13939)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$DenseNodes$1.parsePartialFrom(Osmformat.java:13933)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:888)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup.<init>(Osmformat.java:4575)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup.<init>(Osmformat.java:4514)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup$1.parsePartialFrom(Osmformat.java:6521)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup$1.parsePartialFrom(Osmformat.java:6515)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:888)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.<init>(Osmformat.java:3077)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.<init>(Osmformat.java:3012)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock$1.parsePartialFrom(Osmformat.java:4372)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock$1.parsePartialFrom(Osmformat.java:4366)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.parseFrom(Osmformat.java:3469)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.processOsmPrimitives(PbfBlobDecoder.java:325)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.runAndTrapExceptions(PbfBlobDecoder.java:343)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.run(PbfBlobDecoder.java:355)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
Osm-c-tools update commands:
```
osmconvert --timestamp=2021-07-07T01:14:39Z israel_and_palestine-latest.osm.pbf -o=temp-israel-and-palestine-latest.osm.pbf
// Timestamp is from http://download.openstreetmap.fr/extracts/asia/israel_and_palestine.state.txt
osmupdate israel-and-palestine-latest.osm.pbf israel-and-palestine-latest.osm.osc --base-url=http://download.openstreetmap.fr/replication/asia/israel_and_palestine --minute
```

**Expected behavior**
Graph and folder should be created

**System Information**
I'm running this inside docker, but the I guess this will fail in any environment, it fails relatively fast.

**Screenshots & Logs**

See logs above.

I don't think I can attach the file here as it is 100Mb, I could probably share a link somehow if this can't be easily reproduced, you might be able to download and update a smaller file probably, I don't know, but this one reproduces fairly fast...

As a side note - the idea behind this is to be able to update graphhopper routing more than once a day so updating the osm file and the importing it with graphhopper is our solution, if you think there's a better solution let us know.

Thanks for all the hard work!

**Comment by karussell** [comment]
How much memory do you assign to docker and how much memory does the machine have? What Xmx value did you specify for the import? And can the problem be fixed if you increase it by 20 or 30%?

> totalMB:1024, usedMB:481

Xmx is probably the default of 1GB? If you reduce the Xmx value to e.g. Xmx700m will it still work without running `osmupdate`?

My guess is that osmupdate increases the file so that just more memory is required.

**Comment by HarelM** [comment]
Thanks for the super fast response!
I'm assigning docker a 4 GB memory, the machine has 16Gb.
I ran the import with the default - i.e. 1Gb as can be seen in the log above.
The file before update is actually bigger - 105Mb while the file after is 101Mb.
And the file before the update finishes successfully.
The error happens almost straight at the beginning of the import, it doesn't take long to fail. 
I have a feeling osmupdate changed something in the file that caused a parsing/reading error, but I'm not sure what. I'm able to open this file using my .Net reader so I'm pretty sure the file is valid.
Is there anything else I can test from my end?

**Comment by karussell** [comment]
Ok, this indeed sounds strange and specific to the tool or even geographic export. Unfortunately I do not think we will investigate this if it is does not happen in some "normal" exported PBF, but we would of course welcome any improvements that e.g. makes our reading process more fault tolerant.

btw: we also use osmupdate in our chain (applying it to planet) and did not yet stumble over this problem.

**Comment by HarelM** [comment]
I see. Thanks for the info!
I'll se what I can do...
BTW, Which updates are you using? which extract? at what interval?
I have a feeling this is related to the French extract and minutely updates, but I'm not sure...

**Comment by karussell** [comment]
>  BTW, Which updates are you using? which extract? at what interval?

We use planet pbf and planet updates, I think. But I do not think we use minutely updates only hourly or even only daily but not 100% sure.

**Comment by HarelM** [comment]
I have increased the memory to 2Gb and it seems to finish now.
As you said this is probably currently running on the edge of the memory and seems to pass by a mere luck, I guess...
Odd that a daily file passes while an updated file doesn't.
I'm not sure exactly what's causing this but I'm not very good with Java env...
Feel free to close this issue.
Thanks again for the quick response!
