### ISSUE TITLE
IllegalArgumentException in EdgeKVStorage

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2609]
Unsure how this can happen as we use Helper.cutString before:

```
Caused by: java.lang.IllegalArgumentException: bytes.length cannot be > 255 but was 257
        at com.graphhopper.search.EdgeKVStorage.getBytesForValue(EdgeKVStorage.java:340)
        at com.graphhopper.search.EdgeKVStorage.add(EdgeKVStorage.java:178)
        at com.graphhopper.storage.BaseGraph.setName(BaseGraph.java:467)
        at com.graphhopper.storage.BaseGraph.access$200(BaseGraph.java:45)
        at com.graphhopper.storage.BaseGraph$EdgeIteratorStateImpl.setName(BaseGraph.java:967)
        at com.graphhopper.reader.osm.OSMReader.addEdge(OSMReader.java:337)
        at com.graphhopper.reader.osm.WaySegmentParser$Pass2Handler.handleSegment(WaySegmentParser.java:365)
        at com.graphhopper.reader.osm.WaySegmentParser$Pass2Handler.splitSegmentAtSplitNodes(WaySegmentParser.java:338)
        at com.graphhopper.reader.osm.WaySegmentParser$Pass2Handler.splitLoopSegments(WaySegmentParser.java:299)
        at com.graphhopper.reader.osm.WaySegmentParser$Pass2Handler.splitWayAtJunctionsAndEmptySections(WaySegmentParser.java:274)
        at com.graphhopper.reader.osm.WaySegmentParser$Pass2Handler.handleWay(WaySegmentParser.java:256)
        at com.graphhopper.reader.osm.WaySegmentParser$ReaderElementHandler.handleElement(WaySegmentParser.java:520)
        at com.graphhopper.reader.osm.WaySegmentParser.readOSM(WaySegmentParser.java:396
```

**Comment by otbutz** [comment]
Is it really valid to simply cut UTF8 strings after x bytes?

https://joernhees.de/blog/2010/12/14/how-to-restrict-the-length-of-a-unicode-string/
