### ISSUE TITLE
DirectedRoutingTest failed

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2723]
```
 [INFO] Running com.graphhopper.routing.DirectedRoutingTest
        2023-01-11 22:32:33.280 [main] WARN  c.g.routing.DirectedRoutingTest - expected: []
        2023-01-11 22:32:33.280 [main] WARN  c.g.routing.DirectedRoutingTest - given:    [10]
        2023-01-11 22:32:34.474 [main] WARN  c.g.routing.DirectedRoutingTest - expected: []
        2023-01-11 22:32:34.474 [main] WARN  c.g.routing.DirectedRoutingTest - given:    [41]
        [ERROR] Tests run: 161, Failures: 2, Errors: 0, Skipped: 1, Time elapsed: 3.543 s <<< FAILURE! - in com.graphhopper.routing.DirectedRoutingTest
        [ERROR] randomGraph{Fixture}[9]  Time elapsed: 0.012 s  <<< FAILURE!
        org.opentest4j.AssertionFailedError: wrong weight: 10->10, expected: 1.7976931348623157E308, given: 0.0, seed: 72164598864638
                at com.graphhopper.routing.DirectedRoutingTest.comparePaths(DirectedRoutingTest.java:356)
                at com.graphhopper.routing.DirectedRoutingTest.randomGraph(DirectedRoutingTest.java:242)

        [ERROR] randomGraph{Fixture}[49]  Time elapsed: 0.001 s  <<< FAILURE!
        org.opentest4j.AssertionFailedError: wrong weight: 41->41, expected: 1.7976931348623157E308, given: 0.0, seed: 72165793578121
                at com.graphhopper.routing.DirectedRoutingTest.comparePaths(DirectedRoutingTest.java:356)
                at com.graphhopper.routing.DirectedRoutingTest.randomGraph(DirectedRoutingTest.java:242)
```

**Comment by easbar** [comment]
This seems to be an issue with the new directed unidirectional A* implementation (edf87e626a61482b4f8ad1013353d98c7a485eca) @michaz?
