### ISSUE TITLE
SRTM Service Connection Refused

### ISSUE THREAD

**Issue by Andy1605** [graphhopper/graphhopper#292]
Hello,

If i pull the current master branch of graphhopper i am not compatible with the maps from the maps repository anymore (different graph versions 7 and 9)! So i decided to build maps on my own.
Small maps are no problem (like Schwaben(GER)) but with bigger maps like Germany, i get the following exception while building with graphhopper.sh:

Exception in thread "main" java.lang.RuntimeException: Couldn't process file /home/maps/OSMs/germany.osm, error: java.net.ConnectException: Connection refused
    at com.graphhopper.reader.OSMReader.writeOsm2Graph(OSMReader.java:321)
    at com.graphhopper.reader.OSMReader.readGraph(OSMReader.java:152)
    at com.graphhopper.GraphHopper.importData(GraphHopper.java:623)
    at com.graphhopper.GraphHopper.process(GraphHopper.java:592)
    at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:565)
    at com.graphhopper.tools.Import.main(Import.java:16)
Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection refused
    at com.graphhopper.reader.dem.SRTMProvider.getEle(SRTMProvider.java:302)
    at com.graphhopper.reader.OSMReader.getElevation(OSMReader.java:562)
    at com.graphhopper.reader.OSMReader.addNode(OSMReader.java:547)
    at com.graphhopper.reader.OSMReader.processNode(OSMReader.java:522)
    at com.graphhopper.reader.OSMReader.writeOsm2Graph(OSMReader.java:291)
    ... 5 more
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
    at com.graphhopper.util.Downloader.fetch(Downloader.java:71)
    at com.graphhopper.util.Downloader.downloadFile(Downloader.java:109)
    at com.graphhopper.reader.dem.SRTMProvider.getEle(SRTMProvider.java:264)
    ... 9 more

My SRTM file cache folder contains the following files right after the exception occurred:
dem141189
dem143187
dem143188
dem143189
dem143190
N51E009hgt.zip
N53E008hgt.zip
NE53009hgt.zip
N53E010hgt.zip

I guess this is a time out problem. In this case the time out value should be configurable in the config.properties file.

Greetings.

**Comment by boldtrn** [comment]
I created a mirror for the SRTM data at http://srtm.motoroute.me/. Feel free to use it.

**Comment by karussell** [comment]
We can close here due to the new SRTM provider I think
