### ISSUE TITLE
Issue while deploying with WAR-file

### ISSUE THREAD

**Issue by drnextgis** [graphhopper/graphhopper#297]
I've built WAR-file from current master and trying to deploy it using Jetty8 in Ubuntu.
When I try to open URL in browser I get message `GraphHopper API offline?` and errors in log file:

```
2015-01-10 20:00:23.706:WARN:oejd.WebAppDeployer:WebAppDeployer is deprecated. Use WebAppProvider
2015-01-10 20:00:23.707:INFO:oejs.Server:jetty-8.1.3.v20120416
2015-01-10 20:00:23.750:INFO:oejw.WebInfConfiguration:Extract jar:file:/var/lib/jetty8/webapps/root.war!/ to /var/cache/jetty8/data/jetty-0.0.0.0-8080-root.war--any-/webapp
2015-01-10 20:00:24.350:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
2015-01-10 20:00:24.367:WARN:oejw.StandardDescriptorProcessor:Could not instantiate listener com.graphhopper.http.GuiceServletConfig
java.lang.ClassNotFoundException: com.graphhopper.http.GuiceServletConfig
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:424)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:377)
        at org.eclipse.jetty.server.handler.ContextHandler.loadClass(ContextHandler.java:1471)
        at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1839)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:80)
        at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:67)
        at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:332)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1219)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:699)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:454)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at org.eclipse.jetty.deploy.WebAppDeployer.scan(WebAppDeployer.java:309)
        at org.eclipse.jetty.deploy.WebAppDeployer.doStart(WebAppDeployer.java:189)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:63)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:53)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:91)
        at org.eclipse.jetty.server.Server.doStart(Server.java:262)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1215)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:457)
        at org.eclipse.jetty.start.Main.start(Main.java:602)
        at org.eclipse.jetty.start.Main.main(Main.java:82)
2015-01-10 20:00:24.372:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{,file:/var/cache/jetty8/data/jetty-0.0.0.0-8080-root.war--any-/webapp/},file:/var/lib/jetty8/webapps/root.war
2015-01-10 20:00:24.372:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{,file:/var/cache/jetty8/data/jetty-0.0.0.0-8080-root.war--any-/webapp/},file:/var/lib/jetty8/webapps/root.war
SelectChannelConnector@0.0.0.0:8080
```

This [graphhopper-web-0.2.war](http://oss.sonatype.org/content/groups/public/com/graphhopper/graphhopper-web/0.2/graphhopper-web-0.2.war) file works fine within the same environment.

**Comment by karussell** [comment]
As stated on the mailing list: the main deployment method is bundling a jar file and starting the embedded jetty server. But this war deployment should work too. Here are the necessary steps where I assume tomcat (with location $TOMCAT) but others will work too:

 1. cd web; mvn -DskipTests=true clean install war:war
 2. cp target/*war $TOMCAT/webapps
 3. cp ../config.properties $TOMCAT/
 4. add the following to the copied config.properties
  `graph.location=./graph-cache
   osmreader.osm=your.pbf`
 5. You need to add `host += "/graphhopper-web-0.4-SNAPSHOT";` before `var ghRequest = new GHRequest(host);` in $TOMCAT/webapps/graphhopper-web-0.4-SNAPSHOT/js/main.js so
 6. access http://localhost:8080/graphhopper-web-0.4-SNAPSHOT/

The TODOs in this issue are: document this better and avoid step 5

**Comment by drnextgis** [comment]
Thanks for instruction, now it works fine. Previously for building WAR-file I used the following command from [here](https://github.com/graphhopper/graphhopper/blob/master/docs/core/quickstart-from-source.md#routing-service-deployment):

```
mvn clean war:war
```

**Comment by drnextgis** [comment]
Little notice: in this case some URLs for static assets are broken:

```
GET http://192.168.250.155:8080/img/indicator.gif 404 (Not Found)
GET http://192.168.250.155:8080/img/marker-icon-red.png 404 (Not Found)
GET http://192.168.250.155:8080/img/marker-small-green.png 404 (Not Found)
GET http://192.168.250.155:8080/img/marker-small-red.png 404 (Not Found)
GET http://192.168.250.155:8080/img/marker-icon-green.png 404 (Not Found)
GET http://192.168.250.155:8080/graphhopper-web-0.4-SNAPSHOTimg/marker-icon-green.png 404 (Not Found)
GET http://192.168.250.155:8080/graphhopper-web-0.4-SNAPSHOTimg/left.png 404 (Not Found)
GET http://192.168.250.155:8080/graphhopper-web-0.4-SNAPSHOTimg/right.png 404 (Not Found)
GET http://192.168.250.155:8080/graphhopper-web-0.4-SNAPSHOTimg/slight_left.png 404 (Not Found)
GET http://192.168.250.155:8080/graphhopper-web-0.4-SNAPSHOTimg/slight_right.png 404 (Not Found)
GET http://192.168.250.155:8080/graphhopper-web-0.4-SNAPSHOTimg/sharp_right.png 404 (Not Found)
GET http://192.168.250.155:8080/graphhopper-web-0.4-SNAPSHOTimg/sharp_left.png 404 (Not Found)
GET http://192.168.250.155:8080/graphhopper-web-0.4-SNAPSHOTimg/marker-icon-red.png 404 (Not Found)
```

**Comment by karussell** [comment]
Thanks again! Looks like we should always use (proper) relative paths for resources like image :) 

Would you mind to provide a pull request and test with the normal and this war-deployment?

**Comment by karussell** [comment]
Also do you have an idea how to 'insert' the context like 'graphhopper-web-0.4-SNAPSHOT/' into the request URL for main.js?

**Comment by karussell** [comment]
We'll remove highly likely remove this war deployment support as it currently partial broken and not really tested nor used. See also #1040.
