### ISSUE TITLE
graphhopper profile issue

### ISSUE THREAD

**Issue by momentum123** [graphhopper/graphhopper#3093]
So my use case is I want to import osm file and create graphhopper cache and in my application I just put config to read the graph cache using and dont want to import osm map in run time 

` GraphHopper hopper = new GraphHopper();
        hopper.setGraphHopperLocation(GRAPH_CACHE_PATH);
hopper.setProfiles(new Profile("bike"));
 hopper.load();
        `

NOTE: iam using graphhopper-core 10.0 release version

`Graph: bike|-1189228086
Change configuration to match the graph or delete /Users/me/Downloads/graph-cache/
	at com.graphhopper.GraphHopper.load(GraphHopper.java:1060) ~[graphhopper-core-10.0.jar:na]
`

below are the step how Ima creating graphhoper cache

GRAPH_HOPPER_COMMAND = [
    JAVA_17,
    "-Xmx16g", 
    f"-Ddw.graphhopper.datareader.file={LOCAL_OSM_FILE}",
    f"-Ddw.graphhopper.graph.location={GRAPH_HOPPER_CACHE_DIR}",
    "-jar", 
    LOCAL_GRAPH_HOPPER_JAR, 
    "server", 
    GRAPH_HOPPER_CONFIG_DIR
]

here also Iam graphhopper web jar 10.0 version

here is my config.yml which Iam using in above command 

`graphhopper:

  # OpenStreetMap input file PBF or XML, can be changed via command line -Ddw.graphhopper.datareader.file=some.pbf
  datareader.file: india-latest.osm.pbf
  # Local folder used by graphhopper to store its data
  graph.location: graph-cache

 

  profiles:
   - name: bike
     custom_model_files: [bike.json] # test if bike_elevation.json should be applied.

  profiles_ch:
    - profile: bike

 
  profiles_lm: []

  graph.encoded_values: road_class, road_class_link, road_environment, max_speed, road_access, surface, smoothness, bike_access, bike_average_speed, bike_priority, mtb_rating, hike_rating, roundabout, average_slope

  #### Speed, hybrid and flexible mode ####

  prepare.min_network_size: 200
  prepare.subnetworks.threads: 1

 
  routing.snap_preventions_default: tunnel, bridge, ferry

  routing.non_ch.max_waypoint_distance: 1000000

  import.osm.ignored_highways: motorway,trunk,railway # typically useful for motorized-only routing
  # import.osm.ignored_highways: motorway,trunk # typically useful for non-motorized routing

  # configure the memory access, use RAM_STORE for well equipped servers (default and recommended)
  graph.dataaccess.default_type: RAM_STORE

server:
  application_connectors:
  - type: http
    port: 8989
    # for security reasons bind to localhost
    bind_host: localhost
    # increase GET request limit - not necessary if /maps UI is not used or used without custom models
    max_request_header_size: 50k
  request_log:
      appenders: []
  admin_connectors:
  - type: http
    port: 8990
    bind_host: localhost
# See https://www.dropwizard.io/en/latest/manual/core.html#logging`

 Iam getting below error in my java application while loading graphhopper instance with graph cache.

Graph: bike|-1189228086
Change configuration to match the graph or delete /Users/300069983/Downloads/graph-cache/
	at com.graphhopper.GraphHopper.load(GraphHopper.java:1060) ~[graphhopper-core-10.0.jar:na]

on further looking in graph-cache dir in /Users/300069983/Downloads/graph-cache/properties.txt i see below config

`datareader.import.date=2024-12-24T12:20:02Z
datareader.data.date=2024-12-23T21:21:29Z
profiles=bike|-1189228086
graph.em.version=4
graph.em.bytes_for_flags=9
graph.em.ints_for_turn_cost_flags=0
graph.encoded_values=["{\"className\":\"com.graphhopper.routing.ev.EnumEncodedValue\",\"name\":\"road_class\",\"bits\":5,\"min_storable_value\":0,\"max_storable_value\":31,\"max_value\":20,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":0,\"bwd_data_index\":0,\"fwd_shift\":0,\"bwd_shift\":-1,\"fwd_mask\":31,\"bwd_mask\":0,\"enum_type\":\"com.graphhopper.routing.ev.RoadClass\"}","{\"className\":\"com.graphhopper.routing.ev.SimpleBooleanEncodedValue\",\"name\":\"road_class_link\",\"bits\":1,\"min_storable_value\":0,\"max_storable_value\":1,\"max_value\":1,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":0,\"bwd_data_index\":0,\"fwd_shift\":5,\"bwd_shift\":-1,\"fwd_mask\":32,\"bwd_mask\":0}","{\"className\":\"com.graphhopper.routing.ev.EnumEncodedValue\",\"name\":\"road_environment\",\"bits\":3,\"min_storable_value\":0,\"max_storable_value\":7,\"max_value\":5,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":0,\"bwd_data_index\":0,\"fwd_shift\":6,\"bwd_shift\":-1,\"fwd_mask\":448,\"bwd_mask\":0,\"enum_type\":\"com.graphhopper.routing.ev.RoadEnvironment\"}","{\"className\":\"com.graphhopper.routing.ev.DecimalEncodedValueImpl\",\"name\":\"max_speed\",\"bits\":7,\"min_storable_value\":0,\"max_storable_value\":127,\"max_value\":127,\"negate_reverse_direction\":false,\"store_two_directions\":true,\"fwd_data_index\":0,\"bwd_data_index\":0,\"fwd_shift\":9,\"bwd_shift\":16,\"fwd_mask\":65024,\"bwd_mask\":8323072,\"factor\":2.0,\"use_maximum_as_infinity\":true}","{\"className\":\"com.graphhopper.routing.ev.EnumEncodedValue\",\"name\":\"road_access\",\"bits\":4,\"min_storable_value\":0,\"max_storable_value\":15,\"max_value\":8,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":0,\"bwd_data_index\":0,\"fwd_shift\":23,\"bwd_shift\":-1,\"fwd_mask\":125829120,\"bwd_mask\":0,\"enum_type\":\"com.graphhopper.routing.ev.RoadAccess\"}","{\"className\":\"com.graphhopper.routing.ev.EnumEncodedValue\",\"name\":\"surface\",\"bits\":4,\"min_storable_value\":0,\"max_storable_value\":15,\"max_value\":15,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":0,\"bwd_data_index\":0,\"fwd_shift\":27,\"bwd_shift\":-1,\"fwd_mask\":2013265920,\"bwd_mask\":0,\"enum_type\":\"com.graphhopper.routing.ev.Surface\"}","{\"className\":\"com.graphhopper.routing.ev.EnumEncodedValue\",\"name\":\"smoothness\",\"bits\":4,\"min_storable_value\":0,\"max_storable_value\":15,\"max_value\":9,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":1,\"bwd_data_index\":0,\"fwd_shift\":0,\"bwd_shift\":-1,\"fwd_mask\":15,\"bwd_mask\":0,\"enum_type\":\"com.graphhopper.routing.ev.Smoothness\"}","{\"className\":\"com.graphhopper.routing.ev.SimpleBooleanEncodedValue\",\"name\":\"bike_access\",\"bits\":1,\"min_storable_value\":0,\"max_storable_value\":1,\"max_value\":1,\"negate_reverse_direction\":false,\"store_two_directions\":true,\"fwd_data_index\":1,\"bwd_data_index\":1,\"fwd_shift\":4,\"bwd_shift\":5,\"fwd_mask\":16,\"bwd_mask\":32}","{\"className\":\"com.graphhopper.routing.ev.DecimalEncodedValueImpl\",\"name\":\"bike_average_speed\",\"bits\":4,\"min_storable_value\":0,\"max_storable_value\":15,\"max_value\":14,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":1,\"bwd_data_index\":0,\"fwd_shift\":6,\"bwd_shift\":-1,\"fwd_mask\":960,\"bwd_mask\":0,\"factor\":2.0,\"use_maximum_as_infinity\":false}","{\"className\":\"com.graphhopper.routing.ev.DecimalEncodedValueImpl\",\"name\":\"bike_priority\",\"bits\":4,\"min_storable_value\":0,\"max_storable_value\":15,\"max_value\":13,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":1,\"bwd_data_index\":0,\"fwd_shift\":10,\"bwd_shift\":-1,\"fwd_mask\":15360,\"bwd_mask\":0,\"factor\":0.1,\"use_maximum_as_infinity\":false}","{\"className\":\"com.graphhopper.routing.ev.IntEncodedValueImpl\",\"name\":\"mtb_rating\",\"bits\":3,\"min_storable_value\":0,\"max_storable_value\":7,\"max_value\":7,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":1,\"bwd_data_index\":0,\"fwd_shift\":14,\"bwd_shift\":-1,\"fwd_mask\":114688,\"bwd_mask\":0}","{\"className\":\"com.graphhopper.routing.ev.IntEncodedValueImpl\",\"name\":\"hike_rating\",\"bits\":3,\"min_storable_value\":0,\"max_storable_value\":7,\"max_value\":6,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":1,\"bwd_data_index\":0,\"fwd_shift\":17,\"bwd_shift\":-1,\"fwd_mask\":917504,\"bwd_mask\":0}","{\"className\":\"com.graphhopper.routing.ev.SimpleBooleanEncodedValue\",\"name\":\"roundabout\",\"bits\":1,\"min_storable_value\":0,\"max_storable_value\":1,\"max_value\":1,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":1,\"bwd_data_index\":0,\"fwd_shift\":20,\"bwd_shift\":-1,\"fwd_mask\":1048576,\"bwd_mask\":0}","{\"className\":\"com.graphhopper.routing.ev.DecimalEncodedValueImpl\",\"name\":\"average_slope\",\"bits\":6,\"min_storable_value\":-31,\"max_storable_value\":31,\"max_value\":0,\"negate_reverse_direction\":true,\"store_two_directions\":false,\"fwd_data_index\":1,\"bwd_data_index\":0,\"fwd_shift\":21,\"bwd_shift\":-1,\"fwd_mask\":132120576,\"bwd_mask\":0,\"factor\":1.0,\"use_maximum_as_infinity\":false}","{\"className\":\"com.graphhopper.routing.ev.DecimalEncodedValueImpl\",\"name\":\"ferry_speed\",\"bits\":5,\"min_storable_value\":0,\"max_storable_value\":31,\"max_value\":14,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":1,\"bwd_data_index\":0,\"fwd_shift\":27,\"bwd_shift\":-1,\"fwd_mask\":-134217728,\"bwd_mask\":0,\"factor\":2.0,\"use_maximum_as_infinity\":false}","{\"className\":\"com.graphhopper.routing.ev.EnumEncodedValue\",\"name\":\"bike_network\",\"bits\":3,\"min_storable_value\":0,\"max_storable_value\":7,\"max_value\":4,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":2,\"bwd_data_index\":0,\"fwd_shift\":0,\"bwd_shift\":-1,\"fwd_mask\":7,\"bwd_mask\":0,\"enum_type\":\"com.graphhopper.routing.ev.RouteNetwork\"}","{\"className\":\"com.graphhopper.routing.ev.SimpleBooleanEncodedValue\",\"name\":\"bike_subnetwork\",\"bits\":1,\"min_storable_value\":0,\"max_storable_value\":1,\"max_value\":1,\"negate_reverse_direction\":false,\"store_two_directions\":false,\"fwd_data_index\":2,\"bwd_data_index\":0,\"fwd_shift\":3,\"bwd_shift\":-1,\"fwd_mask\":8,\"bwd_mask\":0}"]
graph.turn_encoded_values=[]
prepare.ch.date.bike=2024-12-24T12:26:45Z
graph.profiles.ch.bike.version=-1189228086
`

**Comment by momentum123** [comment]
I actually wanted to reduce the map load time so that I can serve traffic faster and I dont have to load map file each time. This is why we chose this model where we import map and keep graphhopper cache ready.
