### ISSUE TITLE
Exception when using MMAP_STORE_SYNC and vboxsf filesystem in Linux (Ubuntu)

### ISSUE THREAD

**Issue by milesizzo** [graphhopper/graphhopper#315]
I'm attempting to run the Graphhopper service on an Ubuntu server installation (14.04.1 LTS - Trusty Tahr). I've imported an OSM file from here: http://download.bbbike.org/osm/bbbike/Melbourne/ (Melbourne.osm.pbf) successfully.

Java version:

```
mgi@ubuntu:~/gh/latest$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

Maven version:

```
mgi@ubuntu:~/gh/latest$ mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-40-generic", arch: "amd64", family: "unix"
```

config.properties:

```
#################
### OSMReader ###

graph.dataaccess=RAM_STORE
#graph.dataaccess=MMAP_STORE_SYNC

# Default: use contraction hierarchies to speed things up. requires more RAM/disc space for holding the graph
# Use chWeighting=no to disable it (more flexibility while querying)
# Java API usage is: GraphHopper.setCHWeighting("fastest")
prepare.chWeighting=fastest

# increase from 1 to 5, to reduce way geometry e.g. for android
osmreader.wayPointMaxDistance=1

# Possible options: car,foot,bike,bike2,mtb,racingbike,motorcycle (comma separated)
# When using two or three option together remeber to set "prepare.chWeighting=no" above.
# bike2 takes elevation data into account (like up-hill is slower than down-hill)
# and requires enabling graph.elevation.provider below, e.g. see #169
graph.flagEncoders=car

# to enable turn restrictions for car do
# graph.flagEncoders=car|turnCosts=true

# if you want to reduce storage size and you don't need instructions for a path uncomment this
# osmreader.instructions=false

# To populate your graph with elevation data use SRTM, default is noop
# graph.elevation.provider=srtm
# default location for cache is used /tmp/srtm
# graph.elevation.cachedir=./srtmprovider/
# If you have a slow disk or plenty of RAM change the default MMAP to
# graph.elevation.dataaccess=RAM_STORE

# Location index lookup. Advanced customization. Resolution is in meter, the search specifies the 'radius' in number of tiles.
# E.g. decrease resolution for a faster lookup and increase region search for a more dynamic search and less 'location not found' results
# index.highResolution=300
# index.maxRegionSearch=4

# if you want to support jsonp response type you need to add it explicitely here:
#web.jsonpAllowed=true
```

This runs fine as expected, and on the first run it builds the `Melbourne.osm-gh` directory.

Since I'm going to be eventually working with the full planet data, I need to run in MMAP mode (my dev machine doesn't have enough RAM). So I changed the config.properties `graph.dataaccess` option to be `MMAP_STORE_SYNC`. Upon running I get the following exception:

```
mgi@ubuntu:~/gh/latest$ ./graphhopper.sh web Melbourne.osm-gh
## using java 1.8.0_31 (64bit) from
## using existing osm file Melbourne.osm-gh
## existing jar found tools/target/graphhopper-tools-0.4-SNAPSHOT-jar-with-dependencies.jar
## now web. JAVA_OPTS=-Xmx4g -Xms4g
Feb 02, 2015 3:38:28 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.io.IOException: Invalid argument
java.lang.IllegalStateException: Couldn't load graph
        at com.graphhopper.http.DefaultModule.configure(DefaultModule.java:82)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
        at com.google.inject.AbstractModule.install(AbstractModule.java:118)
        at com.graphhopper.http.GHServer$1.configure(GHServer.java:114)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
        at com.google.inject.spi.Elements.getElements(Elements.java:101)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.graphhopper.http.GHServer.start(GHServer.java:62)
        at com.graphhopper.http.GHServer.main(GHServer.java:48)
Caused by: java.lang.RuntimeException: Couldn't map buffer 0 of 3 at position 100 for 3145628 bytes with offset 100, new fileLength:3145828
        at com.graphhopper.storage.MMapDataAccess.mapIt(MMapDataAccess.java:160)
        at com.graphhopper.storage.MMapDataAccess.loadExisting(MMapDataAccess.java:244)
        at com.graphhopper.storage.SynchedDAWrapper.loadExisting(SynchedDAWrapper.java:141)
        at com.graphhopper.storage.GraphHopperStorage.loadExisting(GraphHopperStorage.java:1379)
        at com.graphhopper.GraphHopper.load(GraphHopper.java:720)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:564)
        at com.graphhopper.http.DefaultModule.createGraphHopper(DefaultModule.java:56)
        at com.graphhopper.http.DefaultModule.configure(DefaultModule.java:69)
        ... 14 more
Caused by: java.io.IOException: Invalid argument
        at sun.nio.ch.FileChannelImpl.map0(Native Method)
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:893)
        at com.graphhopper.storage.MMapDataAccess.newByteBuffer(MMapDataAccess.java:178)
        at com.graphhopper.storage.MMapDataAccess.mapIt(MMapDataAccess.java:152)
        ... 21 more
```

Any help would be greatly appreciated, I have been researching this error for a few days now.

**Comment by milesizzo** [comment]
Not sure if it's significant, but I'm running Linux on an Oracle VM VirtualBox. The virtual machine has 8GB RAM available to it, and two 2.9GHz cores (i7-4600M).

**Comment by devemux86** [comment]
Have you write permissions in the folder where the graph files are?

**Comment by karussell** [comment]
Please check as emux said, that the files are found. E.g. the command
should point the graphhopper script to the original osm file:

./graphhopper.sh web your-file.pbf
or
./graphhopper.sh web your-file.osm

instead of

|./graphhopper.sh web Melbourne.osm-gh|

Peter

**Comment by milesizzo** [comment]
Thanks for the quick responses.

Yep, I've got write permission - Graphhopper created the graph files on the first run.

I get the same exception when I run with the PBF file:

```
mgi@ubuntu:~/gh/latest$ ./graphhopper.sh web Melbourne.osm.pbf
## using java 1.8.0_31 (64bit) from
## using existing osm file Melbourne.osm.pbf
## existing jar found tools/target/graphhopper-tools-0.4-SNAPSHOT-jar-with-dependencies.jar
## now web. JAVA_OPTS=-Xmx4g -Xms4g
Feb 03, 2015 10:58:26 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.io.IOException: Invalid argument
java.lang.IllegalStateException: Couldn't load graph
        at com.graphhopper.http.DefaultModule.configure(DefaultModule.java:82)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
        at com.google.inject.AbstractModule.install(AbstractModule.java:118)
        at com.graphhopper.http.GHServer$1.configure(GHServer.java:114)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
        at com.google.inject.spi.Elements.getElements(Elements.java:101)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.graphhopper.http.GHServer.start(GHServer.java:62)
        at com.graphhopper.http.GHServer.main(GHServer.java:48)
Caused by: java.lang.RuntimeException: Couldn't map buffer 0 of 3 at position 100 for 3145628 bytes with offset 100, new fileLength:3145828
        at com.graphhopper.storage.MMapDataAccess.mapIt(MMapDataAccess.java:160)
        at com.graphhopper.storage.MMapDataAccess.loadExisting(MMapDataAccess.java:244)
        at com.graphhopper.storage.SynchedDAWrapper.loadExisting(SynchedDAWrapper.java:141)
        at com.graphhopper.storage.GraphHopperStorage.loadExisting(GraphHopperStorage.java:1379)
        at com.graphhopper.GraphHopper.load(GraphHopper.java:720)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:564)
        at com.graphhopper.http.DefaultModule.createGraphHopper(DefaultModule.java:56)
        at com.graphhopper.http.DefaultModule.configure(DefaultModule.java:69)
        ... 14 more
Caused by: java.io.IOException: Invalid argument
        at sun.nio.ch.FileChannelImpl.map0(Native Method)
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:893)
        at com.graphhopper.storage.MMapDataAccess.newByteBuffer(MMapDataAccess.java:178)
        at com.graphhopper.storage.MMapDataAccess.mapIt(MMapDataAccess.java:152)
        ... 21 more
```

**Comment by milesizzo** [comment]
Ok, I've found the problem.

On a hunch, I moved all the files to the local ext2 filesystem. This worked.

Before I was running on a [vboxsf filesystem](https://help.ubuntu.com/community/VirtualBox/SharedFolders). Obviously the Java I/O stuff has trouble running on this.

Is this something worth investigating further?

**Comment by karussell** [comment]
It is not the Java I/O it is probably the memory mapping which is not supported or do you only have read-only access? Would be interesting what happens if you set hopper.setAllowWrites(false) as this has worked for other external file systems (obviously you have to place the graphhopper files there as it won't import it automatically)

**Comment by milesizzo** [comment]
So I changed the default `allowWrites` member from `true` to `false` in `core/src/main/java/com/graphhopper/GraphHopper.java` then executed `./graphhopper.sh build`; is that the best way to do it?

Assuming that built as expected, it still got the same error.

**Comment by karussell** [comment]
Yes, this *should* work ;)

Important is that you see in the logs the RO (for readonly)
`graph GraphHopperStorage|bike,car|MMAP_RO|2D....`

Hmmh, it looks that there are at least two other problems we should fix: 

 - [ ] it should be possible to use SYNC and readonly, e.g. DAType.fromString has to be improved
 - [ ] allowWrites should be possible from the config.properties
 - [ ] if allowWrites==true it should be possible to be wrapped in the SYNCed wrapper (not sure if this is currently really the case)

**Comment by devemux86** [comment]
See also #217 

The ```graphHopper.setAllowWrites(false)``` works for me.

**Comment by karussell** [comment]
Yes, it works for Android, no need for SYNC. But for server side we need to support config.properties and also wrapping in the SyncedWrapper which is not yet possible but relative easy to fix.

**Comment by milesizzo** [comment]
Could you add `MMAP_RO` as an option in config.properties?
