### ISSUE TITLE
Graph build fail in rare situations with sac_scale due to BikeFlagEncoder bug

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#351]
I try to build a graph with GH 0.4-rc1 for the Germany region: baden-wuerttemberg-latest.osm.pbf downloaded from Geofabrik today.
(This file was last modified 4 hours ago and contains all OSM data up to 2015-03-03T21:21:02Z.)

I use the options CH off and (car, foot, bike).
But the build fails with:
```java
Exception in thread "PBF Reader" Exception in thread "main" java.lang.RuntimeException: Couldn't process file baden-wuerttemberg-latest.osm.pbf, error: car, no speed found for:cycleway
    at com.graphhopper.reader.OSMReader.writeOsm2Graph(OSMReader.java:319)
    at com.graphhopper.reader.OSMReader.readGraph(OSMReader.java:150)
    at com.graphhopper.GraphHopper.importData(GraphHopper.java:663)
    at com.graphhopper.GraphHopper.process(GraphHopper.java:632)
    at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:605)
    at com.graphhopper.tools.Import.main(Import.java:15)
Caused by: java.lang.IllegalStateException: car, no speed found for:cycleway
    at com.graphhopper.routing.util.CarFlagEncoder.getSpeed(CarFlagEncoder.java:148)
    at com.graphhopper.routing.util.CarFlagEncoder.handleWayTags(CarFlagEncoder.java:227)
    at com.graphhopper.routing.util.EncodingManager.handleWayTags(EncodingManager.java:263)
    at com.graphhopper.reader.OSMReader.processWay(OSMReader.java:367)
    at com.graphhopper.reader.OSMReader.writeOsm2Graph(OSMReader.java:299)
    ... 5 more
java.lang.RuntimeException: Unable to read PBF file.
    at com.graphhopper.reader.pbf.PbfReader.run(PbfReader.java:53)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
    at com.graphhopper.reader.OSMInputFile.process(OSMInputFile.java:265)
    at com.graphhopper.reader.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:106)
    at com.graphhopper.reader.pbf.PbfDecoder.processBlobs(PbfDecoder.java:171)
    at com.graphhopper.reader.pbf.PbfDecoder.run(PbfDecoder.java:184)
    at com.graphhopper.reader.pbf.PbfReader.run(PbfReader.java:49)
    ... 1 more
Caused by: java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2052)
    at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:349)
    at com.graphhopper.reader.OSMInputFile.process(OSMInputFile.java:262)
    ... 5 more
```

**Comment by karussell** [comment]
bike or bike2 and graph.bytesForFlags=4?

**Comment by devemux86** [comment]
bike and default graph.bytesForFlags=4.

**Comment by karussell** [comment]
There was a bug in the bike encoder overwriting the wrong accept bit. Fixed now, please try and reopen if still a problem!

BTW: Thanks a lot for early testing and reporting of RC1!

**Comment by devemux86** [comment]
Thanks Peter!
The builds seem to complete fine now.

Does the fix plays role to the routing too (besides the graph building) ?

**Comment by karussell** [comment]
Could be effected too, yes. But before you rebuild all areas I fear there will be another major edge version change with #352

**Comment by devemux86** [comment]
Not trying to be impatient :) but you mean some time soon?

**Comment by jansoe** [comment]
working on it :)
