### ISSUE TITLE
Sometimes the new threading test fails on JDK8 (travis)

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#518]
```
testMultipleCHPreparationsInParallel(com.graphhopper.GraphHopperTest)  Time elapsed: 0.163 sec  <<< FAILURE!
    java.lang.AssertionError: prepare.date.fastest_car should contain finish time/date [3]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.graphhopper.GraphHopperTest.testMultipleCHPreparationsInParallel(GraphHopperTest.java:859)
```

**Comment by devemux86** [comment]
I have seen that message also trying to build GH locally with Maven on Linux / Java 64bit.

**Comment by karussell** [comment]
I've improved the error messages. If it occurs again - can you please paste the exact AssertionError(s) here?

**Comment by devemux86** [comment]
Yes certainly Peter, I'll watch this.

**Comment by karussell** [comment]
Haven not seen this since them. For now closing here.
