### ISSUE TITLE
Load pbf in GraphHopper using Scala

### ISSUE THREAD

**Issue by nik-ffm** [graphhopper/graphhopper#558]
I tried to run the GraphHopper MapMatching from scala. When I do the importOrLoad function I get the following Error: 

```
Exception in thread "pool-19-thread-1" java.lang.NoClassDefFoundError: com/google/protobuf/ProtocolStringList
	at com.graphhopper.reader.pbf.PbfBlobDecoder.processOsmHeader(PbfBlobDecoder.java:84)
	at com.graphhopper.reader.pbf.PbfBlobDecoder.runAndTrapExceptions(PbfBlobDecoder.java:382)
	at com.graphhopper.reader.pbf.PbfBlobDecoder.run(PbfBlobDecoder.java:404)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.ProtocolStringList
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

My Code looks like:
```
import java.util.List;

import com.graphhopper.GraphHopper;
import com.graphhopper.routing.util.CarFlagEncoder;
import com.graphhopper.routing.util.EncodingManager;
import com.graphhopper.storage.GraphHopperStorage;
import com.graphhopper.storage.index.LocationIndexTree;
import com.graphhopper.util.GPXEntry;

val hopper = new GraphHopper();
hopper.setOSMFile("src/main/resources/karlsruhe.osm.pbf");
hopper.setGraphHopperLocation("./target/mapmatchingtest");
val encoder = new CarFlagEncoder();
hopper.setEncodingManager(new EncodingManager(encoder));
hopper.setCHEnable(false);
hopper.importOrLoad();
```

Running the code as java version works just fine. Any ideas?

**Comment by karussell** [comment]
Please use the forum and check if you specified the correct dependencies.
