### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#561]
I would like to see a Debian package of GraphHopper. Someone interested in this too?

There is e.g. ElasticSearch which ships a deb package and builds it via [a custom pom.xml](https://github.com/elastic/elasticsearch/blob/2.1/distribution/deb)

**Comment by devemux86** [comment]
:+1: 
Interesting idea!

You mean the core package?

**Comment by karussell** [comment]
The core and web, yes. Including the script to make GraphHopper available for more users and easier. The problem is that then the GraphHopper in Debian will be very old compared to master, but even without this I see benefits like just providing the deb package.

**Comment by boldtrn** [comment]
Additionally it would be nice to have a service file for Debian (or systemd in general) to load graphhopper on server startup.

**Comment by akuckartz** [comment]
:+1:

**Comment by karussell** [comment]
With [fpm](https://github.com/jordansissel/fpm) it is already partly working but unfortunately we need two packages ([see this issue](https://github.com/jordansissel/fpm/issues/1529)): one package that installs the files and one for the service.

Here are the steps:

1. edit the config-example.yml and add

```yml
  datareader.file: /opt/graphhopper/berlin-latest.osm.pbf
  graph.location: /opt/graphhopper/graph-cache
```

2. create a graphhopper file with:

```sh
#!/bin/sh
# change dir so that logs go into /var/log/graphhopper/logs
cd /var/log/graphhopper
java -jar /opt/graphhopper/graphhopper-web-0.13-SNAPSHOT.jar server /etc/graphhopper/config-example.yml
```

3. create an empty log file (workaround to create /var/log/graphhopper/logs in a later step)
```bash
echo '' > gh.log
```
4. Install fpm
```bash
# install ruby
sudo apt-get install ruby ruby-dev rubygems build-essential
# install fpm
sudo gem install --no-ri --no-rdoc fpm
```

5. create deb packages
```bash
fpm -n graphhopper -s dir -t deb --deb-no-default-config-files --config-files /etc/graphhopper/config-example.yml -v 0.13 web/target/graphhopper-web-0.13-SNAPSHOT.jar=/opt/graphhopper/ config-example.yml=/etc/graphhopper/ graphhopper=/usr/bin/ /tmp/gh.log=/var/log/graphhopper/logs/
# create service deb package
fpm -v 0.13 -s pleaserun -t deb --deb-no-default-config-files -n graphhopper-service /usr/bin/graphhopper
```

6. install the packages

```bash
sudo dpkg -i graphhopper_0.13_amd64.deb
sudo dpkg -i graphhopper-service_0.13_amd64.deb
```

7. start the service

```bash
sudo systemctl start graphhopper
# open localhost:8989 in the browser 
# see the log
tail -f /var/log/graphhopper/logs/graphhopper.log
journalctl -u graphhopper
```

**Comment by piiskop** [comment]
peacecop@peacecop-HP-ProBook-4520s:/var/log/graphhopper$ java -jar /home/peacecop/graphhopper/graphhopper-web-0.13.0.jar server /home/peacecop/graphhopper/config-example.yml
io.dropwizard.configuration.ConfigurationParsingException: /home/peacecop/graphhopper/config-example.yml has an error:
  * Malformed YAML at line: 6, column: 56; while parsing a block mapping
 in 'reader', line 1, column 1:
    graphhopper:
    ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 11, column 3:
      graph.flag_encoders: car
      ^

 at [Source: (FileInputStream); line: 5, column: 55]

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:96)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:34)
Caused by: com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping
 in 'reader', line 1, column 1:
    graphhopper:
    ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 11, column 3:
      graph.flag_encoders: car
      ^

 at [Source: (FileInputStream); line: 5, column: 55]
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:27)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:359)
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:825)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:247)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2384)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:81)
	... 5 more
Caused by: while parsing a block mapping
 in 'reader', line 1, column 1:
    graphhopper:
    ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 11, column 3:
      graph.flag_encoders: car
      ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:355)
	... 12 more
