### ISSUE TITLE
Unable to start graphhopper after disabling the speed mode in config 

### ISSUE THREAD

**Issue by trippah** [graphhopper/graphhopper#599]
I am trying to disable speed mode so I can use the "heading" parameter for my routing.

prepare.chWeighting=no
#prepare.chWeighting=fastest

I receive following error when trying to restart graphhopper with this setting.

existing jar found tools/target/graphhopper-tools-0.6-SNAPSHOT-jar-with-dependencies.jar
now web. JAVA_OPTS=-Xmx1000m -Xms1000m -server
Dec 08, 2015 10:57:42 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.IllegalStateException: Configured graph.chWeightings: [] is not equal to loaded [fastest|car]
java.lang.IllegalStateException: Couldn't load graph
	at com.graphhopper.http.DefaultModule.configure(DefaultModule.java:84)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.AbstractModule.install(AbstractModule.java:122)
	at com.graphhopper.http.GHServer$1.configure(GHServer.java:117)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.graphhopper.http.GHServer.start(GHServer.java:64)
	at com.graphhopper.http.GHServer.main(GHServer.java:50)
Caused by: java.lang.IllegalStateException: Configured graph.chWeightings: [] is not equal to loaded [fastest|car]
	at com.graphhopper.storage.GraphHopperStorage.loadExisting(GraphHopperStorage.java:282)
	at com.graphhopper.GraphHopper.load(GraphHopper.java:826)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:664)
	at com.graphhopper.http.DefaultModule.createGraphHopper(DefaultModule.java:56)
	at com.graphhopper.http.DefaultModule.configure(DefaultModule.java:69)
	... 14 more

Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Explicit bindings are required and java.lang.Boolean annotated with @com.google.inject.name.Named(value=jsonpAllowed) is not explicitly bound.
  while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=jsonpAllowed)
    for field at com.graphhopper.http.GHBaseServlet.jsonpAllowed(GHBaseServlet.java:41)
  at com.graphhopper.http.GHServletModule.configureServlets(GHServletModule.java:61) (via modules: com.graphhopper.http.GHServer$1 -> com.graphhopper.http.GHServletModule)

2) Explicit bindings are required and java.lang.Boolean annotated with @com.google.inject.name.Named(value=jsonpAllowed) is not explicitly bound.
  while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=jsonpAllowed)
    for field at com.graphhopper.http.GHBaseServlet.jsonpAllowed(GHBaseServlet.java:41)
  at com.graphhopper.http.GHServletModule.configureServlets(GHServletModule.java:64) (via modules: com.graphhopper.http.GHServer$1 -> com.graphhopper.http.GHServletModule)

3) Explicit bindings are required and java.lang.Boolean annotated with @com.google.inject.name.Named(value=jsonpAllowed) is not explicitly bound.
  while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=jsonpAllowed)
    for field at com.graphhopper.http.GHBaseServlet.jsonpAllowed(GHBaseServlet.java:41)
  at com.graphhopper.http.GHServletModule.configureServlets(GHServletModule.java:67) (via modules: com.graphhopper.http.GHServer$1 -> com.graphhopper.http.GHServletModule)

4) Explicit bindings are required and java.lang.Boolean annotated with @com.google.inject.name.Named(value=jsonpAllowed) is not explicitly bound.
  while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=jsonpAllowed)
    for field at com.graphhopper.http.GHBaseServlet.jsonpAllowed(GHBaseServlet.java:41)
  at com.graphhopper.http.GHServletModule.configureServlets(GHServletModule.java:70) (via modules: com.graphhopper.http.GHServer$1 -> com.graphhopper.http.GHServletModule)

5) An exception was caught and reported. Message: Couldn't load graph
  at com.graphhopper.http.GHServer$1.configure(GHServer.java:117) (via modules: com.graphhopper.http.GHServer$1 -> com.graphhopper.http.DefaultModule)

6) Explicit bindings are required and com.graphhopper.GraphHopper is not explicitly bound.
  while locating com.graphhopper.GraphHopper
    for field at com.graphhopper.http.GraphHopperServlet.hopper(GraphHopperServlet.java:56)
  at com.graphhopper.http.GHServletModule.configureServlets(GHServletModule.java:67) (via modules: com.graphhopper.http.GHServer$1 -> com.graphhopper.http.GHServletModule)

7) Explicit bindings are required and com.graphhopper.http.RouteSerializer is not explicitly bound.
  while locating com.graphhopper.http.RouteSerializer
    for field at com.graphhopper.http.GraphHopperServlet.routeSerializer(GraphHopperServlet.java:56)
  at com.graphhopper.http.GHServletModule.configureServlets(GHServletModule.java:67) (via modules: com.graphhopper.http.GHServer$1 -> com.graphhopper.http.GHServletModule)

8) Explicit bindings are required and com.graphhopper.util.TranslationMap is not explicitly bound.
  while locating com.graphhopper.util.TranslationMap
    for field at com.graphhopper.http.I18NServlet.map(I18NServlet.java:36)
  at com.graphhopper.http.GHServletModule.configureServlets(GHServletModule.java:61) (via modules: com.graphhopper.http.GHServer$1 -> com.graphhopper.http.GHServletModule)

9) Explicit bindings are required and com.graphhopper.GraphHopper is not explicitly bound.
  while locating com.graphhopper.GraphHopper
    for field at com.graphhopper.http.InfoServlet.hopper(InfoServlet.java:40)
  at com.graphhopper.http.GHServletModule.configureServlets(GHServletModule.java:64) (via modules: com.graphhopper.http.GHServer$1 -> com.graphhopper.http.GHServletModule)

10) Explicit bindings are required and com.graphhopper.GraphHopper is not explicitly bound.
  while locating com.graphhopper.GraphHopper
    for field at com.graphhopper.http.NearestServlet.hopper(NearestServlet.java:40)
  at com.graphhopper.http.GHServletModule.configureServlets(GHServletModule.java:70) (via modules: com.graphhopper.http.GHServer$1 -> com.graphhopper.http.GHServletModule)

10 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.graphhopper.http.GHServer.start(GHServer.java:64)
	at com.graphhopper.http.GHServer.main(GHServer.java:50)
Caused by: java.lang.IllegalStateException: Couldn't load graph
	at com.graphhopper.http.DefaultModule.configure(DefaultModule.java:84)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.AbstractModule.install(AbstractModule.java:122)
	at com.graphhopper.http.GHServer$1.configure(GHServer.java:117)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	... 5 more
Caused by: java.lang.IllegalStateException: Configured graph.chWeightings: [] is not equal to loaded [fastest|car]
	at com.graphhopper.storage.GraphHopperStorage.loadExisting(GraphHopperStorage.java:282)
	at com.graphhopper.GraphHopper.load(GraphHopper.java:826)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:664)
	at com.graphhopper.http.DefaultModule.createGraphHopper(DefaultModule.java:56)
	at com.graphhopper.http.DefaultModule.configure(DefaultModule.java:69)
	... 14 more

**Comment by karussell** [comment]
Please use our forum for discussion. Here you need to remove the graphhopper folder before restarting. Let me know if this does not fix your problem. Also it is probably wise to use 0.5 instead of the latest snapshot.
