### ISSUE TITLE
Build problem on travis due to permission problems of npm folder

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#632]
Reported today here:
- https://github.com/graphhopper/graphhopper/pull/631#issuecomment-168191724
- https://github.com/graphhopper/graphhopper/pull/625#issuecomment-168134489

```
npm ERR! Error: Attempt to unlock leaflet@^0.7.7, which hasn't been locked
npm ERR!     at unlock (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/cache/add-named.js:41:20
npm ERR!     at /home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
```

Restarting the tests did not solve the problem, but strange enough trying a new branch with a possible fix and without the fix => then the build passed in both cases: https://travis-ci.org/graphhopper/graphhopper/branches

But it gets stranger: restarted the PRs once more ... now one of the two builds passed! https://travis-ci.org/graphhopper/graphhopper/pull_requests

See also: https://github.com/npm/npm/issues/4815 and https://github.com/travis-ci/travis-ci/issues/2244

**Comment by karussell** [comment]
For now assume this change https://github.com/graphhopper/graphhopper/commit/09a5dd43b10d5423724524997b04ae9f0a68c153 fixes this issue and we open this again if not

**Comment by karussell** [comment]
Still happening: #638

**Comment by karussell** [comment]
Getting this problem occasionally.

Furthermore the travis bash script is faulty returning 'tests pass' even if unit test failed when npm tests pass. For now this makes too much trouble and we remove the npm tests from the travis script.
