### ISSUE TITLE
DateRangeParserTest fails

### ISSUE THREAD

**Issue by ratrun** [graphhopper/graphhopper#647]
Compiling the current master on windows using jdk1.8.0_66 creates following error

```
-------------------------------------------------------------------------------
Test set: com.graphhopper.reader.osm.conditional.DateRangeParserTest
-------------------------------------------------------------------------------
Tests run: 17, Failures: 1, Errors: 4, Skipped: 0, Time elapsed: 0.031 sec <<< FAILURE! - in com.graphhopper.reader.osm.conditional.DateRangeParserTest
testParseSimpleDateRangeWithoutYearAndDay2(com.graphhopper.reader.osm.conditional.DateRangeParserTest)  Time elapsed: 0 sec  <<< ERROR!
java.text.ParseException: Unparseable date: "Mar"
	at com.graphhopper.reader.osm.conditional.DateRangeParser.parseDateString(DateRangeParser.java:84)
	at com.graphhopper.reader.osm.conditional.DateRangeParser.parseDateRange(DateRangeParser.java:107)
	at com.graphhopper.reader.osm.conditional.DateRangeParserTest.testParseSimpleDateRangeWithoutYearAndDay2(DateRangeParserTest.java:78)

testParseConditional(com.graphhopper.reader.osm.conditional.DateRangeParserTest)  Time elapsed: 0 sec  <<< ERROR!
java.text.ParseException: Unparseable date: "2014 Dec 15"
	at com.graphhopper.reader.osm.conditional.DateRangeParser.parseDateString(DateRangeParser.java:84)
	at com.graphhopper.reader.osm.conditional.DateRangeParserTest.assertSameDate(DateRangeParserTest.java:214)
	at com.graphhopper.reader.osm.conditional.DateRangeParserTest.testParseConditional(DateRangeParserTest.java:36)

testParseReverseDateRangeDayOnly(com.graphhopper.reader.osm.conditional.DateRangeParserTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.graphhopper.reader.osm.conditional.DateRangeParserTest.testParseReverseDateRangeDayOnly(DateRangeParserTest.java:199)

testParseReverseDateRange(com.graphhopper.reader.osm.conditional.DateRangeParserTest)  Time elapsed: 0 sec  <<< ERROR!
java.text.ParseException: Unparseable date: "2015 Mar 10"
	at com.graphhopper.reader.osm.conditional.DateRangeParser.parseDateString(DateRangeParser.java:84)
	at com.graphhopper.reader.osm.conditional.DateRangeParser.parseDateRange(DateRangeParser.java:110)
	at com.graphhopper.reader.osm.conditional.DateRangeParserTest.testParseReverseDateRange(DateRangeParserTest.java:88)

testParseReverseDateRangeWithoutYearAndDay(com.graphhopper.reader.osm.conditional.DateRangeParserTest)  Time elapsed: 0 sec  <<< ERROR!
java.text.ParseException: Unparseable date: "Mar"
	at com.graphhopper.reader.osm.conditional.DateRangeParser.parseDateString(DateRangeParser.java:84)
	at com.graphhopper.reader.osm.conditional.DateRangeParser.parseDateRange(DateRangeParser.java:110)
	at com.graphhopper.reader.osm.conditional.DateRangeParserTest.testParseReverseDateRangeWithoutYearAndDay(DateRangeParserTest.java:111)
```

**Comment by karussell** [comment]
Thanks & strange as we have a windows CI server successfully running this. But can you print Locale.getDefault() for this test?

**Comment by hbruch** [comment]
Same here. Locale.getDefault() in my case is "de_DE".

**Comment by ratrun** [comment]
The problem vanished when I changed the region settings for the date&time format into English (United States).

**Comment by karussell** [comment]
Thanks for confirming my guess! I'll see how to force US for reading these OSM properties

**Comment by karussell** [comment]
puh, this wasn't easy due to some Calendar ugliness :/

But should be fixed now and I also made other places more 'date stuff stable'. 

Would you try again @ratrun & @hbruch ?

**Comment by hbruch** [comment]
Yes, tests pass now, thanks!
