### ISSUE TITLE
problem when trying to run graphhopper with entire map of europe

### ISSUE THREAD

**Issue by kkalera** [graphhopper/graphhopper#760]
Hi everyone,

I am trying to set up my own graphhopper server. Works fine with the europe_belgium.pbf but I am getting a lot of errors when I am trying to run the entire map of europe.

The problem occurs when I run the following command;
`export GH_FOREGROUND=false && export JETTY_PORT=11111 && ./graphhopper.sh web europe.pbf`

this is the entire error that I get;
`2016-07-31 17:20:05,780 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - version 0.8|2016-07-31T14:03:05Z (5,14,4,3,3,2)
2016-07-31 17:20:05,794 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - graph CH|car|RAM_STORE|2D|NoExt|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308, CHGraph|fastest|car, shortcuts:0, nodesCH:(0MB)
2016-07-31 17:20:05,863 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - start creating graph from europe.pbf
2016-07-31 17:20:05,867 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - using CH|car|RAM_STORE|2D|NoExt|,,,,, memory:totalMB:958, usedMB:26
2016-07-31 17:20:18,804 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 50539203 - could not parse the conditional value:no @ week 44-21 of tag:access:conditional. Exception:Unparseable date: "week 44"
2016-07-31 17:20:18,804 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 50539203 - could not parse the conditional value:no @ week 44-21 of tag:access:conditional. Exception:Unparseable date: "week 44"
2016-07-31 17:21:00,438 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51718691 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:00,438 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51718691 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:05,078 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51760930 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:05,078 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51760930 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:05,078 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51760931 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:05,079 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51760931 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:05,079 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51760933 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:05,079 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51760933 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:05,079 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51760934 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:05,079 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51760934 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:05,080 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51761206 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:21:05,080 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 51761206 - could not parse the conditional value:no @ (2016 Jul 15-2014 Jul 18) of tag:vehicle:conditional. Exception:From after to makes no sense, except for isYearless and isDayOnly DateRanges. From:YEAR_MONTH_DAY; 2016-07-15T00:00:00Z To:YEAR_MONTH_DAY; 2014-07-18T00:00:00Z
2016-07-31 17:22:01,183 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 52514452 - could not parse the conditional value:no @ (Sa-So) of tag:motorcycle:conditional. Exception:Unparseable date: "So"
2016-07-31 17:22:01,184 [main] WARN  com.graphhopper.reader.osm.conditional.ConditionalOSMTagInspector - 52514476 - could not parse the conditional value:no @ (Sa-So) of tag:motorcycle:conditional. Exception:Unparseable date: "So"
Exception in thread "PBF Reader" Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3308)
	at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.ensureSize(GHLongIntBTree.java:382)
	at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.insertKeyValue(GHLongIntBTree.java:295)
	at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.put(GHLongIntBTree.java:206)
	at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.put(GHLongIntBTree.java:220)
	at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.put(GHLongIntBTree.java:220)
	at com.graphhopper.coll.GHLongIntBTree$BTreeEntry.put(GHLongIntBTree.java:220)
	at com.graphhopper.coll.GHLongIntBTree.put(GHLongIntBTree.java:82)
	at com.graphhopper.reader.osm.OSMReader.prepareHighwayNode(OSMReader.java:663)
	at com.graphhopper.reader.osm.OSMReader.preProcess(OSMReader.java:191)
	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:154)
	at com.graphhopper.GraphHopper.importData(GraphHopper.java:776)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:742)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:715)
	at com.graphhopper.http.DefaultModule.createGraphHopper(DefaultModule.java:57)
	at com.graphhopper.http.DefaultModule.configure(DefaultModule.java:70)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.AbstractModule.install(AbstractModule.java:122)
	at com.graphhopper.http.GHServer$1.configure(GHServer.java:124)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.graphhopper.http.GHServer.start(GHServer.java:63)
	at com.graphhopper.http.GHServer.main(GHServer.java:49)
java.lang.RuntimeException: Unable to read PBF file.
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:292)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:107)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.processBlobs(PbfDecoder.java:172)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.run(PbfDecoder.java:185)
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:49)
	... 1 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:350)
	at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:289)
	... 5 more
`

Thank you in advance

**Comment by kkalera** [comment]
The issue seems to be resolved by starting with a new clone, so I probably caused it myself :)

**Comment by devemux86** [comment]
Nevertheless have a close look at your log, you had an `OutOfMemoryError` at some point.

**Comment by kkalera** [comment]
@devemux86 Thank you for that, I didn't notice the `OutOfMemoryError` , I will keep an eye on it, if I run into errors again.

**Comment by kkalera** [comment]
Still experiencing problems when trying to run large pbf files.

europe_belgium.pbf works fine, this what I run into when I try europe.pbf;

still getting the `OutOfMemoryError` while RAM did not exceed 21% and enough disk space available.

`Exception in thread "pool-3-thread-2" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.openstreetmap.osmosis.osmbinary.Osmformat$Way$1.parsePartialFrom(Osmformat.java:10593)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$Way$1.parsePartialFrom(Osmformat.java:10588)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup.<init>(Osmformat.java:3441)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup.<init>(Osmformat.java:3368)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup$1.parsePartialFrom(Osmformat.java:3496)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveGroup$1.parsePartialFrom(Osmformat.java:3491)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.<init>(Osmformat.java:2421)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.<init>(Osmformat.java:2356)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock$1.parsePartialFrom(Osmformat.java:2471)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock$1.parsePartialFrom(Osmformat.java:2466)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:137)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.openstreetmap.osmosis.osmbinary.Osmformat$PrimitiveBlock.parseFrom(Osmformat.java:2722)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.processOsmPrimitives(PbfBlobDecoder.java:369)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.runAndTrapExceptions(PbfBlobDecoder.java:393)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.run(PbfBlobDecoder.java:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-3-thread-3" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1038)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.buildTags(PbfBlobDecoder.java:144)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.processWays(PbfBlobDecoder.java:279)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.processOsmPrimitives(PbfBlobDecoder.java:377)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.runAndTrapExceptions(PbfBlobDecoder.java:393)
	at com.graphhopper.reader.osm.pbf.PbfBlobDecoder.run(PbfBlobDecoder.java:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

`

**Comment by karussell** [comment]
Please use our forum to ask questions. 

Please there include description about your problem, how you start it and also potentially previously log statements
