### ISSUE TITLE
getting errors when importing with bike2 config

### ISSUE THREAD

**Issue by BanuUnal** [graphhopper/graphhopper#764]
i want to create routing data with bike2 configuration but getting a errors
My config.properties:
graph.flag_encoders=bike2
graph.elevation.provider=srtm
prepare.ch.weightings=fastest
prepare.ch.weightings=no
prepare.min_network_size=200
prepare.min_one_way_network_size=200
graph.dataaccess=RAM_STORE

weird thing is it creates the folder with it's content just fine when using graph.flag_encoders=car 

./graphhopper.sh import /Users/USER/Downloads/belgium-latest.osm.pbf 
using java 1.7.0_80 (64bit) from 
using existing osm file /Users/USER/Downloads/belgium-latest.osm.pbf
existing jar found tools/target/graphhopper-tools-0.8-SNAPSHOT-jar-with-dependencies.jar
now import. JAVA_OPTS=-Xmx1000m -Xms1000m -server
INFO  com.graphhopper.reader.osm.GraphHopperOSM - version 0.8|2016-08-04T13:02:58Z (5,14,4,3,3,2)
INFO  com.graphhopper.reader.osm.GraphHopperOSM - graph bike2|RAM_STORE|3D|NoExt|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308
INFO  com.graphhopper.reader.osm.GraphHopperOSM - start creating graph from /Users/USER/Downloads/belgium-latest.osm.pbf
INFO  com.graphhopper.reader.osm.GraphHopperOSM - using bike2|RAM_STORE|3D|NoExt|,,,,, memory:totalMB:959, usedMB:26
INFO  com.graphhopper.reader.osm.OSMReader - 50 000 (preprocess), osmWayMap:83 538 totalMB:906, usedMB:193
INFO  com.graphhopper.reader.osm.OSMReader - creating graph. Found nodes (pillar+tower):4 162 857, totalMB:906, usedMB:196
INFO  com.graphhopper.reader.dem.SRTMProvider - SRTM Elevation Provider, from: http://srtm.kurviger.de/SRTM3/, to: /Users/USER/Documents/Github/graphhopper, as: MMAP_STORE
Exception in thread "PBF Reader" java.lang.RuntimeException: Unable to read PBF file.
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Thread was interrupted.
	at com.graphhopper.reader.osm.pbf.PbfDecoder.waitForUpdate(PbfDecoder.java:68)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:91)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.processBlobs(PbfDecoder.java:172)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.run(PbfDecoder.java:185)
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:49)
	... 1 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2052)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.waitForUpdate(PbfDecoder.java:64)
	... 5 more
Exception in thread "main" java.lang.RuntimeException: Couldn't process file /Users/USER/Downloads/belgium-latest.osm.pbf, error: Index: 2, Size: 1
	at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:334)
	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:158)
	at com.graphhopper.GraphHopper.importData(GraphHopper.java:776)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:742)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:715)
	at com.graphhopper.tools.Import.main(Import.java:33)
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.graphhopper.storage.MMapDataAccess.getShort(MMapDataAccess.java:329)
	at com.graphhopper.reader.dem.HeightTile.getHeight(HeightTile.java:101)
	at com.graphhopper.reader.dem.SRTMProvider.getEle(SRTMProvider.java:258)
	at com.graphhopper.reader.osm.OSMReader.getElevation(OSMReader.java:631)
	at com.graphhopper.reader.osm.OSMReader.addNode(OSMReader.java:616)
	at com.graphhopper.reader.osm.OSMReader.processNode(OSMReader.java:591)
	at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:300)
	... 5 more

**Comment by devemux86** [comment]
Do you use the latest GraphHopper with the SRTM provider fix?

See also the related discussion [here](https://discuss.graphhopper.com/t/arrayindexoutofboundsexception-when-creating-graph-with-elevation/903) in the forum.

**Comment by BanuUnal** [comment]
yes this error is with the latest version (updated an hour ago)

**Comment by devemux86** [comment]
The error arises from the http use for the SRTM provider, instead of https.
This was fixed in latest commit https://github.com/graphhopper/graphhopper/commit/33a268811aaae53358263503ad850506e1488669 but your log above shows that you still use the http in the url.

**Comment by BanuUnal** [comment]
if i opened the file at core/src/main/java/com/graphhopper/reader/dem/SRTMProvider.java
it had the fix but i just re-cloned the repo and tried again, that fixed the problem
thanks you very much for your fast replies
