### ISSUE TITLE
GraphHopper crash on Android 4.1

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#914]
Sample crashes on Android 4.1 at application exit with the following exception:

```java
Caused by: java.lang.IllegalArgumentException: expected receiver of type java.nio.DirectByteBuffer, but got java.nio.MappedByteBufferAdapter
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.graphhopper.util.Helper$1.run(Helper.java:377)
   at java.security.AccessController.doPrivileged(AccessController.java:60)
   at com.graphhopper.util.Helper.cleanMappedByteBuffer(Helper.java:366)
   at com.graphhopper.storage.MMapDataAccess.clean(MMapDataAccess.java:356)
   at com.graphhopper.storage.MMapDataAccess.close(MMapDataAccess.java:257)
   at com.graphhopper.storage.MMapDataAccess.close(MMapDataAccess.java:249)
   at com.graphhopper.storage.StorableProperties.close(StorableProperties.java:113)
   at com.graphhopper.storage.GraphHopperStorage.close(GraphHopperStorage.java:277)
   at com.graphhopper.GraphHopper.close(GraphHopper.java:1222)
```

**Comment by karussell** [comment]
I think this is related to #852 where I was hoping to get 'freeing' support for Android. See [here](https://github.com/graphhopper/graphhopper/pull/852/files#diff-51df64a4a568a4658650309e94a648f5R377)

Would you mind to try if using java.nio.MappedByteBufferAdapter instead of Class.forName("java.nio.DirectByteBuffer") works? It [should have](http://www.docjar.com/docs/api/java/nio/MappedByteBufferAdapter.html) a free method too.

**Comment by devemux86** [comment]
(it was [reported](https://groups.google.com/forum/#!topic/cruiser-users/fMdYzqRzPWQ) in Cruiser forum - I should test more often older Android versions :slightly_frowning_face: )

`java.nio.MappedByteBufferAdapter` isn't public right?

**Comment by karussell** [comment]
Is cruiser using the latest master? (I guess, yes)

> I should test more often older Android versions :slightly_frowning_face:

Ah, so newer versions work with this code. Interesting.

> java.nio.MappedByteBufferAdapter isn't public right?

Yes, it is package protected. But with reflection we might still get it via `dbbFreeMethod.setAccessible(true);`?

**Comment by devemux86** [comment]
Using `Class.forName("java.nio.MappedByteBufferAdapter")` seems to work.

> Is cruiser using the latest master? (I guess, yes)

Yes always with latest master of Mapsforge / VTM / GraphHopper! :slightly_smiling_face: 

> Ah, so newer versions work with this code. Interesting.

Yes back to Android 5 it works, not checked on what version exactly the crash starts happening.

**Comment by devemux86** [comment]
But `java.nio.MappedByteBufferAdapter` does not work on desktop with e.g. Java 8 (Oracle) due to:
```java
java.lang.ClassNotFoundException: java.nio.MappedByteBufferAdapter
```

**Comment by karussell** [comment]
Can you have a look if the commit in branch android_bug_914 fixes the problem and still runs on other versions?

> But java.nio.MappedByteBufferAdapter does not work on desktop with e.g. Java 8 (Oracle) due to:

Sure, this was just a quick test and the commit should make it working everywhere - at least I hope so.

**Comment by devemux86** [comment]
I checked `android_bug_914` branch on Android (latest & older) and on desktop and buffers clean seems working fine!

**Comment by karussell** [comment]
Merged

**Comment by karussell** [comment]
With #934 we use the JDK8 approach for all Android versions except if the buffer is of type MappedByteBufferAdapter
