### ISSUE TITLE
Android: Clean mapped byte buffers fails

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#933]
On Android the clean of mapped byte buffers fails with:

```java
Caused by: java.lang.RuntimeException: unable to unmap the mapped buffer
   at com.graphhopper.util.Helper.cleanMappedByteBuffer(Helper.java:426)
   at com.graphhopper.storage.MMapDataAccess.clean(MMapDataAccess.java:356)
   at com.graphhopper.storage.MMapDataAccess.close(MMapDataAccess.java:257)
   at com.graphhopper.storage.MMapDataAccess.close(MMapDataAccess.java:249)
   at com.graphhopper.storage.StorableProperties.close(StorableProperties.java:113)
   at com.graphhopper.storage.GraphHopperStorage.close(GraphHopperStorage.java:277)
   at com.graphhopper.GraphHopper.close(GraphHopper.java:1226)
   at com.graphhopper.android.MainActivity.onDestroy(MainActivity.java:170)
   at android.app.Activity.performDestroy(Activity.java:6881)
   at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)
   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4190)
   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221) 
   at android.app.ActivityThread.-wrap6(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:154) 
   at android.app.ActivityThread.main(ActivityThread.java:6119) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
Caused by: java.security.PrivilegedActionException: java.lang.NoSuchMethodException: free []
   at java.security.AccessController.doPrivileged(AccessController.java:71)
   at com.graphhopper.util.Helper.cleanMappedByteBuffer(Helper.java:370)
   at com.graphhopper.storage.MMapDataAccess.clean(MMapDataAccess.java:356) 
   at com.graphhopper.storage.MMapDataAccess.close(MMapDataAccess.java:257) 
   at com.graphhopper.storage.MMapDataAccess.close(MMapDataAccess.java:249) 
   at com.graphhopper.storage.StorableProperties.close(StorableProperties.java:113) 
   at com.graphhopper.storage.GraphHopperStorage.close(GraphHopperStorage.java:277) 
   at com.graphhopper.GraphHopper.close(GraphHopper.java:1226) 
   at com.graphhopper.android.MainActivity.onDestroy(MainActivity.java:170) 
   at android.app.Activity.performDestroy(Activity.java:6881) 
   at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153) 
   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4190) 
   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221) 
   at android.app.ActivityThread.-wrap6(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:154) 
   at android.app.ActivityThread.main(ActivityThread.java:6119) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
Caused by: java.lang.NoSuchMethodException: free []
   at java.lang.Class.getMethod(Class.java:1981)
   at java.lang.Class.getMethod(Class.java:1637)
   at com.graphhopper.util.Helper$1.run(Helper.java:377)
   at java.security.AccessController.doPrivileged(AccessController.java:67)
   at com.graphhopper.util.Helper.cleanMappedByteBuffer(Helper.java:370) 
   at com.graphhopper.storage.MMapDataAccess.clean(MMapDataAccess.java:356) 
   at com.graphhopper.storage.MMapDataAccess.close(MMapDataAccess.java:257) 
   at com.graphhopper.storage.MMapDataAccess.close(MMapDataAccess.java:249) 
   at com.graphhopper.storage.StorableProperties.close(StorableProperties.java:113) 
   at com.graphhopper.storage.GraphHopperStorage.close(GraphHopperStorage.java:277) 
   at com.graphhopper.GraphHopper.close(GraphHopper.java:1226) 
   at com.graphhopper.android.MainActivity.onDestroy(MainActivity.java:170) 
   at android.app.Activity.performDestroy(Activity.java:6881) 
   at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153) 
   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4190) 
   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221) 
   at android.app.ActivityThread.-wrap6(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:154) 
   at android.app.ActivityThread.main(ActivityThread.java:6119) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

As reported [here](https://github.com/graphhopper/graphhopper/commit/5bb35ec908eca8d565b22cf8e53df56ccc991315#commitcomment-20465349).

**Comment by devemux86** [comment]
@karussell [asked](https://github.com/graphhopper/graphhopper/commit/5bb35ec908eca8d565b22cf8e53df56ccc991315#commitcomment-20465910) to run the following before the error:
```java
Method[] m = directByteBufferClass.getDeclaredMethods();
for (int i = 0; i < m.length; i++)
          log(m[i].toString());
```

On Android Nougat 7.1 we get:

```java
private byte java.nio.DirectByteBuffer.get(long)
private char java.nio.DirectByteBuffer.getChar(long)
private double java.nio.DirectByteBuffer.getDouble(long)
private float java.nio.DirectByteBuffer.getFloat(long)
private int java.nio.DirectByteBuffer.getInt(long)
private long java.nio.DirectByteBuffer.getLong(long)
private short java.nio.DirectByteBuffer.getShort(long)
private long java.nio.DirectByteBuffer.ix(int)
private java.nio.ByteBuffer java.nio.DirectByteBuffer.putChar(long,char)
private java.nio.ByteBuffer java.nio.DirectByteBuffer.putDouble(long,double)
private java.nio.ByteBuffer java.nio.DirectByteBuffer.putFloat(long,float)
private java.nio.ByteBuffer java.nio.DirectByteBuffer.putInt(long,int)
private java.nio.ByteBuffer java.nio.DirectByteBuffer.putLong(long,long)
private java.nio.ByteBuffer java.nio.DirectByteBuffer.putShort(long,short)
byte java.nio.DirectByteBuffer._get(int)
void java.nio.DirectByteBuffer._put(int,byte)
public long java.nio.DirectByteBuffer.address()
public java.nio.CharBuffer java.nio.DirectByteBuffer.asCharBuffer()
public java.nio.DoubleBuffer java.nio.DirectByteBuffer.asDoubleBuffer()
public java.nio.FloatBuffer java.nio.DirectByteBuffer.asFloatBuffer()
public java.nio.IntBuffer java.nio.DirectByteBuffer.asIntBuffer()
public java.nio.LongBuffer java.nio.DirectByteBuffer.asLongBuffer()
public java.nio.ByteBuffer java.nio.DirectByteBuffer.asReadOnlyBuffer()
public java.nio.ShortBuffer java.nio.DirectByteBuffer.asShortBuffer()
public java.lang.Object java.nio.DirectByteBuffer.attachment()
public sun.misc.Cleaner java.nio.DirectByteBuffer.cleaner()
public java.nio.ByteBuffer java.nio.DirectByteBuffer.compact()
public java.nio.ByteBuffer java.nio.DirectByteBuffer.duplicate()
public byte java.nio.DirectByteBuffer.get()
public byte java.nio.DirectByteBuffer.get(int)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.get(byte[],int,int)
public char java.nio.DirectByteBuffer.getChar()
public char java.nio.DirectByteBuffer.getChar(int)
char java.nio.DirectByteBuffer.getCharUnchecked(int)
public double java.nio.DirectByteBuffer.getDouble()
public double java.nio.DirectByteBuffer.getDouble(int)
double java.nio.DirectByteBuffer.getDoubleUnchecked(int)
public float java.nio.DirectByteBuffer.getFloat()
public float java.nio.DirectByteBuffer.getFloat(int)
float java.nio.DirectByteBuffer.getFloatUnchecked(int)
public int java.nio.DirectByteBuffer.getInt()
public int java.nio.DirectByteBuffer.getInt(int)
int java.nio.DirectByteBuffer.getIntUnchecked(int)
public long java.nio.DirectByteBuffer.getLong()
public long java.nio.DirectByteBuffer.getLong(int)
long java.nio.DirectByteBuffer.getLongUnchecked(int)
public short java.nio.DirectByteBuffer.getShort()
public short java.nio.DirectByteBuffer.getShort(int)
short java.nio.DirectByteBuffer.getShortUnchecked(int)
void java.nio.DirectByteBuffer.getUnchecked(int,char[],int,int)
void java.nio.DirectByteBuffer.getUnchecked(int,double[],int,int)
void java.nio.DirectByteBuffer.getUnchecked(int,float[],int,int)
void java.nio.DirectByteBuffer.getUnchecked(int,int[],int,int)
void java.nio.DirectByteBuffer.getUnchecked(int,long[],int,int)
void java.nio.DirectByteBuffer.getUnchecked(int,short[],int,int)
public boolean java.nio.DirectByteBuffer.isAccessible()
public boolean java.nio.DirectByteBuffer.isDirect()
public boolean java.nio.DirectByteBuffer.isReadOnly()
public java.nio.ByteBuffer java.nio.DirectByteBuffer.put(byte)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.put(int,byte)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.put(long,byte)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.put(byte[],int,int)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putChar(char)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putChar(int,char)
void java.nio.DirectByteBuffer.putCharUnchecked(int,char)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putDouble(double)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putDouble(int,double)
void java.nio.DirectByteBuffer.putDoubleUnchecked(int,double)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putFloat(float)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putFloat(int,float)
void java.nio.DirectByteBuffer.putFloatUnchecked(int,float)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putInt(int)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putInt(int,int)
void java.nio.DirectByteBuffer.putIntUnchecked(int,int)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putLong(int,long)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putLong(long)
void java.nio.DirectByteBuffer.putLongUnchecked(int,long)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putShort(int,short)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.putShort(short)
void java.nio.DirectByteBuffer.putShortUnchecked(int,short)
void java.nio.DirectByteBuffer.putUnchecked(int,char[],int,int)
void java.nio.DirectByteBuffer.putUnchecked(int,double[],int,int)
void java.nio.DirectByteBuffer.putUnchecked(int,float[],int,int)
void java.nio.DirectByteBuffer.putUnchecked(int,int[],int,int)
void java.nio.DirectByteBuffer.putUnchecked(int,long[],int,int)
void java.nio.DirectByteBuffer.putUnchecked(int,short[],int,int)
public void java.nio.DirectByteBuffer.setAccessible(boolean)
public java.nio.ByteBuffer java.nio.DirectByteBuffer.slice()
```

**Comment by karussell** [comment]
Nice, there seems to be public sun.misc.Cleaner java.nio.DirectByteBuffer.cleaner() !

**Comment by karussell** [comment]
Can you try what happens for if you remove the whole android block `if (Constants.ANDROID) {...}`

I'll also test on Android 5, what we get there.

**Comment by devemux86** [comment]
>Can you try what happens for if you remove the whole android block `if (Constants.ANDROID) {...}`

Working on Android 7.1 (I'll try also on Android 4.X).

**Comment by karussell** [comment]
Hmmh, darn. There is this catch which could hide non functional code: `} catch (NoSuchMethodException ex2) {`. Can you temporarily remove this too?

**Comment by karussell** [comment]
Looks like it works on Android 5 even without the catch. See #934

**Comment by devemux86** [comment]
I tested #934, works on Android 7.

On Android 4.1 we have the exception:

```java
NoSuchMethodException | java.nio.MappedByteBufferAdapter | 0
java.lang.NoSuchMethodException: cleaner []
    at java.lang.Class.getConstructorOrMethod(Class.java:460)
    at java.lang.Class.getMethod(Class.java:915)
    at com.graphhopper.util.Helper$1.run(Helper.java:397)
    at java.security.AccessController.doPrivileged(AccessController.java:60)
    at com.graphhopper.util.Helper.cleanMappedByteBuffer(Helper.java:370)
    at com.graphhopper.storage.MMapDataAccess.clean(MMapDataAccess.java:356)
    at com.graphhopper.storage.MMapDataAccess.close(MMapDataAccess.java:257)
    at com.graphhopper.storage.MMapDataAccess.close(MMapDataAccess.java:249)
    at com.graphhopper.storage.index.LocationIndexTree.close(LocationIndexTree.java:322)
    at com.graphhopper.GraphHopper.close(GraphHopper.java:1229)
    at com.graphhopper.android.MainActivity.onDestroy(MainActivity.java:170)
    at android.app.Activity.performDestroy(Activity.java:5172)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1109)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3260)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3291)
    at android.app.ActivityThread.access$1200(ActivityThread.java:130)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4745)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
```

And the declared methods list is:

```java
public java.nio.CharBuffer java.nio.MappedByteBufferAdapter.asCharBuffer()
public java.nio.DoubleBuffer java.nio.MappedByteBufferAdapter.asDoubleBuffer()
public java.nio.FloatBuffer java.nio.MappedByteBufferAdapter.asFloatBuffer()
public java.nio.IntBuffer java.nio.MappedByteBufferAdapter.asIntBuffer()
public java.nio.LongBuffer java.nio.MappedByteBufferAdapter.asLongBuffer()
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.asReadOnlyBuffer()
public java.nio.ShortBuffer java.nio.MappedByteBufferAdapter.asShortBuffer()
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.compact()
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.duplicate()
public final void java.nio.MappedByteBufferAdapter.free()
public byte java.nio.MappedByteBufferAdapter.get()
public byte java.nio.MappedByteBufferAdapter.get(int)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.get(byte[],int,int)
public char java.nio.MappedByteBufferAdapter.getChar()
public char java.nio.MappedByteBufferAdapter.getChar(int)
public double java.nio.MappedByteBufferAdapter.getDouble()
public double java.nio.MappedByteBufferAdapter.getDouble(int)
public float java.nio.MappedByteBufferAdapter.getFloat()
public float java.nio.MappedByteBufferAdapter.getFloat(int)
public int java.nio.MappedByteBufferAdapter.getInt()
public int java.nio.MappedByteBufferAdapter.getInt(int)
public long java.nio.MappedByteBufferAdapter.getLong()
public long java.nio.MappedByteBufferAdapter.getLong(int)
public short java.nio.MappedByteBufferAdapter.getShort()
public short java.nio.MappedByteBufferAdapter.getShort(int)
public boolean java.nio.MappedByteBufferAdapter.isDirect()
public boolean java.nio.MappedByteBufferAdapter.isReadOnly()
void java.nio.MappedByteBufferAdapter.limitImpl(int)
void java.nio.MappedByteBufferAdapter.orderImpl(java.nio.ByteOrder)
void java.nio.MappedByteBufferAdapter.positionImpl(int)
[B java.nio.MappedByteBufferAdapter.protectedArray()
int java.nio.MappedByteBufferAdapter.protectedArrayOffset()
boolean java.nio.MappedByteBufferAdapter.protectedHasArray()
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.put(byte)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.put(int,byte)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.put(byte[],int,int)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putChar(char)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putChar(int,char)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putDouble(double)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putDouble(int,double)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putFloat(float)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putFloat(int,float)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putInt(int)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putInt(int,int)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putLong(int,long)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putLong(long)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putShort(int,short)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.putShort(short)
public java.nio.ByteBuffer java.nio.MappedByteBufferAdapter.slice()
```

**Comment by karussell** [comment]
Thanks, then we use MappedByteBufferAdapter.free() there ...

**Comment by karussell** [comment]
Included the the slightly changed old fix in #934 ... would you try once again without the `catch(NoSuchMethodException)`?

This could be something that works properly for all (tested) Android and JDK8+9

**Comment by devemux86** [comment]
I tested the updated #934 on Android 7, Android 4.X and even on Android 2.3.
No problem so far! :+1:

**Comment by karussell** [comment]
Nice & Thanks for those many tests :) ! Will keep it still open for a bit.

**Comment by karussell** [comment]
Something is still wrong with the mmap handling. When leaving the app this exception is raised:

```
        W/c*.g*.u*.Helper(15240): NoSuchMethodException | 0
        W/c*.g*.u*.Helper(15240): java.lang.NoSuchMethodException: cleaner []
        W/c*.g*.u*.Helper(15240): 	at java.lang.Class.getMethod(Class.java:671)
        W/c*.g*.u*.Helper(15240): 	at com.graphhopper.util.Helper$1.run(Helper.java:406)
        W/c*.g*.u*.Helper(15240): 	at java.security.AccessController.doPrivileged(AccessController.java:60)
```

**Comment by devemux86** [comment]
Hmm have not tested it also on Android 5.. :slightly_smiling_face:

**Comment by karussell** [comment]
Can be easily fixed as there is also a free method: https://android.googlesource.com/platform/libcore/+/android-5.0.2_r1/luni/src/main/java/java/nio/DirectByteBuffer.java

**Comment by devemux86** [comment]
@karussell I'm afraid I cannot confirm your findings on Android `5.1.1`.
The old code runs without errors on a device I tested.. :slightly_frowning_face:

**Comment by karussell** [comment]
That would be strange as I was able to reproduce this. (And meanwhile I was allowed to upgrade to 6.x)

Maybe there is a difference between 5.1.1 and 5.0 and they just said that I had 5.1?

**Comment by devemux86** [comment]
Oh, I forgot again to change in `build.gradle` the repositories.
So indeed with old code I see too the exception on 5.1.1, good finding! :slightly_smiling_face:
