### ISSUE TITLE
SpatialRuleLookup fails for small areas

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#957]
If the area is rather small like core/files/monaco.osm.gz we get:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.graphhopper.routing.util.spatialrules.SpatialRuleLookupArray.getRuleContainerIndex(SpatialRuleLookupArray.java:125)
	at com.graphhopper.routing.util.spatialrules.SpatialRuleLookupArray.isBorderTile(SpatialRuleLookupArray.java:135)
	at com.graphhopper.routing.util.spatialrules.SpatialRuleLookupArray.lookupRule(SpatialRuleLookupArray.java:103)
```

Maybe the loop in isBorderTile should pick the min(2, lookupArray[0].length) somehow?

**Comment by karussell** [comment]
Ah, or just the equals is missing in getRuleContainerIndex? `xIndex >= lookupArray.length`

**Comment by boldtrn** [comment]
Is this fixed? I tried monaco with the current master and did not receive an exception.

**Comment by karussell** [comment]
Again my mistake: have accidentally committed this in the landmark change :/

https://github.com/graphhopper/graphhopper/commit/e085c0b3f3b1e8a3b5942d0938218bec40a357f3#diff-b6259a4439e6674e5604699ad102c0de
